Added list of tests case to help
ydb-platform/nbs pull request #1050
Opened 2024-04-24 15:40 UTC by EvgeniyKozev

2024-04-24 15:45 UTC, WilyTiger requested changes

2024-04-24 15:45 UTC, WilyTiger commented on cloud/blockstore/tools/testing/eternal_tests/test_runner/lib/test_configs.py
> +def get_description_test_case():
достаточно вывести _DISK_CONFIGS и _FS_CONFIGS. Остальное это описание некоторых дополнительных параметров не для всех тестов

2024-05-13 16:54 UTC, qkrorlqr commented on cloud/blockstore/tools/testing/eternal_tests/test_runner/lib/test_configs.py
> +def get_description_test_case():
get_test_case_description

2024-05-13 16:56 UTC, qkrorlqr commented on cloud/blockstore/tools/testing/eternal_tests/test_runner/lib/arg_parser.py
> +                                                     '\n\t./yc-nbs-run-eternal-load-tests setup-test --cluster <cluster> --cluster-config-path <config-path> --test-case eternal-640gb-verify-checkpoin
какая километровая строчка, давай перенесем на несколько строк

2024-05-17 12:29 UTC, WilyTiger commented on cloud/blockstore/tools/testing/eternal_tests/test_runner/lib/test_configs.py
> +def get_description_test_case():
Я понимаю что ты хочешь сделать, я тебе говорю о том что, то что ты выводишь это не тест кейсы. У тебя в этом списке будут дубли. Нету таких тестов - Load test cases и IPC test cases. Есть тесты с фс, дисками и бд. _LOAD_CONFIGS описывает в целом нагрузку для утилиты eternal_load по названию теста. IPC это тоже просто дополнительный параметр для некоторых тестов

2024-05-17 12:30 UTC, WilyTiger commented on cloud/blockstore/tools/testing/eternal_tests/test_runner/lib/test_configs.py
> +def get_description_test_case():
Тебе нужно вывести _DISK_CONFIGS, _FS_CONFIGS и _DB

2024-06-06 10:07 UTC, closed without merging