Don't erase first numerical character in sensor name in prometheus format
ydb-platform/nbs pull request #1094
Opened 2024-05-01 17:13 UTC by dvrazumov

2024-05-01 18:25 UTC, qkrorlqr commented
нужен юниттест

2024-05-01 18:25 UTC, qkrorlqr requested changes
надо портировать в репозиторий ydb тоже

2024-05-02 13:00 UTC, dvrazumov commented
> надо портировать в репозиторий ydb тоже

https://github.com/ydb-platform/ydb/pull/4226

2024-05-02 13:05 UTC, qkrorlqr commented on library/cpp/monlib/encode/prometheus/prometheus_encoder_ut.cpp
> +    Y_UNIT_TEST(InvalidCharactersShouldBeReplaced) {
{ не там

2024-05-02 13:06 UTC, qkrorlqr commented on library/cpp/monlib/encode/prometheus/prometheus_encoder_ut.cpp
> +    Y_UNIT_TEST(FirstCharacterShouldNotBeReplaced) {
{ не там

2024-05-02 13:25 UTC, qkrorlqr approved these changes

2024-05-02 13:45 UTC, EvgeniyKozev approved these changes

2024-05-02 14:44 UTC, merged