Parallelize migration and shadow disk fill
ydb-platform/nbs pull request #1096
Opened 2024-05-02 05:55 UTC by drbasic

2024-05-02 15:01 UTC, drbasic commented on cloud/blockstore/libs/storage/volume/volume_ut.cpp
> +        UNIT_ASSERT_VALUES_EQUAL(60, migrationProgressCounter);
Вот тут поменялась чиселка, какой процент миграции завершен. 
Раньше процент вычислялся как текущий персистентно сохраненный индекс к размеру диска. 
Это плохая метрика, так как не учитывает что не все девайсы нужно мигрировать. Сейчас сделал чтобы вычислялось как (Размер-ОсталосьМигрировать)/Размер.
Однако вылезла проблема. ОсталосьМигрировать учитывает размер последнего девайса, даже если он использован не полностью.
И по этому процент снизился с 80 до 60.
@qkrorlqr   чем продиктовано что в тестах мы делаем размер диска в 2.5 девайса?

2024-05-03 06:53 UTC, komarevtsev-d commented on cloud/blockstore/libs/storage/partition_nonrepl/part_nonrepl_migration_common_actor_migration.cpp
> +    CachedMigrationProgressAchieved = std::nullopt;
Это поле кроме этого метода нигде не используется? Зачем она поле тогда?

2024-05-03 06:53 UTC, komarevtsev-d commented on cloud/blockstore/libs/storage/partition_nonrepl/part_nonrepl_migration_common_actor_migration.cpp
> +            CachedMigrationProgressAchieved.value_or(0));
По логике вещей `CachedMigrationProgressAchieved` здесь всегда nullopt

2024-05-03 06:53 UTC, komarevtsev-d commented on cloud/blockstore/libs/storage/partition_nonrepl/part_nonrepl_migration_common_actor_migration.cpp
> +    if (!ProcessingBlocks.IsProcessingStarted()) {
Может тогда заодно переименуешь в `IsProcessing` или в `IsProcessingEnabled` по аналогии?

Если процессинг уже завершился, то это не значит что он не стартовал.

2024-05-03 06:53 UTC, komarevtsev-d commented on cloud/blockstore/libs/storage/partition_nonrepl/part_nonrepl_migration_common_actor_mirror.cpp
>      }
А зачем этот код? Мы когда начнём миграцию новго блока, то увидим есть ли запись в процессе и отложим если что.

2024-05-03 07:51 UTC, drbasic commented on cloud/blockstore/libs/storage/partition_nonrepl/part_nonrepl_migration_common_actor_migration.cpp
> +    CachedMigrationProgressAchieved = std::nullopt;
Я написал комментарий в объявлении поля.
Смысл такой:
Когда мы мигрировали блок, который содержит (или находится правее) смещения, которое нужно сохранить персистентно, то нужно дождаться всех блоков, которые левее этого смещения и отчитаться наверх что мы достигли нового прогресса миграции. 
Может случится что сначала мигрирует блок, который установит CachedMigrationProgressAchieved, а потом мигрирует блок левее, и вот когда этот блок левее мигрировал и больше нет inflight никого левее CachedMigrationProgressAchieved мы можем отчитаться наверх о новых достижениях)

2024-05-03 07:52 UTC, drbasic commented on cloud/blockstore/libs/storage/partition_nonrepl/part_nonrepl_migration_common_actor_migration.cpp
> +            CachedMigrationProgressAchieved.value_or(0));
выше коммент

2024-05-03 07:52 UTC, drbasic commented on cloud/blockstore/libs/storage/partition_nonrepl/part_nonrepl_migration_common_actor_mirror.cpp
>      }
написал коммент. Нам нужно дать приоритет миграции, иначе клиент, долбящий в один блок застопорит миграцию

2024-05-03 08:00 UTC, komarevtsev-d approved these changes

2024-05-03 12:27 UTC, qkrorlqr commented on cloud/blockstore/libs/storage/partition_nonrepl/part_nonrepl_migration_actor.cpp
> +TDuration TNonreplicatedPartitionMigrationActor::CalculateMigrationTimeout(
я теперь вообще не вижу смысла в этой враппер-функции, можно просто по месту звать TimeoutCalculator.CalculateTimeout(range)

2024-05-03 12:28 UTC, qkrorlqr commented on cloud/blockstore/libs/storage/partition_nonrepl/part_nonrepl_migration_actor.cpp
> +TDuration TNonreplicatedPartitionMigrationActor::CalculateMigrationTimeout(
а, это же часть интерфейса, ок

2024-05-03 15:45 UTC, qkrorlqr requested changes

2024-05-03 15:45 UTC, qkrorlqr commented on cloud/blockstore/libs/storage/partition_nonrepl/part_nonrepl_migration_common_actor_migration.cpp
> +    CachedMigrationProgressAchieved = std::nullopt;
Какая-то сложная логика накручена. Мы знаем по битмапе в ProcessingBlocks, какие блоки мигрировали, какие - нет. Когда очередной рейндж мигрирует, мы можем просто пытаться прокрутить какой-нибудь LastMigratedIndex вперед, пока не наткнемся на блок, для которого соответствующий бит в битмапе не выставлен. И далее если LastMigratedIndex >= nextCachedProgress, репортить изменение прогресса.

2024-05-03 15:45 UTC, qkrorlqr commented on cloud/blockstore/libs/storage/partition_nonrepl/part_nonrepl_migration_common_actor_migration.cpp
> +    CachedMigrationProgressAchieved = std::nullopt;
А, блин, теперь в ProcessingBlocks по факту не обработанные блоки могут быть помечены как Processed. Как-то сложнее теперь код воспринимать.

2024-05-03 15:45 UTC, qkrorlqr commented on cloud/blockstore/libs/storage/partition_nonrepl/part_nonrepl_migration_common_actor.h
> +    bool MigrationRangeScheduled = false;
RangeMigrationScheduled?

2024-05-03 15:45 UTC, qkrorlqr commented on cloud/blockstore/libs/storage/partition_nonrepl/part_nonrepl_migration_common_actor_mirror.cpp
> +    // Check overlapping with a range that will be migrated next.
with the range

2024-05-03 15:45 UTC, qkrorlqr commented on cloud/blockstore/libs/storage/partition_nonrepl/part_nonrepl_migration_common_actor_mirror.cpp
> +        if (checkOverlapsWithMigration(ProcessingBlocks.BuildProcessingRange()))
что-то я не понимаю - вот мы ввели MigrationsInProgress, зачем мы тогда проверяем пересечение с ProcessingBlocks.BuildProcessingRange()? в MigrationsInProgress не будет этого рейнджа? я думал, там все рейнджи есть, которые сейчас в процессе миграци

2024-05-03 15:45 UTC, qkrorlqr commented on cloud/blockstore/libs/storage/volume/volume_actor_stats.cpp
> +        ui64 migratedBlockCount =
выглядит как правка, нерелевантная этому PR

2024-05-03 15:45 UTC, qkrorlqr commented on cloud/blockstore/libs/storage/volume/volume_ut.cpp
> +        DoShouldEnsureMutualExclusionOfIntersectingWritesAndMigrationRequests(
лучше в отдельный тесткейс вынести

2024-05-03 15:45 UTC, qkrorlqr commented on cloud/blockstore/libs/storage/volume/volume_ut.cpp
> +        UNIT_ASSERT_VALUES_EQUAL(60, migrationProgressCounter);
не помню уже, чем
можно привести в соответствие реальности

2024-05-03 15:45 UTC, qkrorlqr commented on cloud/blockstore/libs/storage/partition_nonrepl/part_nonrepl_migration_common_actor_migration.cpp
> +    auto delayBetweenMigrations =
какое-то усложнение
почему бы не оставить так, как было? всегда звать CalculateMigrationTimeout, только передавая в него не последний рейндж, а тот, который хочется мигрировать
если DeferredMigrations усложняют это место, ну ок, можно для простоты DeferredMigrations стартовать вообще без delay - мы же уже учли delay, когда первый раз попробовали запустить миграции, которые у нас сейчас в DeferredMigrations лежат

2024-05-04 13:31 UTC, drbasic commented on cloud/blockstore/libs/storage/partition_nonrepl/part_nonrepl_migration_common_actor_mirror.cpp
> +        if (checkOverlapsWithMigration(ProcessingBlocks.BuildProcessingRange()))
Мы знаем какой блок мы БУДЕМ сейчас мигрировать и не даем начаться записи пользователя в этот блок, иначе если пользователь будет писать в этот блок непрерывно, мы не сможем его мигрировать.

2024-05-06 07:31 UTC, drbasic commented on cloud/blockstore/libs/storage/volume/volume_ut.cpp
> +        UNIT_ASSERT_VALUES_EQUAL(60, migrationProgressCounter);
Оставил так. По факту у нас бывает что физически девайс больше чем  мы используем.

2024-05-06 07:32 UTC, drbasic commented on cloud/blockstore/libs/storage/partition_nonrepl/part_nonrepl_migration_common_actor_migration.cpp
> +    if (DstActorId) {
убрал

2024-05-06 07:32 UTC, drbasic commented on cloud/blockstore/libs/storage/partition_nonrepl/part_nonrepl_migration_common_actor_migration.cpp
> +    for (auto [key, range] : DeferredMigrations) {
clang-format форматирует правильно, видимо не прогнал эту строчку(

2024-05-06 07:34 UTC, drbasic commented on cloud/blockstore/libs/storage/partition_nonrepl/part_nonrepl_migration_common_actor_mirror.cpp
> +        if (checkOverlapsWithMigration(ProcessingBlocks.BuildProcessingRange()))
В общем сделал методы 
`
    std::optional<TBlockRange64> GetNextMigrationRange() const;
    std::optional<TBlockRange64>
    TakeNextMigrationRange(const NActors::TActorContext& ctx);
`
которыми можно легко понять какой диапазон будем мигрировать следующим и взять этот диапазон.

2024-05-06 07:35 UTC, drbasic commented on cloud/blockstore/libs/storage/volume/volume_actor_stats.cpp
> +        ui64 migratedBlockCount =
Убрал, вынесу в другой ПР

2024-05-06 07:35 UTC, drbasic commented on cloud/blockstore/libs/storage/partition_nonrepl/part_nonrepl_migration_common_actor_migration.cpp
> +    auto delayBetweenMigrations =
с методом GetNextMigrationRange() получилось проще

2024-05-06 07:53 UTC, komarevtsev-d approved these changes

2024-05-06 18:52 UTC, qkrorlqr commented on cloud/blockstore/libs/storage/partition_nonrepl/part_nonrepl_migration_common_actor_migration.cpp
>      {
теперь скобка не там

2024-05-06 18:54 UTC, qkrorlqr approved these changes
вроде норм

2024-05-07 02:55 UTC, drbasic commented on cloud/blockstore/libs/storage/partition_nonrepl/part_nonrepl_migration_common_actor_migration.cpp
>      {
в другом ПРе поправлю

2024-05-07 02:55 UTC, merged