[Filestore] add mutilple-clients fio tests to eternal-test-runner
ydb-platform/nbs pull request #1137
Opened 2024-05-06 18:21 UTC by debnatkh

While optimizing filestore for multiple clients' RW load patterns (#539, #324), there was a need for filestore tests that support multiple clients. As a simple solution, we use simple FIO, running on multiple clients and mounting the same NFS.

2024-05-13 17:42 UTC, WilyTiger requested changes

2024-05-13 17:42 UTC, WilyTiger commented on cloud/blockstore/tools/testing/eternal_tests/test_runner/lib/main.py
> +    _VM_PREFIX = "%s-test-vm-%s"
Мы вроде везде в питон скриптах одинарные кавычки используем

2024-05-13 17:42 UTC, WilyTiger commented on cloud/blockstore/tools/testing/eternal_tests/test_runner/lib/test_configs.py
> +        print(cmd)
Дебажный вывод?

2024-05-13 17:42 UTC, WilyTiger commented on cloud/blockstore/tools/testing/eternal_tests/test_runner/lib/main.py
> +        # instances = self.find_instances()
лишнее?

2024-05-13 17:42 UTC, WilyTiger commented on cloud/blockstore/tools/testing/eternal_tests/test_runner/lib/main.py
> +            instances.append(self.create_and_configure_vm(i, i != 0))
А почему так, а не создать отдельно фс, если надо и приатачить к вмкам. И убрать параметр skip_fs_create

2024-05-13 18:00 UTC, qkrorlqr commented on cloud/blockstore/tools/testing/eternal_tests/test_runner/lib/main.py
> +    _VM_PREFIX = "%s-test-vm-%s"
не, стараемся, наоборот, двойные

главное чтоб в одном файле не было то так, то сяк

2024-05-13 18:26 UTC, debnatkh commented on cloud/blockstore/tools/testing/eternal_tests/test_runner/lib/main.py
> +            instances.append(self.create_and_configure_vm(i, i != 0))
Сейчас `create_and_configure_vm` и создаёт, и монтирует диск/фс. Вывод о том, что именно создавать, она делает по конфигу. Так что надо в любом случае прокидывать параметр о том, что fs создавать не надо в `create_and_configure_vm`.

Разумная альтернатива такому коду – это иметь функцию, которой передаются параметры ВМ, а также конфиги диска и/или фс, после чего она создаёт их, а не делает вывод из конфига всего теста. Но это надо будет поредактировать чувствуительную часть `main.py`

2024-05-13 18:54 UTC, WilyTiger approved these changes

2024-05-14 18:42 UTC, WilyTiger approved these changes

2024-06-06 11:05 UTC, ya-ksgamora approved these changes

2024-06-06 12:20 UTC, merged