[Disk Manager] add tests with larger vhd images; add CacheMissedReadCounts check
ydb-platform/nbs pull request #1195
Opened 2024-05-14 14:08 UTC by BarkovBG

https://github.com/ydb-platform/nbs/issues/498

2024-05-14 14:28 UTC, SvartMetal commented on cloud/disk_manager/test/images/recipe/__main__.py
> +    ubuntu1604_image_file_path = yatest_common.build_path("cloud/disk_manager/test/images/resources/vhd_images/ubuntu1604-ci-stable")
vhd_ubuntu1604_image_file_path

2024-05-14 14:30 UTC, SvartMetal commented on cloud/disk_manager/test/images/recipe/__main__.py
> +        ubuntu1604_image_file_server = ImageFileServerLauncher(ubuntu1604_image_file_path)
vhd_ubuntu1604_image_file_server

2024-05-14 14:34 UTC, SvartMetal submitted a review, later dismissed

2024-05-14 16:21 UTC, jkuradobery requested changes

2024-05-14 16:21 UTC, jkuradobery commented on cloud/disk_manager/internal/pkg/dataplane/url/vhd/tests/vhd_test.go
> +func TestQCOW2MapImageUbuntu1604(t *testing.T) {
TestVHDMapImageUbuntu1604?

2024-05-15 11:19 UTC, leftmain approved these changes

2024-05-15 11:20 UTC, merged