Make rdma code better #1
ydb-platform/nbs pull request #1228
Opened 2024-05-17 10:25 UTC by drbasic

2024-05-17 12:00 UTC, komarevtsev-d approved these changes

2024-05-19 08:31 UTC, budevg requested changes

2024-05-19 08:31 UTC, budevg commented on cloud/blockstore/libs/storage/partition_nonrepl/part_nonrepl_rdma_actor_readblocks_local.cpp
> +
remove empty line here .. the pattern for checking error is usually
```
auto err = someStuff()
if (err) {
}
```

2024-05-19 11:55 UTC, qkrorlqr commented on cloud/blockstore/libs/storage/partition_nonrepl/part_nonrepl_rdma_actor_readblocks.cpp
> -            HandleResult(*dr, std::move(buffer));
почему?

2024-05-19 11:56 UTC, qkrorlqr submitted a review, later dismissed
А где лучше-то стало? Я это откачу, если мне лично не объяснят, что такие PR улучшают. Уже не первый раз вижу перекладывание кода из строки в строку с неясной пользой. Перестаньте, пожалуйста, этим заниматься.

Любые правки кода - это вред в виде риска внесения новых багов и порчи блейма. Этот вред должен компенсироваться какой-то новой пользой от кода. Если это рефакторинг, то он должен упрощать дальнейшие модификации кода или улучшать читаемость кода или хотя бы его количество сокращать (что косвенно может иногда улучшить читаемость). Тут я не вижу ничего из этого.

2024-05-20 05:07 UTC, drbasic commented
> А где лучше-то стало? Я это откачу, если мне лично не объяснят, что такие PR улучшают. Уже не первый раз вижу перекладывание кода из строки в строку с неясной пользой. Перестаньте, пожалуйста, этим заниматься.
> 
> Любые правки кода - это вред в виде риска внесения новых багов и порчи блейма. Этот вред должен компенсироваться какой-то новой пользой от кода. Если это рефакторинг, то он должен упрощать дальнейшие модификации кода или улучшать читаемость кода или хотя бы его количество сокращать (что косвенно может иногда улучшить читаемость). Тут я не вижу ничего из этого.

1. два разных класса имеют одинаковое имя TRdmaRequestContext и имеют похожий код. Меня это путает
2. статический метод зовется через указатель - меня это путает
3. для чего-то делается using TResponse хотя без него явно видно что же в ответе - какой тип. Мне сложнее читать код
4. все что не меняется должно объявляться константным - мне это упрощает понимание 
5. уменьшил вложенность кода за счет проверки и раннего выхода - тут да, спорное, возможно не стоило трогать.

2024-05-20 09:11 UTC, komarevtsev-d approved these changes

2024-05-20 09:21 UTC, budevg approved these changes

2024-05-20 11:06 UTC, qkrorlqr commented
> 1. два разных класса имеют одинаковое имя TRdmaRequestContext и имеют похожий код. Меня это путает

они в anon ns в разных файлах - из остального файла и из имени файла понятно, что это за классы

> 2. статический метод зовется через указатель - меня это путает

мелочь

> 3. для чего-то делается using TResponse хотя без него явно видно что же в ответе - какой тип. Мне сложнее читать код
не помню

возможно, для краткости 

> 4. все что не меняется должно объявляться константным - мне это упрощает понимание 
> 5. уменьшил вложенность кода за счет проверки и раннего выхода - тут да, спорное, возможно не стоило трогать. Откатил.
> 6. std::move применяется к классу который нельзя мувать

когда новый код пишется - да, наверное, это все правильно

> 7. неявный захват в лямбду this. На мой взгляд лучше явно написать this  чтобы было видно с лямбдой нужно быть аккуратным и не продлевать время ее жизни дольше чем this

у нас такие лямбды в половине хендлеров евентов и понятно, что их потом никуда не передают - они вызываются только в том же самом скоупе

короче, частично это вкусовщина, частично - мелочи
если очень хочется это залить и раз уже сделаны эти правки - ну ок, коммить
но по мне так пустая трата времени

вот, с ходу еще несколько похожих вещей:
https://github.com/ydb-platform/nbs/blob/ca525d68b14d597b9d849c300c7fd64885cc027a/cloud/blockstore/libs/client_rdma/rdma_client.cpp#L110
https://github.com/ydb-platform/nbs/blob/ca525d68b14d597b9d849c300c7fd64885cc027a/cloud/blockstore/libs/service_local/storage_rdma.cpp#L90
https://github.com/ydb-platform/nbs/blob/ca525d68b14d597b9d849c300c7fd64885cc027a/cloud/blockstore/libs/storage/partition/part_actor_writeblocks.cpp#L205

можно бесконечно рефакторить

2024-05-20 11:19 UTC, merged

2024-05-20 11:30 UTC, drbasic commented
Я за то чтобы у нас в коде было не "можно понять и разобраться", а все было максимально просто и явно. 
В частности это складывается из таких мелочей, что два разных класса имеют одно имя, обращение к статическому методу через объект.
Я же не просто так в это файл полез, а начал писать новый код и мне пришлось потратить время чтобы прочитать этот код, уверен что в дальнейшем этот файле будет разбираться проще.

В части захвата в этой лямбде по = тут с тобой соглашусь, она никуда не утекает, не надо было трогать.

Про обращение к сериализатору по стрелочке, я вообще хочу все методы у него сделать статическими, но это не сейчас.