issue-1128: batch loading of compaction map by groups
ydb-platform/nbs pull request #1233
Opened 2024-05-17 15:28 UTC by WilyTiger

#1128

2024-05-17 15:58 UTC, qkrorlqr requested changes

2024-05-17 15:58 UTC, qkrorlqr commented on cloud/filestore/libs/storage/tablet/model/compaction_map.cpp
> +        bool exist = false;
exists

2024-05-17 15:58 UTC, qkrorlqr commented on cloud/filestore/libs/storage/tablet/model/compaction_map.cpp
> +            if (exist) {
это условие не нужно - если группа не существовала, у нее в метриках будут нули и можно эти нули спокойно вычесть
в итоге получается, что и exists-флаг не нужен

2024-05-17 15:58 UTC, qkrorlqr commented on cloud/filestore/libs/storage/tablet/model/compaction_map.cpp
> +            endIndex++;
++endIndex

2024-05-17 15:58 UTC, qkrorlqr commented on cloud/filestore/libs/storage/tablet/model/compaction_map_ut.cpp
> -
почему удаляется строчка?

2024-05-17 15:58 UTC, qkrorlqr commented on cloud/filestore/libs/storage/tablet/model/compaction_map_ut.cpp
> +        const auto group = TCompactionMap::GroupSize;
groupSize тогда уж

2024-05-17 15:58 UTC, qkrorlqr commented on cloud/filestore/libs/storage/tablet/ut_counters/cloud-filestore-libs-storage-tablet-ut_counters
> +/root/.ya/build/symres/24b99bd4f5c48fcf9c38a5a2ab2f561f/cloud-filestore-libs-storage-tablet-ut_counters
2 лишних бинаря закоммитила

2024-05-17 22:45 UTC, qkrorlqr approved these changes

2024-05-21 14:44 UTC, yegorskii approved these changes

2024-05-21 16:27 UTC, qkrorlqr approved these changes

2024-05-22 10:08 UTC, merged