issue-1236: update DR config w/o triggering STORAGE_VERIFY
ydb-platform/nbs pull request #1237
Opened 2024-05-18 00:02 UTC by sharpeye

Now UpdateConfig uses UpdateKnownDevices instead of RegisterAgent and therefore STORAGE_VERIFY will not be called.

2024-05-20 05:44 UTC, komarevtsev-d commented on cloud/blockstore/libs/storage/disk_registry/disk_registry_state.cpp
> +            UpdateKnownDevices(db, *agent);
Это изменение на практике чем-то грозит? После обновления конфига новый агент автоматически подхватится и начнёт работать?

2024-05-20 13:15 UTC, sharpeye commented on cloud/blockstore/libs/storage/disk_registry/disk_registry_state.cpp
> +            UpdateKnownDevices(db, *agent);
Новый агент начнет рабоать после ADD_HOST - когда его девайсы добавятся в конфиг.

В этом изменении убран STORAGE_VERIFY: раньше звали RegisterAgent, который мог вернуть ошибку (например. если NodeId = 0).

2024-05-20 16:22 UTC, komarevtsev-d approved these changes

2024-05-21 11:04 UTC, qkrorlqr requested changes

2024-05-21 11:04 UTC, qkrorlqr commented on cloud/blockstore/libs/storage/disk_registry/disk_registry_state.cpp
> +void TDiskRegistryState::UpdateKnownDevices(
Этот код не выглядит самостоятельной функцией, т.к. полагается на то, что перед его запуском вызовут ProcessConfig, чтобы обновить KnownAgents. В месте вызова совершенно неочевидно, что если поменять порядок и сначала вызвать UpdateKnownDevices для updatedAgents, а ProcessConfig позвать после, то что-то пойдет не так. Тут вносится вносится очередное размытие границ ответственности между функциями. У нас и так в TDiskRegistryState куча функций, которые выдвигают неочевидные требования к вызывающему их коду - давайте не будем такое множить. Например, связи между остальными вызовами в UpdateConfig и вызовом UpdateKnownDevices станут очевидны, если передать const TKnownAgent& параметром в UpdateKnownAgents. Это уменьшит риск вызова UpdateKnownAgents из неправильного места. Вообще, основная проблема в TDiskRegistryState - это даже не то, что он разросся до огромных размеров, а то, что по мере роста он разрастался не отдельными loosely coupled-модулями, а вот такими функциями, которые сами копошатся в большом числе кишок TDiskRegistryState, делая разнообразные предположения о том, какие из этих кишок кто-то уже актуализировал снаружи (KnownAgents), а какие надо обновить внутри функции (AgentList). Тут вообще плохо - AgentList и передается снаружи (фактически - т.к. agent - это результат лукапа в AgentList), и модифицируется внутри функции.

2024-06-05 06:39 UTC, komarevtsev-d submitted a review, later dismissed

2024-06-05 10:02 UTC, komarevtsev-d approved these changes

2024-06-07 04:49 UTC, komarevtsev-d approved these changes

2024-06-10 16:42 UTC, qkrorlqr approved these changes

2024-06-11 17:05 UTC, merged