NBS-4665 [NBS] Validate checkpoint requests and reply without saving/exection when needed
ydb-platform/nbs pull request #1239
Opened 2024-05-20 06:52 UTC by gy2411

This pr is to replace #239.

When we start to process a checkpoint request, we should call ValidateCheckpointRequest method added in #1134. Depending on the result of validation, we either reply to the request immediately or save the request to the database and execute it as usual.

2024-05-20 07:14 UTC, gy2411 commented on cloud/blockstore/libs/storage/volume/volume_ut_checkpoint.cpp
> +        volume.DeleteCheckpoint("c1");
Опечатка

2024-05-20 07:14 UTC, gy2411 commented on cloud/blockstore/libs/storage/volume/volume_ut_checkpoint.cpp
> +        for (auto checkpointId : TVector<TString>{"c6", "c7"}) {
Опечатка

2024-05-20 07:53 UTC, gy2411 commented on cloud/blockstore/libs/storage/volume/volume_actor_checkpoint.cpp
> +    while (checkpointStore.HasRequestToExecute(&readyToExecuteRequestId)) {
Не уверен насчёт этого момента. Дело в том, что сложность это while по времени -- квадрат от числа запросов, так как метод HasRequestToExecute каждый раз заново [проходится](https://github.com/ydb-platform/nbs/blob/main/cloud/blockstore/libs/storage/volume/model/checkpoint.cpp#L222) по мапе CheckpointRequests. Таким образом возникает риск, что volume actor проведёт в этом while очень много времени. Можем ли мы считать, что у нас никогда не будет настолько много запросов на чекпоинты, или нужно как-то оптимизировать это место?

2024-05-22 13:58 UTC, drbasic requested changes

2024-05-22 13:58 UTC, drbasic commented on cloud/blockstore/libs/storage/volume/volume_actor_checkpoint.cpp
> +    while (checkpointStore.HasRequestToExecute(&readyToExecuteRequestId)) {
Не думаю что тут мы должны застрять на долго, все-таки запросов в памяти не должно копиться много.

2024-05-22 13:58 UTC, drbasic commented on cloud/blockstore/libs/storage/volume/volume_actor_checkpoint.cpp
> +        CheckpointRequests.FindPtr(requestId);
чем гарантируется что requestInfo != nullptr?

2024-05-22 13:58 UTC, drbasic commented on cloud/blockstore/libs/storage/volume/model/checkpoint.cpp
> +        CheckpointRequests.FindPtr(requestId)->State ==
не проверили результат CheckpointRequests.FindPtr()

2024-05-24 07:17 UTC, gy2411 commented on cloud/blockstore/libs/storage/volume/volume_actor_checkpoint.cpp
> +            CheckpointRequests.erase(request.RequestId);
Вот тут ещё надо удалять элемент из CheckpointRequests -- иначе эта мапа будет неограниченно расти в памяти.

2024-05-24 20:24 UTC, qkrorlqr commented on cloud/blockstore/libs/storage/volume/volume_actor_checkpoint.cpp
> +    while (checkpointStore.HasRequestToExecute(&readyToExecuteRequestId)) {
> Можем ли мы считать, что у нас никогда не будет настолько много запросов на чекпоинты, или нужно как-то оптимизировать это место?

обычно в таких ситуациях либо оптимизируешь, либо вставляешь жесткий лимит на размер и отдаешь ошибки при попытке превысить размер

2024-05-24 20:35 UTC, qkrorlqr commented on cloud/blockstore/libs/storage/volume/model/checkpoint.cpp
> +    auto& checkpointRequest = GetRequest(requestId);
какие-то опасные методы, которые возвращают reference и делают VERIFY, если не могут вернуть reference
я вижу, что в других методах этого класса активно используется GetRequest - ты не хочешь переписать его на возврат указателя все-таки?

2024-05-27 15:01 UTC, qkrorlqr commented on cloud/blockstore/libs/storage/volume/volume_actor_checkpoint.cpp
> +    for (auto requestId : readyToProcessRequestIds) {
перед : пробел не ставим

2024-05-27 15:10 UTC, gy2411 commented on cloud/blockstore/libs/storage/volume/volume_actor_checkpoint.cpp
> +    while (checkpointStore.HasRequestToExecute(&readyToExecuteRequestId)) {
Оптимизировал -- теперь за одно обращение к checkpoint store забираются сразу все ready to process запросы. Таким образом, volume actor не будет вертеться в петле O(кол-во звпросов в памяти)^2 времени.

2024-05-28 09:24 UTC, gy2411 commented on cloud/blockstore/libs/storage/volume/model/checkpoint.cpp
> +    auto& checkpointRequest = GetRequest(requestId);
Решили переписать эти методы на возврат указателя в отлельном pr.

2024-05-29 08:04 UTC, drbasic approved these changes

2024-05-29 08:15 UTC, merged