use static libnl #1166
ydb-platform/nbs pull request #1313
Opened 2024-05-31 11:48 UTC by tpashkin

2024-06-04 13:21 UTC, sanek325 approved these changes

2024-06-04 13:25 UTC, EvgeniyKozev submitted a review, later dismissed

2024-06-04 13:30 UTC, sanek325 approved these changes

2024-06-04 13:32 UTC, EvgeniyKozev approved these changes

2024-06-05 16:13 UTC, qkrorlqr requested changes
Тогда уж делать аналогично всем остальным либам - без LDFLAGS, просто через PEERDIR

2024-06-06 10:29 UTC, tpashkin commented
> Тогда уж делать аналогично всем остальным либам - без LDFLAGS, без NETLINK-флага, просто через PEERDIR

Нам нужно собрать контейнер без лишних зависимостей. Я позже затащу либу в contrib, но из-за lgpl линковка всё равно останется и такая, и такая (как сделано для aio или iconv)

2024-06-06 10:34 UTC, qkrorlqr commented
> Я позже затащу либу в contrib

главное чтоб не сильно позже
скажем, не позднее конца следующей недели

2024-06-06 10:42 UTC, qkrorlqr approved these changes

2024-06-06 10:42 UTC, merged