Get rid macros for counters
ydb-platform/nbs pull request #1336
Opened 2024-06-04 08:57 UTC by drbasic

Убираю макросы в счетчиках. При таком подходе объявление счетчика чуть сложнее, его нужно прописать в двух местах, но код при этом становится читаемым.
Есть защита от дурака, если не прописать новый счетчик в общем списке всех счетчиков, сломается static_assert.

2024-06-04 09:05 UTC, drbasic commented
Начал с замены первой пачки макросов. Если все ок, заменю остальные.

2024-06-05 11:22 UTC, drbasic commented on cloud/blockstore/libs/storage/core/disk_counters.h
> +consteval auto MakeMeta()
Довольно простым хаком получилось взять имя поля и не прописывать его руками.
Возможно при черипике в 23-3  потребуется чуть поправить выкусывание имени, но скорее всего все будет ок.

2024-06-07 05:02 UTC, komarevtsev-d submitted a review, later dismissed

2024-06-11 18:25 UTC, qkrorlqr requested changes
не знаю, как бы так проверить, что тут нигде не перепутано ничего в районе параметров каунтеров после рефакторинга (я про PublishingPolicy и CounterOption)

2024-06-11 18:25 UTC, qkrorlqr commented on cloud/blockstore/libs/storage/core/disk_counters.h
> +    TMemberMeta<decltype(NDetail::ExtractMemberPtr<T>())> result;
а почему просто TMemberMeta<T> не хватает?

2024-06-11 18:25 UTC, qkrorlqr commented on cloud/blockstore/libs/storage/core/disk_counters.h
> +    std::string_view left = "::";
а тут TStringBuf, кстати, получится использовать? или из-за consteval не получится?

2024-06-11 18:25 UTC, qkrorlqr commented on cloud/blockstore/libs/storage/core/disk_counters.h
> +    static constexpr TMeta AllCounters[] = {
что-то сложно
а почему просто в рантайме в конструкторе TSimpleDiskCounters не собрать этот массив? ему обязательно быть static-ом?

2024-06-11 18:25 UTC, qkrorlqr commented on cloud/blockstore/libs/storage/core/disk_counters.h
> +    static constexpr TMeta AllCounters[] = {
тут вопрос, аналогичный вопросу про TSimpleDiskCounters::AllCounters

2024-06-13 04:28 UTC, drbasic commented on cloud/blockstore/libs/storage/core/disk_counters.h
> +    TMemberMeta<decltype(NDetail::ExtractMemberPtr<T>())> result;
T тут не является именем типа. Это указатель на член класса.

2024-06-13 04:28 UTC, drbasic commented on cloud/blockstore/libs/storage/core/disk_counters.h
> +    std::string_view left = "::";
использовал  TStringBuf  для хранения, но при вычислениях нужны constexpr методы, которых у TStringBuf нет.

Вообще (это тема для отдельного разговора) я не понимаю зачем мы используем свой тип, когда есть стандартный std::string_view. Я бы сделал обратное упражнение, заменил все TStringBuf на std::string_view.

2024-06-13 04:28 UTC, drbasic commented on cloud/blockstore/libs/storage/core/disk_counters.h
> +    static constexpr TMeta AllCounters[] = {
На мой взгляд не сложно и точно очень эффективно. В compile-time мы создаем мета-информацию про поля, включая проверку на то что не пропустили регистрацию.   
Конечно, можно создавать эту штуку на каждый объект, но я не понимаю зачем. Проще от этого не станет.

2024-06-15 22:18 UTC, qkrorlqr commented on cloud/blockstore/libs/storage/core/disk_counters.h
> +    std::string_view left = "::";
> зачем мы используем свой тип, когда есть стандартный std::string_view

1. по историческим причинам
2. у него есть набор удобных методов, которых нет у string_view

> Я бы сделал обратное упражнение, заменил все TStringBuf на std::string_view

не надо, это будет огромный бесполезный рефакторинг

2024-06-15 22:21 UTC, qkrorlqr commented on cloud/blockstore/libs/storage/core/disk_counters.h
> +    static constexpr TMeta AllCounters[] = {
ok

2024-06-15 22:21 UTC, qkrorlqr approved these changes

2024-06-17 07:36 UTC, komarevtsev-d approved these changes

2024-06-17 08:39 UTC, qkrorlqr approved these changes

2024-06-17 08:41 UTC, merged