issue-1320: Add disk info handle
ydb-platform/nbs pull request #1383
Opened 2024-06-10 13:30 UTC by antonmyagkov

2024-06-11 09:51 UTC, qkrorlqr requested changes
еще нужен тест в cloud/blockstore/tests/client

2024-06-11 09:51 UTC, qkrorlqr commented on cloud/blockstore/libs/daemon/common/bootstrap.cpp
> +            EBlockStoreRequest::DescribeAgentDevices
сюда не надо - это апи для compute-ноды (демон компьюта, который на конкретном хосте поднимает-гасит ВМ-ки, подключает-отключает диски)

2024-06-11 09:51 UTC, qkrorlqr commented on cloud/blockstore/libs/service/request_helpers.h
> +        case EBlockStoreRequest::DescribeAgentDevices:
это должно быть в другой секции (return true) - это как раз-таки control plane request

2024-06-11 09:51 UTC, qkrorlqr commented on cloud/blockstore/libs/storage/disk_registry/disk_registry_state.cpp
> +                deviceInfo.set_devicename(device.GetDeviceName());
в наших .pb.h-файлах есть геттеры и сеттеры в нашем стайлгайде, надо использовать их (SetDeviceName, etc)

2024-06-11 09:51 UTC, qkrorlqr commented on cloud/blockstore/libs/storage/disk_registry/disk_registry_state.cpp
> +            if (IsDirtyDevice(device.GetDeviceUUID()) ||
это все надо учесть
вообще, стоит, как я тебе говорил, сделать полную раскладку по месту, как в метриках - отдельно Free, отдельно Allocated, отдельно Dirty, etc.

2024-06-11 09:51 UTC, qkrorlqr commented on cloud/blockstore/libs/storage/disk_registry/disk_registry_state.cpp
> +TVector<NProto::TAgentInfo> TDiskRegistryState::GetAgentsInfo() const
давай лучше назовем как-нибудь BuildAgentsInfo(), чтоб по названию было понятно, что это не легкий геттер, а что-то, что будет производить потенциально дорогие вычисления

2024-06-11 09:51 UTC, qkrorlqr commented on cloud/blockstore/libs/storage/disk_registry/disk_registry_state.cpp
> +TVector<NProto::TAgentInfo> TDiskRegistryState::GetAgentsInfo() const
на этот метод нужен юниттест

2024-06-11 11:31 UTC, antonmyagkov commented on cloud/blockstore/libs/daemon/common/bootstrap.cpp
> +            EBlockStoreRequest::DescribeAgentDevices
Done

2024-06-11 18:30 UTC, qkrorlqr submitted a review, later dismissed

2024-06-12 11:36 UTC, antonmyagkov commented
> еще нужен тест в cloud/blockstore/tests/client

В следующем пулл реквесте

2024-06-12 11:45 UTC, qkrorlqr submitted a review, later dismissed

2024-06-17 09:59 UTC, qkrorlqr approved these changes

2024-06-17 10:00 UTC, qkrorlqr approved these changes

2024-06-17 10:13 UTC, drbasic requested changes

2024-06-17 10:13 UTC, drbasic commented on cloud/blockstore/libs/storage/disk_registry/disk_registry_actor_query_agents_info.cpp
> +    for (auto& agentInfo: State->QueryAgentsInfo()) {
тут возвращается объект, который присваивается в ссылку. не константная ссылка не продлевает время жизни объекта. Т.е. тут получается обращение к дохлому объекту.
нужно убрать &, оставить сохранение по значению.

2024-06-17 12:39 UTC, drbasic commented on cloud/blockstore/libs/storage/disk_registry/disk_registry_actor_query_agents_info.cpp
> +    for (auto& agentInfo: State->QueryAgentsInfo()) {
А зачем этот if вообще нужен?
Тут проверяется что ветор не пустой? ну и какая разница пустой он лил нет, безусловно делать  *response->Record.AddAgents() = State->QueryAgentsInfo();

2024-06-17 13:00 UTC, drbasic commented on cloud/blockstore/libs/storage/disk_registry/disk_registry_actor_query_agents_info.cpp
> +    for (auto& agentInfo: State->QueryAgentsInfo()) {
я прочитал вместо  for if. Все тут нормально.

2024-06-17 13:00 UTC, drbasic approved these changes

2024-06-17 13:22 UTC, merged