retry scrubbing for 5 minutes before reporting checksum mismatch
ydb-platform/nbs pull request #1393
Opened 2024-06-11 19:20 UTC by WilyTiger

2024-06-12 10:21 UTC, qkrorlqr requested changes

2024-06-12 10:21 UTC, qkrorlqr commented on cloud/blockstore/libs/storage/partition_nonrepl/part_mirror_actor.cpp
> +                "[%s] Checksum mismatch for range %s, reshedule scrubbing",
reschedule

2024-06-12 10:21 UTC, qkrorlqr commented on cloud/blockstore/libs/storage/partition_nonrepl/part_mirror_actor.h
> +constexpr TDuration ChecksumMismatchTimeout = TDuration::Minutes(5);
надо в конфиг вынести

2024-06-12 10:21 UTC, qkrorlqr commented on cloud/blockstore/libs/storage/partition_nonrepl/part_mirror_actor_mirror.cpp
> +    if (RangeId2BlockRange(ScrubbingRangeId, State.GetBlockSize())
а тут почему поменялось?

2024-06-12 10:21 UTC, qkrorlqr commented on cloud/blockstore/libs/storage/partition_nonrepl/part_mirror_ut.cpp
> +        auto& counter = env.StorageStatsServiceState->Counters;
counters

2024-06-12 10:21 UTC, qkrorlqr commented on cloud/blockstore/libs/storage/partition_nonrepl/part_mirror_ut.cpp
> +        auto& counter = env.StorageStatsServiceState->Counters;
counters

2024-06-12 10:21 UTC, qkrorlqr commented on cloud/blockstore/libs/storage/partition_nonrepl/part_mirror_ut.cpp
> +                fullCyclesCount++;
++fullCycleCount;

2024-06-12 10:21 UTC, qkrorlqr commented on cloud/blockstore/libs/storage/partition_nonrepl/part_mirror_ut.cpp
> +        while (fullCyclesCount < 2) {
если в коде баг, тест зависнет намертво
нужен какой-то код, который будет прерывать цикл, если он не завершился за какое-то вменяемое время

2024-06-12 10:21 UTC, qkrorlqr commented on cloud/blockstore/libs/storage/partition_nonrepl/part_mirror_ut.cpp
> +        while (fullCyclesCount < 3) {
тут все аналогичные замечания

2024-06-12 10:21 UTC, qkrorlqr commented on cloud/blockstore/libs/storage/partition_nonrepl/part_mirror_ut.cpp
> +                writeDeviceResponses++;
++writeDeviceResponses;

2024-06-12 10:21 UTC, qkrorlqr commented on cloud/blockstore/libs/storage/partition_nonrepl/part_mirror_ut.cpp
> +                    auto response = std::make_unique<TEvDiskAgent::TEvWriteDeviceBlocksResponse>(
```
# echo -n '                    auto response = std::make_unique<TEvDiskAgent::TEvWriteDeviceBlocksResponse>('|wc -c
97
```

2024-06-12 10:21 UTC, qkrorlqr commented on cloud/blockstore/libs/storage/partition_nonrepl/part_mirror_ut.cpp
> +        runtime.SetScheduledEventFilter([&] (auto& runtime, auto& event, auto&& delay, auto&& deadline) {
```
# echo -n '        runtime.SetScheduledEventFilter([&] (auto& runtime, auto& event, auto&& delay, auto&& deadline) {'|wc -c
105
```

2024-06-12 10:25 UTC, WilyTiger commented on cloud/blockstore/libs/storage/partition_nonrepl/part_mirror_actor_mirror.cpp
> +    if (RangeId2BlockRange(ScrubbingRangeId, State.GetBlockSize())
Потому что в прошлом пр меня Кирилл попросил убрать ScrubbingRange вообще, а в этом месте я забыла убрать. ScrubbingRange был всегда нулевой и в одном из тестов эта ветка проверялась коряво, потому что инфлайт запрос был тоже в нулевой диапазон. Я поправила тесты, теперь там запрос на запись не с нулевого блока, тест стал падать по делу и дочистила этот ScrubbingRange

2024-06-12 15:26 UTC, qkrorlqr submitted a review, later dismissed

2024-06-13 05:25 UTC, drbasic requested changes

2024-06-13 05:25 UTC, drbasic commented on cloud/blockstore/libs/storage/partition_nonrepl/part_mirror_actor.cpp
> +        ScrubbingRangeStarted = ctx.Now();
Если написать ScrubbingRangeId = 0;
То будет понятно, что везде где планируем считывание чексумм нового диапазона, выставляем ScrubbingRangeStarted = ctx.Now();
А еще лучше сделать метод 
```
void StartScrubbingRange(ui64 scrubbingRangeId, const TActorContext& ctx) {
  if (ScrubbingRangeId != scrubbingRangeId) {
    ScrubbingRangeId = scrubbingRangeId;
    ScrubbingRangeStarted = ctx.Now();
  }
  ScheduleScrubbingNextRange(ctx);
}
```
И вызывать везде StartScrubbingRange();
Кстати в https://github.com/ydb-platform/nbs/blob/main/cloud/blockstore/libs/storage/partition_nonrepl/part_mirror_actor.cpp#L261
не происходит взывова ScheduleScrubbingNextRange(ctx); это ошибка?

2024-06-13 05:25 UTC, drbasic commented on cloud/blockstore/libs/storage/partition_nonrepl/part_mirror_actor.cpp
> +                DescribeRange(
я бы сделал константный метод 
```
TBlockRange64 GetScrubbingRange() const {
   return RangeId2BlockRange(ScrubbingRangeId, State.GetBlockSize());
}

```

2024-06-13 15:46 UTC, drbasic approved these changes

2024-06-13 19:05 UTC, qkrorlqr submitted a review, later dismissed

2024-06-14 10:21 UTC, drbasic approved these changes

2024-06-14 10:25 UTC, sharpeye approved these changes

2024-06-14 10:26 UTC, merged