configure ttl for stat and archive stats ydb tables
ydb-platform/nbs pull request #1400
Opened 2024-06-12 17:02 UTC by yegorskii

2024-06-12 17:55 UTC, qkrorlqr requested changes

2024-06-12 17:55 UTC, qkrorlqr commented on cloud/blockstore/libs/ydbstats/config.cpp
> +    xxx(StatsTableTtl,                    TDuration,        Seconds(0)        )\
Seconds(0) необязательно писать, можно просто {}

2024-06-12 17:55 UTC, qkrorlqr commented on cloud/blockstore/libs/ydbstats/ydbscheme.cpp
> +#include "config.h"
сначала идет парный "h"-файл

2024-06-12 17:55 UTC, qkrorlqr commented on cloud/blockstore/libs/ydbstats/ydbscheme.cpp
> +            ttl});
непонятно, зачем задаются единицы измерения, если передается не int, а TDuration

2024-06-12 17:55 UTC, qkrorlqr commented on cloud/blockstore/libs/ydbstats/ydbscheme.h
> +    TStatsTableScheme(
а зачем столько конструкторов разных? почему одного какого-нибудь недостаточно?

2024-06-12 17:55 UTC, qkrorlqr commented on cloud/blockstore/libs/ydbstats/ydbstats.cpp
> +        THashMap<TString, EPrimitiveType> columns,
не хватает отступа

2024-06-12 17:55 UTC, qkrorlqr commented on cloud/blockstore/libs/ydbstats/ydbstorage.h
> +            TMaybe<NYdb::NTable::TTtlSettings> ttlSettings )
зачем 2 конструктора? они по смыслу ничем не отличаются

2024-06-14 11:35 UTC, yegorskii commented on cloud/blockstore/libs/ydbstats/ydbscheme.cpp
> +            ttl});
Ну это такой интерфейс ydb. Здесь задается поле по которому определяется ttl записи. Поскольку его тип не DateTime, то требуется указать единицы измерения времени в поле. Почему мы не использовали DateTime? Потому что на момент создания ydb stats, поддержка типа времени то ли не работала то ли еще что

2024-06-14 14:00 UTC, qkrorlqr commented on cloud/blockstore/libs/ydbstats/ydbscheme.cpp
> +            ttl});
А тогда уж передать инт, а не дюрейшн, нельзя?

2024-06-14 14:04 UTC, yegorskii commented on cloud/blockstore/libs/ydbstats/ydbscheme.cpp
> +            ttl});
Нет, там только duration

2024-06-14 14:09 UTC, qkrorlqr approved these changes

2024-06-14 14:41 UTC, EvgeniyKozev approved these changes

2024-06-14 14:56 UTC, merged