NBS-1458 Add check range to read used blocks
ydb-platform/nbs pull request #1475
Opened 2024-06-21 11:29 UTC by sdimanx91

2024-06-21 12:31 UTC, drbasic commented on cloud/blockstore/libs/storage/volume/volume_actor_forward_trackused.cpp
> +    if (usedBlocks->Count() <= endIndex) {
usedBlocks используется без проверки на  nullptr

2024-06-21 12:38 UTC, drbasic commented on cloud/blockstore/libs/storage/volume/volume_actor_forward_trackused.cpp
> +            if (IsOnlyOverlayDisk(usedBlocks, msg->Record.GetStartIndex(), msg->Record.GetBlocksCount())) {
clang-format

2024-06-21 12:39 UTC, drbasic commented on cloud/blockstore/libs/storage/volume/volume_actor_forward_trackused.cpp
> +    ui64 startIndex,
Сюда лучше передать параметр  TRangeBlocks64

2024-06-21 14:42 UTC, drbasic submitted a review, later dismissed

2024-06-24 08:58 UTC, drbasic commented on cloud/blockstore/libs/storage/volume/volume_actor_forward_trackused.cpp
> +    return usedBlocks->Count(range.Start, range.End) == range.Size();
range.End + 1

2024-06-24 08:58 UTC, drbasic commented on cloud/blockstore/libs/storage/volume/volume_actor_forward_trackused.cpp
> +namespace {
анонимный неймспейс удобее помещать внутри namespace NCloud::NBlockStore::NStorage {

2024-06-24 12:27 UTC, qkrorlqr commented on cloud/blockstore/libs/storage/volume/volume_actor_forward_trackused.cpp
>  ////////////////////////////////////////////////////////////////////////////////
отбивка у нас всегда идет перед названием класса или функции, не перед namespace

2024-06-24 12:27 UTC, qkrorlqr commented on cloud/blockstore/libs/storage/volume/volume_actor_forward_trackused.cpp
> +#include <cloud/blockstore/libs/common/block_range.h>
порядок инклюдов не по алфавиту

2024-06-24 12:28 UTC, qkrorlqr requested changes
нужен ut, без ut заливать не надо

2024-07-16 17:43 UTC, qkrorlqr requested changes

2024-07-16 17:43 UTC, qkrorlqr commented on cloud/blockstore/libs/storage/volume/volume_actor_forward_trackused.cpp
> +
отбивка ///... перед ф-цией/классом

2024-07-16 17:43 UTC, qkrorlqr commented on cloud/blockstore/libs/storage/volume/volume_ut.cpp
> +        runtime->SetObserverFunc(
SetEventFilter

1. Observer-а неудобно мержить в stable-23-3
2. в подавляющем большинстве случаев функциональность Observer-ов не нужна - достаточно бинарного EventFilter

2024-07-16 17:43 UTC, qkrorlqr commented on cloud/blockstore/libs/storage/volume/volume_ut.cpp
> +        UNIT_ASSERT_EQUAL(countOfBlockReadReq, 2);
UNIT_ASSERT_VALUES_EQUAL(expected, actual)

2024-07-16 17:43 UTC, qkrorlqr commented on cloud/blockstore/libs/storage/volume/volume_ut.cpp
> +        runtime->DispatchEvents({}, TDuration::Seconds(1));
зачем?

2024-07-16 17:43 UTC, qkrorlqr commented on cloud/blockstore/libs/storage/volume/volume_ut.cpp
> +        runtime->RegisterService(
зачем? если уж инициализировать, то где-то внутри PrepareTestActorRuntime

2024-07-16 17:43 UTC, qkrorlqr commented on cloud/blockstore/libs/storage/volume/volume_ut.cpp
> +            "vol0",                // diskId
что-то с отступом до коммента не то - комменты где-то далеко справа, и вообще часть комментов почему-то с одним отступом, часть - с другим

2024-07-16 17:43 UTC, qkrorlqr commented on cloud/blockstore/libs/storage/volume/volume_ut.cpp
> +        auto readRequest = volume.CreateReadBlocksRequest(
этот запрос должен нормально обрабатываться
после resize UsedBlocksMap должна тоже поресайзиться, а если она не ресайзится, это выглядит как баг

2024-07-17 11:11 UTC, sdimanx91 commented on cloud/blockstore/libs/storage/volume/volume_ut.cpp
> +        runtime->DispatchEvents({}, TDuration::Seconds(1));
Уже не зачем,  WriteBlocks же вроде синхронно пишет

2024-07-18 11:38 UTC, sdimanx91 commented on cloud/blockstore/libs/storage/volume/volume_ut.cpp
> +        auto readRequest = volume.CreateReadBlocksRequest(
Вот тут я не совсем понял, она может и поресайзится, но на диске то места меньше.

2024-07-18 12:11 UTC, sdimanx91 commented on cloud/blockstore/libs/storage/volume/volume_ut.cpp
> +        auto readRequest = volume.CreateReadBlocksRequest(
Короче, понятно.

UsedBlocksMap обновляться не должен, потому что это размер базового диска. А меняется размер оверлэйного.

Если изменить UsedBlocksMap, то по логике программы, станет непонятно откуда считывать данные.

2024-07-22 10:10 UTC, drbasic requested changes

2024-07-22 10:10 UTC, drbasic commented on cloud/blockstore/libs/storage/volume/volume_actor_forward_trackused.cpp
> +        // Use overlay. The disk may have been resized
это условие не достаточное. 
нужно проверить еще маску, если там все единицы, то тогда вернуть true

2024-07-22 10:14 UTC, drbasic commented on cloud/blockstore/libs/storage/volume/volume_actor_forward_trackused.cpp
> +        // Use overlay. The disk may have been resized
а вот если !Overlaps() тогда можно смело возвращать true, так как диапазоны запроса и базового диска не пересекаются и мы гарантированно читаем только с оверлейного диска.

И еще, нужно явно передать в функцию размер базового диска, так как битовая маска внутри  округляет размеры и не гарантирует что ее размер соответствует тому, который ей передавали при создании.

2024-07-22 16:06 UTC, qkrorlqr commented on cloud/blockstore/libs/storage/volume/volume_ut.cpp
> +        auto readRequest = volume.CreateReadBlocksRequest(
> UsedBlocksMap обновляться не должен, потому что это размер базового диска.

звучит очень странно
UsedBlocksMap в TVolumeActor изначально добавил я и это была мапа по кол-ву блоков конкретно того диска, за который отвечает этот TVolumeActor

2024-08-09 15:00 UTC, drbasic requested changes

2024-08-09 15:00 UTC, drbasic commented on cloud/blockstore/libs/storage/volume/volume_actor_forward_trackused.cpp
> +    const TCompressedBitmap* usedBlocks,
лучше usedBlocks через константную ссылку

2024-08-13 13:07 UTC, drbasic approved these changes

2024-08-13 14:11 UTC, qkrorlqr commented on cloud/blockstore/libs/storage/volume/volume_actor_forward_trackused.cpp
> +           baseDiskRange.End - range.Start + 1;
чтобы потом долго в уме не дебажить, можно добавить проверку
```
if (!baseDiskRange.Overlaps(range)) {
    return true;
}
```
рядом с аналогичной проверкой для usedBlocksRange

2024-08-13 14:11 UTC, qkrorlqr commented on cloud/blockstore/libs/storage/volume/volume_ut.cpp
> +    Y_UNIT_TEST(ShouldTrackusedFromOverlayAndBaseRequested)
TrackUsed

2024-08-13 14:11 UTC, qkrorlqr commented on cloud/blockstore/libs/storage/volume/volume_actor_forward_trackused.cpp
> +            if (const TCompressedBitmap* usedBlocks = State->GetUsedBlocks()) {
в каком случае тут может быть nullptr?

2024-08-13 14:11 UTC, qkrorlqr commented on cloud/blockstore/libs/storage/volume/volume_ut.cpp
> +                        event->Sender,
а почему отправитель и получатель совпадают?
и почему вообще просто не сделать msg->Record.Clear() вместо отправки события вручную?

2024-08-13 14:11 UTC, qkrorlqr commented on cloud/blockstore/libs/storage/volume/volume_ut.cpp
> +                case TEvVolume::TEvDescribeBlocksRequest::EventType: {
TEvVolume::EvDescribeBlocksRequest
в остальных case - аналогично

2024-08-13 14:11 UTC, qkrorlqr commented on cloud/blockstore/libs/storage/volume/volume_ut.cpp
> +                    UNIT_ASSERT_EQUAL("base_disk", msg->Record.GetDiskId());
UNIT_ASSERT_VALUES_EQUAL, т.к. он генерирует более подробный дифф при фейле

2024-08-13 14:13 UTC, qkrorlqr commented on cloud/blockstore/libs/storage/volume/volume_ut.cpp
> +        auto readRequest = volume.CreateReadBlocksRequest(
здесь все еще непонятно
UsedBlocksMap задумывался как битмапа для блоков вольюма, в котором она лежит, а не для блоков базового диска

2024-08-16 17:07 UTC, drbasic requested changes

2024-08-16 17:07 UTC, drbasic commented on cloud/blockstore/libs/storage/volume/volume_actor.cpp
> +bool TVolumeActor::CheckReadWriteBlockRange(const TBlockRange64& range) const
Формулируй работу с диапазонами через диапазоны.
Должно получится что-то вроде 
volumeRange.Contains(requestRange)

2024-08-16 17:07 UTC, drbasic commented on cloud/blockstore/libs/storage/volume/volume_actor_forward.cpp
> +TBlockRange64 GetRequestBlockRange(const typename TMethod::TRequest::TPtr& ev) {
есть BuildRequestBlockRange()

2024-08-16 17:07 UTC, drbasic commented on cloud/blockstore/libs/storage/volume/volume_actor_forward.cpp
> +                    << "invalid block range [" << "index: " << range.Start
Используй DescribeRange()

2024-08-16 17:15 UTC, drbasic commented on cloud/blockstore/libs/storage/volume/volume_actor_forward_trackused.cpp
> +            if (const TCompressedBitmap* usedBlocks = State->GetUsedBlocks()) {
Уже не актуально

2024-08-16 18:02 UTC, qkrorlqr approved these changes

2024-08-20 14:18 UTC, drbasic commented on cloud/blockstore/libs/storage/volume/volume_ut.cpp
> +            TBlockRange64::MakeClosedInterval(0, 1024 * 5),
напиши комментарий в чем идея запроса, почему он вызовет ошибку в партишене

2024-08-20 14:24 UTC, drbasic approved these changes

2024-08-20 16:01 UTC, qkrorlqr approved these changes

2024-08-20 16:05 UTC, merged