issue 1394: update agent only once
ydb-platform/nbs pull request #1476
Opened 2024-06-21 12:16 UTC by antonmyagkov

Issue: #1394

2024-07-02 10:14 UTC, sharpeye commented on cloud/blockstore/libs/storage/disk_registry/disk_registry_state.cpp
> +TVector<TDiskRegistryState::TDiskId> TDiskRegistryState::MarkDeviceAsClean(
М.б. переименовать в `MarkDevicesAsClean` ?

2024-07-02 17:41 UTC, antonmyagkov commented on cloud/blockstore/libs/storage/disk_registry/disk_registry_state.cpp
> +TVector<TDiskRegistryState::TDiskId> TDiskRegistryState::MarkDeviceAsClean(
Done

2024-07-04 13:01 UTC, sharpeye commented on cloud/blockstore/libs/storage/disk_registry/testlib/test_state.cpp
> +    TVector<TDirtyDevice> dirtyDevices)
Можно перегрузку добавить для `TVector<TDirtyDevice>` и оставить как было для `TVector<TString>`

2024-07-04 13:52 UTC, sharpeye approved these changes

2024-07-09 07:10 UTC, drbasic commented on cloud/blockstore/libs/storage/disk_registry/disk_registry_state.h
> +    TDiskId MarkDeviceAsClean(
Можно добавить комментарий что делает этот метод, что возвращается, идентификатор диск с которым что случилось?

2024-07-09 07:12 UTC, drbasic commented on cloud/blockstore/libs/storage/disk_registry/disk_registry_state.cpp
> +        AdjustDeviceIfNeeded(*device, {});
почему мы не передаем время вторым параметром в AdjustDeviceIfNeeded ?

2024-07-09 07:15 UTC, drbasic requested changes

2024-07-09 07:15 UTC, drbasic commented on cloud/blockstore/libs/storage/disk_registry/disk_registry_state.h
> +    TVector<TDeviceId> TryUpdateDevices(
комментарий что возвращается, идентификаторы девайсов которые были обновлены?

2024-07-09 07:21 UTC, komarevtsev-d submitted a review, later dismissed

2024-07-09 07:35 UTC, drbasic requested changes

2024-07-09 07:35 UTC, drbasic commented on cloud/blockstore/libs/storage/disk_registry/disk_registry_state.cpp
> +    TMap<TString, NProto::TAgentConfig*> agentsMap;
Не очень хорошо сохранять указатель, а потом вызывать методы, которые модифицируют состояние. В текущий момент времени проблем нет, агентов никто не удаляет, но если кто-то это сделает, будет неприятно.
Давай сохраним идентификатор агента, в цикле ниже найдем его еще раз.

2024-07-09 16:34 UTC, antonmyagkov commented on cloud/blockstore/libs/storage/disk_registry/disk_registry_state.h
> +    TDiskId MarkDeviceAsClean(
Done

```
/// Mark selected device as clean and remove it
/// from lists of suspended/dirty/pending cleanup devices
/// @return disk id where selected device was allocated
```

2024-07-09 16:34 UTC, antonmyagkov commented on cloud/blockstore/libs/storage/disk_registry/disk_registry_state.cpp
> +        AdjustDeviceIfNeeded(*device, {});
Нужно передавать Now()

Fixed

2024-07-09 16:35 UTC, antonmyagkov commented on cloud/blockstore/libs/storage/disk_registry/disk_registry_state.h
> +    TVector<TDeviceId> TryUpdateDevices(
Done

```
/// Try to update configuration of selected devices and their agents
/// in the disk registry database
/// @return List of updated devices
```

2024-07-09 16:35 UTC, antonmyagkov commented on cloud/blockstore/libs/storage/disk_registry/disk_registry_state.cpp
> +    TMap<TString, NProto::TAgentConfig*> agentsMap;
Исправил

2024-07-09 17:13 UTC, komarevtsev-d approved these changes

2024-07-10 06:01 UTC, drbasic commented on cloud/blockstore/libs/storage/disk_registry/disk_registry_state.cpp
> +        AdjustDeviceIfNeeded(*device, Now());
now был передан параметром

2024-07-10 06:01 UTC, drbasic commented on cloud/blockstore/libs/storage/disk_registry/disk_registry_state.h
>      bool TryUpdateDevice(
а что означает возвращаемый bool ?

2024-07-10 07:39 UTC, drbasic commented on cloud/blockstore/libs/storage/disk_registry/disk_registry_state.cpp
> +        AdjustDeviceIfNeeded(*device, Now());
и там выше не забудь удалить Y_UNUSED(now)

2024-07-10 08:47 UTC, drbasic approved these changes

2024-07-10 08:51 UTC, antonmyagkov commented on cloud/blockstore/libs/storage/disk_registry/disk_registry_state.h
>      bool TryUpdateDevice(
Задокументировал

2024-07-10 08:51 UTC, antonmyagkov commented on cloud/blockstore/libs/storage/disk_registry/disk_registry_state.cpp
> +        AdjustDeviceIfNeeded(*device, Now());
Поправил

2024-07-10 09:36 UTC, sharpeye approved these changes

2024-07-10 09:49 UTC, merged

2024-07-10 11:33 UTC, qkrorlqr commented on cloud/blockstore/libs/storage/disk_registry/disk_registry_state.cpp
> +        agentsMap.emplace(agent->agentid());
agentid -> GetAgentId
у нас в коде, сгенеренном protoc, генерятся соответсвующие стайлгайду методы помимо дефолтных методов

2024-07-10 11:33 UTC, qkrorlqr commented on cloud/blockstore/libs/storage/disk_registry/disk_registry_state.cpp
> +    TSet<TAgentId> agentsMap;
это какой-то agentSet, а не Map