reporting metrics to hive from filestore
ydb-platform/nbs pull request #1503
Opened 2024-06-26 12:03 UTC by Sazonov99

#1175

2024-07-01 13:39 UTC, qkrorlqr commented on cloud/filestore/libs/storage/tablet/tablet_actor.cpp
> +    std::ostringstream oss;
во-первых, у нас есть TStringBuilder
во-вторых, не надо собирать сообщение для __дебажного__ логирования вне макроса LOG_DEBUG, т.к. у тебя в таком случае это сообщение будет собираться всегда, а не только тогда, когда loglevel выставлен в DEBUG

2024-07-01 13:39 UTC, qkrorlqr commented on cloud/filestore/libs/storage/tablet/tablet_actor.cpp
> +    Y_UNUSED(ctx);
где ж он unused-то
он вполне-себе used

2024-07-01 13:40 UTC, qkrorlqr commented on cloud/filestore/libs/storage/tablet/tablet_private.h
> +                ui64 cycles = 0)
не надо дефолтных значений
это ж отличный способ забыть где-нибудь передать значение и удивляться, почему мы нули репортим в метриках

2024-07-01 13:41 UTC, qkrorlqr reviewed
У нас уже собираются цифры по потреблению cpu - в ElapsedMicrosecByActivity
С разбивкой по акторам
Нельзя эти цифры зарепортить в хайв, чтоб не писать руками в каждом методе еще раз вычисление потраченного цпу?

2024-07-09 09:14 UTC, yegorskii commented on cloud/filestore/libs/storage/tablet/tablet_actor_counters.cpp
> +    i64 sumRequestBytes =
Compaction забыл. Вообще было бы неплохо придумать что-то чтобы при добавлении запроса не приходилось тут что-то еще править. Можно конечно через макросы сделать.....

2024-07-09 13:09 UTC, Sazonov99 commented on cloud/filestore/libs/storage/tablet/tablet_actor_counters.cpp
> +    i64 sumRequestBytes =
Я могу конечно что-то такое написать:

```
#define SUM_REQUEST_BYTES(metrics, field) sumRequestBytes += metrics.field.RequestBytes;

#define SUM_ALL_REQUEST_BYTES(metrics)                 \
    SUM_REQUEST_BYTES(metrics, ReadBlob)               \
    SUM_REQUEST_BYTES(metrics, WriteBlob)              \
    SUM_REQUEST_BYTES(metrics, PatchBlob)              \
    SUM_REQUEST_BYTES(metrics, ReadData)               \
    SUM_REQUEST_BYTES(metrics, DescribeData)           \
    SUM_REQUEST_BYTES(metrics, WriteData)              \
    SUM_REQUEST_BYTES(metrics, AddData)                \
    SUM_REQUEST_BYTES(metrics, GenerateBlobIds)        \
    SUM_REQUEST_BYTES(metrics, Cleanup)                \
    SUM_REQUEST_BYTES(metrics, Flush)                  \
    SUM_REQUEST_BYTES(metrics, FlushBytes)             \
    SUM_REQUEST_BYTES(metrics, TrimBytes)              \
    SUM_REQUEST_BYTES(metrics, CollectGarbage)         \
    SUM_REQUEST_BYTES(metrics, Compaction)             \
    

```

Но так, просто придется править в другом месте. Если ты имел ввиду что-то другое под макросами, покажи пример?

2024-07-11 08:00 UTC, drbasic requested changes

2024-07-11 08:00 UTC, drbasic commented on cloud/filestore/libs/storage/tablet/tablet_actor.cpp
> +NKikimr::NMetrics::TResourceMetrics* TIndexTabletActor::GetResourceMetrics()
не понятна ценность этого метода, можно напрямую обратиться?

2024-07-11 08:40 UTC, qkrorlqr requested changes
нужны ut

2024-07-11 08:50 UTC, drbasic commented on cloud/filestore/libs/storage/tablet/tablet_actor.h
> +        i64 PastNetworkMetric = 0;
там далее ожидается знаковое число?

2024-07-11 08:50 UTC, drbasic commented on cloud/filestore/libs/storage/tablet/tablet_actor.h
> +        i64 TakeSumRequestBytes()
реализацию нетривиальных методов нужно выносить в cpp

2024-07-11 09:45 UTC, drbasic approved these changes

2024-07-11 10:16 UTC, qkrorlqr commented on cloud/filestore/libs/storage/tablet/tablet_ut_stats.cpp
> +
?

2024-07-11 10:17 UTC, qkrorlqr commented on cloud/filestore/libs/storage/tablet/ut/ya.make
> +    tablet_ut_stats.cpp
уже есть ut_counters - добавься туда

2024-07-11 10:53 UTC, qkrorlqr commented on cloud/filestore/libs/storage/tablet/tablet_actor.h
> +                TVector<TRequestMetrics*>& allRequestMetrics)
не хватает отступа

2024-07-11 10:53 UTC, qkrorlqr commented on cloud/filestore/libs/storage/tablet/tablet_actor.h
> +        static constexpr const ui32 RequestMetricsCount = 14;
зачем эта константа?

2024-07-11 10:54 UTC, qkrorlqr commented on cloud/filestore/libs/storage/tablet/tablet_actor_counters.cpp
> +    auto *resourceMetrics = Executor()->GetResourceMetrics();
auto* resourceMetrics

2024-07-11 10:55 UTC, qkrorlqr commented on cloud/filestore/libs/storage/tablet/tablet_actor_counters.cpp
> +    resourceMetrics->Network.Increment(Metrics.TakeTotalRequestBytes(), ctx.Now());
а там нету какого-нибудь Set вместо Increment? чтоб не заниматься вычитаниями всякими (я тут не про перформанс, а про упрощение кода)

2024-07-11 10:57 UTC, qkrorlqr commented on cloud/filestore/libs/storage/tablet/tablet_actor_counters.cpp
> +void TIndexTabletActor::SendMetricsToHive(const TActorContext& ctx)
название вводит в заблуждение
тут ничего в хайв не отправляется явным образом - тут просто репортятся метрики в таблеточного экзекьютора
ReportMetricsToExecutor

2024-07-11 16:14 UTC, Sazonov99 commented on cloud/filestore/libs/storage/tablet/tablet_actor_counters.cpp
> +    resourceMetrics->Network.Increment(Metrics.TakeTotalRequestBytes(), ctx.Now());
Set есть, но он делает не то, что нам нужно. Он устанавливает полученное значение как среднее. Если упрощать код:
```
    void Set(ValueType value, TInstant now = TInstant::Now()) {
        AverageValue = value;
    }
```

Increment в свою очередь находит высчитывает значение, что больше похоже на то, чо мы хотим получить:
```
    void Increment(std::make_signed_t<ValueType> value, TInstant now = TInstant::Now()) {
        AccumulatorValue += value;
        auto time(GetTimeValue(now - LastUpdate));
        if (time >= DurationToStore) {
            AverageValue = GetSumOfAverages(AverageValue, GetValueAveragePerDuration(DurationToCalculate, time));
        }
    }
```

2024-07-16 10:50 UTC, qkrorlqr commented on cloud/filestore/libs/storage/tablet/tablet_ut_counters.cpp
> +        bool equalWithInaccuracy = (0.95 < (sz / (network * reportInterval))) &&
есть UNIT_ASSERT_DOUBLES_EQUAL, в который можно передать погрешность

2024-07-16 10:51 UTC, qkrorlqr commented on cloud/filestore/libs/storage/tablet/tablet_ut_counters.cpp
> +                return reportCount;
если этот евент не придет, тест повиснет навсегда и весь suite упадет по таймауту?

2024-07-16 12:43 UTC, qkrorlqr approved these changes

2024-07-17 09:22 UTC, yegorskii approved these changes

2024-07-17 09:26 UTC, merged