NBS-4826 send message about long running blob operations to TPartitionActor and TVolumeActor
ydb-platform/nbs pull request #151
Opened 2024-01-16 06:40 UTC by drbasic

2024-01-17 09:45 UTC, budevg submitted a review, later dismissed

2024-01-17 16:59 UTC, qkrorlqr approved these changes

2024-01-17 16:59 UTC, qkrorlqr commented on cloud/blockstore/libs/storage/partition/part_ut.cpp
> +        // requests send to TPartitionActor and TVolumeActor.
sent to

2024-01-17 16:59 UTC, qkrorlqr commented on cloud/blockstore/libs/storage/partition/part_ut.cpp
> +        // Wait for EvLongRunningOperation (finish or cancel) arrived.
arrived -> arrival

2024-01-17 16:59 UTC, qkrorlqr commented on cloud/blockstore/libs/storage/partition/part_ut.cpp
> +            partition.SendReadBlocksRequest(0);   //
а зачем тут //?

2024-01-17 16:59 UTC, qkrorlqr commented on cloud/blockstore/libs/storage/partition_common/actor_read_blob.cpp
> +        VolumeTabletId,
странно, что тут появляется VolumeTabletId, т.к. компонент - PARTITION_COMMON, да и в целом мы привыкли в логах работы с блобстораджем видеть partition tablet id

2024-01-17 16:59 UTC, qkrorlqr commented on cloud/blockstore/libs/storage/partition_common/long_running_operation_companion.h
> +    void RequestCanceled(const NActors::TActorContext& ctx);
опять докопаюсь до букв: у нас почти везде написано cancelled (с двумя l) - давай и тут с двумя писать (и в EReason тоже)

2024-01-17 16:59 UTC, qkrorlqr commented on cloud/blockstore/libs/storage/volume/volume_actor_stats.cpp
> +        const TString reason =
давай полноценно конвертнем EReason в TString? "Finished"/"Cancelled"/"LongRunningDetected"

2024-01-17 16:59 UTC, qkrorlqr commented
еще надо прекоммитный чек перезапустить

2024-01-19 07:51 UTC, drbasic commented on cloud/blockstore/libs/storage/partition/part_ut.cpp
> +            partition.SendReadBlocksRequest(0);   //
Уже не нужно, с текущими настройками clang-format все ОК

2024-01-19 12:59 UTC, qkrorlqr approved these changes

2024-01-20 05:40 UTC, komarevtsev-d approved these changes

2024-01-20 05:42 UTC, komarevtsev-d requested changes
Падают тесты cloud/blockstore/libs/storage/partition_common/ut. Не твоё?

2024-01-20 05:58 UTC, komarevtsev-d approved these changes

2024-01-21 12:27 UTC, merged