[NBS] POC: default encryption for NRD
ydb-platform/nbs pull request #1533
Opened 2024-07-02 19:04 UTC by sharpeye

2024-07-15 06:34 UTC, drbasic commented on cloud/blockstore/apps/client/lib/command.cpp
> +        CreateDefaultEncryptionKeyProvider(),
вызов CreateDefaultEncryptionKeyProvider() приводит к чтению из KMS, кейринг и т.п. 
Если можно это сделать один раз, то лучше запомнить ответ и использовать два раза.

2024-07-15 10:33 UTC, sharpeye commented on cloud/blockstore/apps/client/lib/command.cpp
> +        CreateDefaultEncryptionKeyProvider(),
CreateDefaultEncryptionKeyProvider никуда не ходит - создается провайдер, который умеет ходить.

2024-07-15 11:53 UTC, drbasic submitted a review, later dismissed

2024-07-23 13:22 UTC, drbasic approved these changes

2024-08-05 18:52 UTC, qkrorlqr requested changes
С такими PR нужен также md-файл с описанием работы этого механизма где-то в /doc/blockstore

2024-08-05 18:52 UTC, qkrorlqr commented on cloud/blockstore/config/storage.proto
> +    optional bool DefaultEncryptionForNonReplicatedDisksEnabled = 377;
так не только NonReplicated же
DiskRegistryBased

2024-08-05 18:52 UTC, qkrorlqr commented on cloud/blockstore/libs/encryption/encryption_client.cpp
> +    // XXX: why not inplace decrypt?
так, может, не XXX напишем, а какой-нибудь TODO с указанием issue?

2024-08-05 18:52 UTC, qkrorlqr commented on cloud/blockstore/libs/encryption/encryption_client.cpp
> +        return MakeError(E_ARGUMENT, "The destination buffer is too small");
давай в текст ошибки добавим dst.size() и src.size()

2024-08-05 18:52 UTC, qkrorlqr commented on cloud/blockstore/libs/encryption/encryption_client.cpp
> +            return MakeError(E_FAIL, "Encryptor has generated a zero block!");
давай сюда передадим тот же message, что и в ReportXXX

2024-08-05 18:52 UTC, qkrorlqr commented on cloud/blockstore/libs/encryption/encryption_client.cpp
> +                        "Encryption client is destroyed");
давай, чтоб можно было различить с предыдущим кейсом, напишем тут Encryption client is destroyed after mount или что-то в этом духе

2024-08-05 18:52 UTC, qkrorlqr commented on cloud/blockstore/libs/encryption/encryption_client.cpp
> +        Y_UNUSED(EncryptionKeyProvider);
почему не используем?

2024-08-05 18:52 UTC, qkrorlqr commented on cloud/blockstore/libs/encryption/encryption_client.cpp
> +        TEncryptionKey key{Base64Decode(volume.GetEncryptionDesc().GetKeyHash())};
э, а как это так мы получаем ключ ИЗ хэша ключа?

2024-08-05 18:52 UTC, qkrorlqr commented on cloud/blockstore/libs/encryption/encryption_client_ut.cpp
> +                E_ARGUMENT, // Unexpected encription mode
encryption

2024-08-05 18:52 UTC, qkrorlqr commented on cloud/blockstore/libs/storage/service/service_actor_create.cpp
> +void TCreateEncryptionKeyActor::Bootstrap(const TActorContext& ctx)
а почему через актора? заглушка под правильное получение ключа через шифрование рандома на KEK из RootKMS?

2024-08-05 18:52 UTC, qkrorlqr commented on cloud/blockstore/libs/storage/service/service_actor_create.cpp
> +        GetStorageMediaKind() != NProto::STORAGE_MEDIA_SSD_LOCAL &&    // XXX
TODO с указанием issue

2024-08-05 18:52 UTC, qkrorlqr commented on cloud/blockstore/libs/storage/service/service_actor_create.cpp
> +            NKikimr::AppData()->IOPoolId);
а почему IOPool? в нем же обычно всякие логгеры живут и в целом код, который может с локальными файлами работать и не чувствителен к латенси

тут разве Batch-пул не лучше подойдет?

2024-08-05 18:52 UTC, qkrorlqr commented on cloud/blockstore/libs/storage/volume/volume_actor_forward_trackused.cpp
> +        volumeConfig.GetEncryptionDesc().GetMode() == NProto::ENCRYPTION_AES_XTS;
почему проверка поменялась?

2024-08-05 18:52 UTC, qkrorlqr commented on cloud/blockstore/libs/storage/volume/volume_state.cpp
> +        if (encryptionDesc.GetMode() == NProto::ENCRYPTION_AES_XTS) {
а тут еще и копипаста этого странного условия

2024-08-05 18:52 UTC, qkrorlqr commented on cloud/blockstore/public/api/protos/encryption.proto
> +    // VolumeConfig.EncryptionDesc.KeyHash as base64.
так, может, новое поле завести? Key + KekId
если KekId пустой, то, значит, Key - plaintext

2024-08-05 18:52 UTC, qkrorlqr commented on cloud/blockstore/tests/default_encryption/test.py
> +    disk_agent_config = generate_disk_agent_txt(
а зачем у нас какой-то новый способ конфигурирования агентов тут появляется? почему не такой же код, как, например, в local-nonrepl loadtest-е?

2024-12-04 19:35 UTC, closed without merging