issue-1146: preliminary changes: refacto RO txs: allow them to be ran atop of IIndexTabletDatabase + implement fast path for them
ydb-platform/nbs pull request #1563
Opened 2024-07-08 17:01 UTC by debnatkh

2024-07-23 14:09 UTC, debnatkh commented on cloud/filestore/libs/storage/tablet/tablet_tx.h
> +// RW transactions that modify inode-related tables
лишний комментарий

2024-07-23 15:25 UTC, qkrorlqr requested changes

2024-07-29 16:02 UTC, qkrorlqr commented on cloud/filestore/libs/storage/core/tablet.h
> +            Y_UNUSED(tx);                                                      \
tx тут вполне себе used

2024-07-29 16:14 UTC, qkrorlqr commented on cloud/filestore/libs/storage/tablet/tablet_state_nodes.cpp
> +
лишняя пустая строка

2024-07-29 16:14 UTC, qkrorlqr commented on cloud/filestore/libs/storage/tablet/tablet_state_nodes.cpp
> +IIndexTabletDatabase& TIndexTabletState::GetInMemoryIndexState() {
{ не там

2024-07-29 16:15 UTC, qkrorlqr commented on cloud/filestore/libs/storage/tablet/tablet_state.h
> +    IIndexTabletDatabase& GetInMemoryIndexState();
AccessInMemoryIndexState() (если нужен)
и GetInMemoryIndexState() const (если нужен)

2024-07-30 10:38 UTC, qkrorlqr approved these changes

2024-07-30 10:43 UTC, yegorskii approved these changes

2024-07-30 10:44 UTC, merged