set items count limit for TTrimBytes transaction
ydb-platform/nbs pull request #1647
Opened 2024-07-22 14:39 UTC by yegorskii

2024-07-23 13:37 UTC, qkrorlqr requested changes

2024-07-23 13:37 UTC, qkrorlqr commented on cloud/filestore/config/storage.proto
> +    optional uint64 TrimBytesItemsCount = 359;
ItemCount

2024-07-23 13:37 UTC, qkrorlqr commented on cloud/filestore/libs/storage/tablet/model/fresh_bytes.h
> +        ui64 DataItemsProcessed = 0;
эти 2 поля не нужны - их может вычислять сам визитор
в итоге и TVisitTopResult не нужен - вместо него достаточно bool

2024-07-23 13:37 UTC, qkrorlqr commented on cloud/filestore/libs/storage/tablet/tablet_state_data.cpp
> +std::pair<ui64, bool> TIndexTabletState::FinishFlushBytes(
грязно
по этой сигнатуре вообще не понять, что на самом деле возвращается
TFlushBytesStats какой-нибудь надо вернуть, где будут именованные поля

2024-07-23 13:37 UTC, qkrorlqr commented on cloud/filestore/libs/storage/tablet/tablet_state_data.cpp
> +    if (result.ChunkCompleted) {
тоже грязно
у тебя может быть одна единственная ф-ция FinishCleanup(chunkId, itemCount, markerCount), которая уже внутри себя поймет, закончился чанк и надо его удалить или же нет
и вообще сама эта ф-ция может вернуть bool со смыслом, что чанк удален, а VisitTop может вообще свою сигнатуру не менять

2024-07-23 13:50 UTC, yegorskii commented on cloud/filestore/config/storage.proto
> +    optional uint64 TrimBytesItemsCount = 359;
да когда же я уже запомню(

2024-07-24 12:09 UTC, qkrorlqr commented on cloud/filestore/libs/storage/tablet/model/fresh_bytes.cpp
> +    return;
wtf

2024-07-24 12:10 UTC, qkrorlqr commented on cloud/filestore/libs/storage/tablet/model/fresh_bytes.cpp
> +    if (dataItems == dataSize) {
а зачем тут if? разве erase от begin до end не будет эквивалентен clear()?

2024-07-24 12:10 UTC, qkrorlqr commented on cloud/filestore/libs/storage/tablet/model/fresh_bytes.cpp
> +    ui64 dataItems,
давай лучше dataItemCount, deletionMarkerCount

2024-07-24 12:11 UTC, qkrorlqr commented on cloud/filestore/libs/storage/tablet/model/fresh_bytes_ut.cpp
> +        UNIT_ASSERT_VALUES_EQUAL(
зачем VALUES_EQUAL с булем? просто UNIT_ASSERT

2024-07-24 12:12 UTC, qkrorlqr commented on cloud/filestore/libs/storage/tablet/model/fresh_bytes.cpp
> +    ui64 itemsLimit,
itemLimit
кстати, в другом месте в этом же PR у тебя как раз itemLimit

2024-07-24 12:38 UTC, yegorskii commented on cloud/filestore/libs/storage/tablet/model/fresh_bytes.cpp
> +    ui64 itemsLimit,
Мне это правило никогда не дастся....

2024-07-24 19:13 UTC, yegorskii commented on cloud/filestore/libs/storage/tablet/model/fresh_bytes.cpp
> +    chunk.Data.erase(
Я добавил STORAGE_VERIFY, но он тут не очень полезен потому что LogTag в этом классе недоступен(

2024-07-25 10:15 UTC, qkrorlqr commented on cloud/filestore/libs/storage/tablet/model/fresh_bytes.cpp
> +    STORAGE_VERIFY(check, TWellKnownEntityTypes::FILESYSTEM, chunkId);
chunkId - это вообще не fsId

2024-07-25 15:24 UTC, drbasic approved these changes

2024-07-25 15:27 UTC, merged