NBSDUTY-32: fix generation of space only lines in config_generator
ydb-platform/nbs pull request #1660
Opened 2024-07-23 20:06 UTC by budevg

2024-07-24 12:16 UTC, qkrorlqr requested changes
надо переканонизировать тесты

2024-07-24 12:17 UTC, qkrorlqr commented on cloud/storage/core/tools/common/go/configurator/configurator.go
> +	err = trimWhiteSpaceLines(filePath)
а нельзя ли сразу при генерации не генерить эти trailing-пробелы? чтоб не постфактум их чистить регулярками

2024-07-25 08:02 UTC, budevg commented on cloud/storage/core/tools/common/go/configurator/configurator.go
> +	err = trimWhiteSpaceLines(filePath)
Вот тут https://github.com/ydb-platform/nbs/blob/users/evgenybud/config-generator-whitespaces/cloud/storage/core/tools/common/go/configurator/configurator.go#L484 используется template, который выглядит вот так https://github.com/ydb-platform/nbs/blob/users/evgenybud/config-generator-whitespaces/cloud/storage/core/tools/ops/config_generator/gotest/test_service/values.yaml#L3


.Text там с отступами, и поэтому в каждый \n добавляются пробелы. 
Не нашёл, как сделать, чтобы template сам это делал, поэтому написал функцию, которая убирает пробелы, где не надо.

2024-07-25 10:35 UTC, sharpeye commented on cloud/storage/core/tools/common/go/configurator/configurator.go
> +	err = trimWhiteSpaceLines(filePath)
Можно добавить функцию `trim` в сам шаблон:
```yaml
config:
{{ range .Configs }}
  {{ .FileName }}: |+
    {{ .Text | trim }}
{{ end }}
```
и в коде:
```go
valuesTemplate := template.New(filepath.Base(valuesTemplatePath)).Funcs(template.FuncMap{
	"trim": func (s string) string {
		return strings.TrimSpace(s)
	},
})
valuesTemplate, err := valuesTemplate.ParseFiles(valuesTemplatePath)
```

2024-07-28 08:13 UTC, budevg commented on cloud/storage/core/tools/common/go/configurator/configurator.go
> +	err = trimWhiteSpaceLines(filePath)
Хорошая идея, но не очень хочется связывать шаблон в одном репозитории с функциями, реализованными в другом репозитории. По-моему, моё решение довольно простое и читабельное.

2024-07-30 07:40 UTC, drbasic approved these changes

2024-07-30 07:58 UTC, sharpeye approved these changes

2024-07-30 08:07 UTC, merged