Use smart pointers for memory mangement
ydb-platform/nbs pull request #1662
Opened 2024-07-24 12:30 UTC by drbasic

2024-07-25 10:23 UTC, sharpeye commented on cloud/blockstore/vhost-server/request_aio.cpp
> +    const auto *it = std::lower_bound(
lower_bound возвращает итератор, а не указатель

2024-07-25 10:23 UTC, sharpeye commented on cloud/blockstore/vhost-server/request_aio.h
> +using TAioRequestHolder = std::unique_ptr<TAioRequest, TAioRequestDeleter>;
А почему не TAioRequestPtr?

2024-07-25 10:28 UTC, drbasic commented on cloud/blockstore/vhost-server/request_aio.cpp
> +    const auto *it = std::lower_bound(
который является указателем

2024-07-25 10:30 UTC, drbasic commented on cloud/blockstore/vhost-server/request_aio.h
> +using TAioRequestHolder = std::unique_ptr<TAioRequest, TAioRequestDeleter>;
Можно и Ptr. Тут эти типы используются для обеспечения времени жизни, потому так и назвал. Могу поменять.

2024-07-25 10:40 UTC, sharpeye commented on cloud/blockstore/vhost-server/request_aio.cpp
> +    const auto *it = std::lower_bound(
Это сейчас, а потом добавят какой-нить debug_checked_iterator в вектор для debug-сборок (как в STL для MS VS) - перестанет собираться.

2024-07-25 12:56 UTC, budevg requested changes

2024-07-25 12:56 UTC, budevg commented on cloud/blockstore/vhost-server/request_aio.h
> +    CreateNew(size_t bufferCount, vhd_io* io, TCpuCycles submitTs);
```c++
    static TAioCompoundRequestHolder CreateNew(
        int inflight,
        vhd_io* io,
        size_t bufferSize,
        TCpuCycles submitTs);
```

2024-07-26 08:17 UTC, budevg approved these changes

2024-07-26 08:29 UTC, sharpeye approved these changes

2024-07-26 08:36 UTC, komarevtsev-d approved these changes

2024-07-26 08:36 UTC, merged