add force operation to delete all zero compaction stat ranges; add aсtion to write specified data to compaction map table
ydb-platform/nbs pull request #1690
Opened 2024-07-30 12:50 UTC by WilyTiger

#1128

2024-07-31 13:05 UTC, qkrorlqr requested changes

2024-07-31 13:05 UTC, qkrorlqr commented on cloud/filestore/libs/storage/tablet/tablet_actor_monitoring.cpp
> +    } else {
else if mode == "..."

2024-07-31 13:05 UTC, qkrorlqr commented on cloud/filestore/libs/storage/tablet/tablet_database.cpp
> +void TIndexTabletDatabase::WriteCompactionMap(
эти функции не нужны, можно пользоваться существующей WriteCompactionMap(rangeId, blobsCount, deletionsCount) функцией

2024-07-31 13:05 UTC, qkrorlqr commented on cloud/filestore/libs/storage/tablet/tablet_actor.cpp
> +                i += Config->GetMaxDeleteZeroCompactionRangesPerTx();
а зачем так хитро? почему не скопировать просто весь ZeroScoreRanges?

2024-07-31 13:05 UTC, qkrorlqr commented on cloud/filestore/libs/storage/tablet/tablet_actor_delete_zero_compaction_ranges.cpp
> +        if (!GetCompactionStats(range).BlobsCount &&
проще сделать транзакцию не DeleteZeroCompactionRanges, а транзакцию RewriteCompactionRanges, которая примет параметром список rangeId и просто вызовет db.WriteCompactionMap(rangeId, currentBlobsCount, currentDeletionsCount)

2024-08-05 12:25 UTC, qkrorlqr requested changes

2024-08-05 12:25 UTC, qkrorlqr commented on cloud/filestore/libs/storage/tablet/tablet_tx.h
> +                const TVector<NProtoPrivate::TCompactionRangeStats>& ranges)
by-value передавай
иначе move не имеет смысла

2024-08-05 12:25 UTC, qkrorlqr commented on cloud/filestore/libs/storage/tablet/tablet_private.h
> +        TDeleteZeroCompactionRangesRequest(ui32 rangeId)
explicit

2024-08-05 12:25 UTC, qkrorlqr commented on cloud/filestore/libs/storage/tablet/tablet_tx.h
> +        TDeleteZeroCompactionRanges(TRequestInfoPtr requestInfo, ui32 startIndex)
```
# echo -n '         TDeleteZeroCompactionRanges(TRequestInfoPtr requestInfo, ui32 startIndex)'|wc -c
82
```

2024-08-05 12:25 UTC, qkrorlqr commented on cloud/filestore/libs/storage/tablet/tablet_tx.h
> +        ui32 StartIndex;
const

2024-08-05 12:25 UTC, qkrorlqr commented on cloud/filestore/libs/storage/tablet/tablet_tx.h
> +        TVector<NProtoPrivate::TCompactionRangeStats> Ranges;
const?

2024-08-05 12:25 UTC, qkrorlqr commented on cloud/filestore/libs/storage/tablet/tablet_ut_data.cpp
> +        env.GetRuntime().SetEventFilter([&] (auto& runtime, TAutoPtr<IEventHandle>& event) {
```
# echo -n '        env.GetRuntime().SetEventFilter([&] (auto& runtime, TAutoPtr<IEventHandle>& event) {'|wc -c
92
```

2024-08-05 12:25 UTC, qkrorlqr commented on cloud/filestore/libs/storage/tablet/tablet_ut_data.cpp
> +                case TEvIndexTabletPrivate::EvDeleteZeroCompactionRangesRequest: {
```
# echo -n '                case TEvIndexTabletPrivate::EvDeleteZeroCompactionRangesRequest: {'|wc -c
82
```

2024-08-05 12:25 UTC, qkrorlqr commented on cloud/filestore/libs/storage/tablet/tablet_ut_data.cpp
> +                    requests++;
++requests

2024-08-05 12:25 UTC, qkrorlqr commented on cloud/filestore/libs/storage/tablet/tablet_ut_data.cpp
> +        tablet.ForcedOperation(NProtoPrivate::TForcedOperationRequest::E_DELETE_EMPTY_RANGES);
```
# echo -n '        tablet.ForcedOperation(NProtoPrivate::TForcedOperationRequest::E_DELETE_EMPTY_RANGES);'|wc -c
94
```

2024-08-05 12:25 UTC, qkrorlqr commented on cloud/filestore/libs/storage/tablet/tablet_ut_data.cpp
> +            TEvIndexTabletPrivate::EForcedRangeOperationMode::DeleteZeroCompactionRanges);
```
# echo -n '            TEvIndexTabletPrivate::EForcedRangeOperationMode::DeleteZeroCompactionRanges);'|wc -c
90
```

2024-08-14 17:20 UTC, qkrorlqr commented on cloud/filestore/libs/storage/service/service_ut.cpp
> +
лишняя пустая строка

2024-08-14 17:24 UTC, qkrorlqr approved these changes

2024-08-14 18:40 UTC, yegorskii submitted a review, later dismissed

2024-08-15 11:33 UTC, yegorskii approved these changes

2024-08-15 11:38 UTC, qkrorlqr approved these changes

2024-08-15 11:57 UTC, merged