issue-1146: implement getters for in-memory cache
ydb-platform/nbs pull request #1692
Opened 2024-07-30 17:26 UTC by debnatkh

The in-memory state consists of 6 maps/unordered_maps, mirroring the contents of the following tables:

* Nodes
* NodesVer
* NodeAttrs
* NodeAttrsVer
* NodeRefs
* NodeRefsVer

For now the state is read-only, thus, so far there are no unit-tests.

References #1146

2024-07-30 17:43 UTC, debnatkh commented on cloud/filestore/config/storage.proto
> +
лишняя строка

2024-08-05 10:35 UTC, qkrorlqr requested changes

2024-08-05 10:35 UTC, qkrorlqr commented on cloud/filestore/libs/storage/tablet/model/alloc.h
> +    InMemoryCache,
InMemoryNodeIndexCache?

2024-08-05 10:35 UTC, qkrorlqr commented on cloud/filestore/libs/storage/tablet/tablet_state_cache.cpp
> +        TNodeAttrsVerKey(nodeId, name, ReverseCommitId(commitId)));
а зачем в кэше в памяти делать Reverse? это ж нужно для локальной базы, т.к. там только в одну сторону можно эффективно ходить по таблице

2024-08-05 10:35 UTC, qkrorlqr commented on cloud/filestore/libs/storage/tablet/tablet_state_cache.h
> +    public:
не нужно

2024-08-05 10:35 UTC, qkrorlqr commented on cloud/filestore/libs/storage/tablet/tablet_state_cache.h
> +        ui64 CommitId;
= 0

2024-08-05 10:35 UTC, qkrorlqr commented on cloud/filestore/libs/storage/tablet/tablet_state_cache.h
> +    public:
не нужно в struct

2024-08-05 10:35 UTC, qkrorlqr commented on cloud/filestore/libs/storage/tablet/tablet_state_cache.h
> +    public:
не нужно в struct

2024-08-05 10:35 UTC, qkrorlqr commented on cloud/filestore/libs/storage/tablet/tablet_state_cache.h
> +        ui64 MaxCommitId;
= 0

2024-08-05 10:35 UTC, qkrorlqr commented on cloud/filestore/libs/storage/tablet/tablet_state_cache.h
> +    public:
.

2024-08-05 10:35 UTC, qkrorlqr commented on cloud/filestore/libs/storage/tablet/tablet_state_cache.h
> +    public:
.

2024-08-05 10:35 UTC, qkrorlqr commented on cloud/filestore/libs/storage/tablet/tablet_state_cache.h
> +    };   // namespace NCloud::NFileStore::NStorage
?

2024-08-05 10:35 UTC, qkrorlqr commented on cloud/filestore/libs/storage/tablet/tablet_state_cache.h
> +    public:
.

2024-08-05 10:35 UTC, qkrorlqr commented on cloud/filestore/libs/storage/tablet/tablet_state_cache.h
> +        ui64 CommitId;
= 0

2024-08-05 10:35 UTC, qkrorlqr commented on cloud/filestore/libs/storage/tablet/tablet_state_cache.h
> +        ui64 Version;
= 0

2024-08-05 10:35 UTC, qkrorlqr commented on cloud/filestore/libs/storage/tablet/tablet_state_cache.h
> +    public:
.

2024-08-05 10:35 UTC, qkrorlqr commented on cloud/filestore/libs/storage/tablet/tablet_state_cache.h
> +    public:
.

2024-08-05 10:35 UTC, qkrorlqr commented on cloud/filestore/libs/storage/tablet/tablet_state_cache.h
> +        ui64 MaxCommitId;
= 0

2024-08-05 10:35 UTC, qkrorlqr commented on cloud/filestore/libs/storage/tablet/tablet_state_cache.h
> +        ui64 Version;
= 0

2024-08-05 10:35 UTC, qkrorlqr commented on cloud/filestore/libs/storage/tablet/tablet_state_cache.h
> +    public:
.

2024-08-05 10:35 UTC, qkrorlqr commented on cloud/filestore/libs/storage/tablet/tablet_state_cache.h
> +    public:
.

2024-08-05 10:35 UTC, qkrorlqr commented on cloud/filestore/libs/storage/tablet/tablet_state_cache.h
> +        ui64 CommitId;
= 0

2024-08-05 10:35 UTC, qkrorlqr commented on cloud/filestore/libs/storage/tablet/tablet_state_cache.h
> +        ui64 ChildId;
= 0

2024-08-05 10:35 UTC, qkrorlqr commented on cloud/filestore/libs/storage/tablet/tablet_state_cache.h
> +    public:
.

2024-08-12 17:28 UTC, debnatkh commented on cloud/filestore/libs/storage/tablet/tablet_state_cache.cpp
> +        TNodeAttrsVerKey(nodeId, name, ReverseCommitId(commitId)));
Сделал так чтобы отличие с кодом с локальной базой было минимально и его корректность можно было верифицировать глазами

2024-08-22 18:22 UTC, qkrorlqr commented on cloud/filestore/libs/storage/core/config.h
> +
лишняя пустая строка

2024-08-22 18:22 UTC, qkrorlqr commented on cloud/filestore/libs/storage/tablet/tablet_state_cache.cpp
> +    // determine, whether the set of stored attributes is complete.
мы в общем-то могли бы всегда загружать вообще все атрибуты ноды в кэш

2024-08-22 18:22 UTC, qkrorlqr commented on cloud/filestore/libs/storage/tablet/tablet_state_cache.h
> +    struct TWriteNodeRequest {
{ не там
в некоторых других местах тоже

2024-08-22 18:25 UTC, debnatkh commented on cloud/filestore/libs/storage/tablet/tablet_state_cache.cpp
> +    // determine, whether the set of stored attributes is complete.
https://github.com/ydb-platform/nbs/issues/1146#issuecomment-2305382745

2024-08-23 16:10 UTC, qkrorlqr approved these changes

2024-08-26 09:05 UTC, yegorskii approved these changes

2024-08-26 10:39 UTC, yegorskii approved these changes

2024-08-26 11:34 UTC, qkrorlqr approved these changes

2024-08-26 11:36 UTC, merged