issue-1657: support expand volume in CSI Driver
ydb-platform/nbs pull request #1748
Opened 2024-08-07 17:24 UTC by antonmyagkov

2024-09-02 08:40 UTC, dvrazumov requested changes

2024-09-02 08:40 UTC, dvrazumov commented on cloud/blockstore/tools/csi_driver/internal/driver/node.go
> +	volumeInfo, ok := s.volumeMap[req.VolumeId]
Получается, после перезагрузки драйвера (например, при обновлении или падении), мапа `volumeMap` обнулится и мы не сможем изменить размер вольюма?

2024-09-02 08:40 UTC, dvrazumov commented on cloud/blockstore/tools/csi_driver/internal/driver/node.go
> +	newBlocksCount := uint64(req.CapacityRange.RequiredBytes) / uint64(resp.Volume.BlockSize)
Может Ceil добавить? Иначе выделяется <= чем нужно

2024-09-02 08:40 UTC, dvrazumov commented on cloud/blockstore/tools/csi_driver/internal/driver/node.go
> +	_, err = s.nbsClient.ResizeVolume(ctx, &nbsapi.TResizeVolumeRequest{
Может добавим проверку, что `newBlocksCount > resp.Volume.BlocksCount`? И что будет, если `newBlocksCount == resp.Volume.BlocksCount`?

2024-09-02 08:40 UTC, dvrazumov commented on cloud/blockstore/tests/csi_driver/test.py
> +        assert bytes_usage["total"] // 1000 ** 3 == 2
А почему здесь 1000, не 1024? И почему нельзя написать строгое равенство bytes_usage["total"] == 2 * volume_size?

2024-09-02 11:07 UTC, antonmyagkov commented on cloud/blockstore/tests/csi_driver/test.py
> +        assert bytes_usage["total"] // 1000 ** 3 == 2
volumestats использует внутри statfs: https://github.com/ydb-platform/nbs/blob/main/cloud/blockstore/tools/csi_driver/internal/driver/node.go#L744

total - это количество data blocks * block size. Это значение меньше чем размер nbd девайса в байтах.

2024-09-02 11:09 UTC, antonmyagkov commented on cloud/blockstore/tools/csi_driver/internal/driver/node.go
> +	volumeInfo, ok := s.volumeMap[req.VolumeId]
Ты прав. После перезагрузки драйвера PublishVolume не вызывается повторно.

Удалил мапу, теперь получаем nbdDeviceFile через ListEndpoints

2024-09-02 11:14 UTC, antonmyagkov commented on cloud/blockstore/tools/csi_driver/internal/driver/node.go
> +	_, err = s.nbsClient.ResizeVolume(ctx, &nbsapi.TResizeVolumeRequest{
Я решил не проверять этот случай потому что:
1. Через kubectl apply pvc невозможно уменьшить размер volume.
2. kubectl apply pvc не применяется если размер pvc такой же
3. csi-sanity тесты тоже не содержат кейса с уменьшением размера volume

2024-09-02 13:06 UTC, antonmyagkov commented on cloud/blockstore/tools/csi_driver/internal/driver/node.go
> +	_, err = s.nbsClient.ResizeVolume(ctx, &nbsapi.TResizeVolumeRequest{
Добавил проверку

2024-09-02 15:27 UTC, antonmyagkov commented on cloud/blockstore/tools/csi_driver/internal/driver/node.go
> +	newBlocksCount := uint64(req.CapacityRange.RequiredBytes) / uint64(resp.Volume.BlockSize)
Done

2024-09-04 09:24 UTC, dvrazumov approved these changes

2024-09-04 09:56 UTC, qkrorlqr commented on cloud/blockstore/public/sdk/go/client/grpc.go
> +func (client *grpcClient) ResizeDevice(
у нас уже есть ResizeVolume

2024-09-04 10:01 UTC, qkrorlqr commented on cloud/blockstore/public/sdk/go/client/grpc.go
> +func (client *grpcClient) ResizeDevice(
И вообще, возможно, переиспользовать тут https://github.com/ydb-platform/nbs/blob/79cae7ae96d5131c88940f8062e15d862018247f/cloud/blockstore/public/api/protos/endpoints.proto#L217, т.к. RefreshEndpoint мы как раз и делали для того, чтобы дотащить до эндпоинта и до ВМ-ки информацию о том, что размер Volume за эндпоинтом изменился

2024-09-04 10:21 UTC, gy2411 approved these changes

2024-09-04 12:20 UTC, antonmyagkov commented on cloud/blockstore/public/sdk/go/client/grpc.go
> +func (client *grpcClient) ResizeDevice(
Ок. Добавил ссылку на этот тред в тикет. Попробую переделать.

2024-09-04 12:21 UTC, merged