Remove .yandex_meta
ydb-platform/nbs pull request #1783
Opened 2024-08-13 03:45 UTC by drbasic

2024-08-13 07:44 UTC, tpashkin commented
А давай сразу выпилим из ya.make файлов?

```
nbs % grep yandex_meta contrib/libs/libcap/ya.make
LICENSE_TEXTS(.yandex_meta/licenses.list.txt)
```

2024-08-13 07:55 UTC, tpashkin approved these changes

2024-08-13 08:00 UTC, tpashkin requested changes
Так не получится, совсем без LICENSE_TEXTS ya make поперхнётся. Нужно заменить на локальный файл лицензии

```
libcap % ya make
Error[-WPluginErr]: in $B/contrib/libs/libcap/libcontrib-libs-libcap.a: License texts not found. See https://st.yandex-team.ru/DTCC-324
Configure error (use -k to proceed)
```

2024-08-13 11:34 UTC, tpashkin commented
> Так не получится, совсем без LICENSE_TEXTS ya make поперхнётся. Нужно заменить на локальный файл лицензии
> 
> ```
> libcap % ya make
> Error[-WPluginErr]: in $B/contrib/libs/libcap/libcontrib-libs-libcap.a: License texts not found. See https://st.yandex-team.ru/DTCC-324
> Configure error (use -k to proceed)
> ```

Хотя любопытно, что build прошёл 🤔

2024-08-16 07:21 UTC, tpashkin approved these changes

2024-08-16 07:23 UTC, Sazonov99 approved these changes

2024-08-16 07:31 UTC, merged