Stat about opened files from one/many sessions
ydb-platform/nbs pull request #1818
Opened 2024-08-19 14:43 UTC by proller

2024-08-19 16:17 UTC, debnatkh commented on cloud/filestore/libs/storage/tablet/tablet_state_sessions.cpp
> +        DecrementNodesWriteMultiSessionCount(db);
Не уверен, что статистику эту нужно персистентно хранить – если вместо этого хранить это где-то в памяти, то от db можно избавиться

2024-08-19 16:17 UTC, debnatkh commented on cloud/filestore/libs/storage/tablet/tablet_state_sessions.cpp
> +    auto& nodeStat = Impl->NodeToSessionStat[handle->nodeid()];
->NodeId()

2024-08-20 17:51 UTC, debnatkh commented on cloud/filestore/libs/storage/tablet/tablet_state.cpp
> +        return {};
EStatField::None

2024-08-20 17:51 UTC, debnatkh commented on cloud/filestore/libs/storage/tablet/tablet_state.cpp
> +    return {};
Тут None, навеное, не очень корректно отдавать?

2024-08-20 17:51 UTC, debnatkh commented on cloud/filestore/libs/storage/tablet/tablet_state.h
> +        THashMap<TString, THashSet<ui64>> ReadSessionToHandle;
значением здесь же может быть просто количество хендлов?

2024-08-20 17:51 UTC, debnatkh commented on cloud/filestore/libs/storage/tablet/tablet_state_sessions.cpp
> +    if (field == TNodeToSessionStat::EStatField::NodesWriteMultiSessionCount) {
Тут switch case может поаккуратнее бы был?

2024-08-21 14:01 UTC, debnatkh commented on cloud/filestore/libs/storage/tablet/tablet_ut_nodes.cpp
> +    Y_UNIT_TEST(StatOpenedFiles)
ShouldStatOpenedFiles

2024-08-21 22:31 UTC, proller commented on cloud/filestore/libs/storage/tablet/tablet_state.h
> +        THashMap<TString, i64> ReadSessions;
u сделает проблему если удалить handle без создания

2024-08-23 16:41 UTC, qkrorlqr requested changes

2024-08-23 16:41 UTC, qkrorlqr commented on cloud/filestore/libs/storage/tablet/protos/tablet.proto
> +    uint64 NodesWriteMultiSessionCount  = 213;
давай отступы сделаем аналогично остальным полям - в остальных полях нет выравнивания отступа перед "="

2024-08-23 16:41 UTC, qkrorlqr commented on cloud/filestore/libs/storage/tablet/tablet_actor.h
> +        std::atomic<i64> NodesWriteSingleSessionCount{0};
так, может, назовем прямым текстом - NodesOpenForWritingBySingleSession, NodesOpenForWritingByMultipleSessions, NodesOpenForReadingBySingleSession, NodesOpenForReadingByMultipleSessions?

2024-08-23 16:41 UTC, qkrorlqr commented on cloud/filestore/libs/storage/tablet/tablet_state.cpp
> +    if (nodeStat.WriteSessions.contains(sessionId) &&
аж 3 лукапа - зачем? код это не упрощает
```
{
    auto it = nodeStat.WriteSessions.find(sessionId);
    if (it != nodeStat.WriteSessions.end() && it->second <= 0) {
        nodeStat.WriteSessions.erase(it);
    }
}
```

для read аналогично

2024-08-23 16:41 UTC, qkrorlqr commented on cloud/filestore/libs/storage/tablet/tablet_state.cpp
> +    if (!Stat.contains(nodeId)) {
нет смысла передавать nodeId и потом делать проверку на contains и далее еще и лукап - когда ты вызываешь Clean, у тебя всегда на руках есть итератор на элемент хэштаблицы Stat - можно его сразу и передать

2024-08-23 16:41 UTC, qkrorlqr commented on cloud/filestore/libs/storage/tablet/tablet_state_sessions.cpp
> +                1));
что-то какой-то странный Reset - он же не в 0 сбрасывает, а декрементит на единицу просто
давай назовем DecrementNodeCounters
и вместо UpdateNodeCounters - IncrementNodeCounters

2024-08-23 16:41 UTC, qkrorlqr commented on cloud/filestore/libs/storage/tablet/tablet_state_sessions.cpp
> +            FileSystemStats.SetNodesWriteSingleSessionCount(SafeDecrement(
не надо SafeDecrement - он делает abort в случае, если декремент сделать не получилось, то есть его имеет смысл использовать для каких-то метрик, критичных для корректности работы ФС (да и в этом случае тоже не очень хорошо)

тут корректность данных метрик для работы ФС не критична, так что лучше сделать abort в дебаге, а в релизном билде пусть не падает, если значение получается < 0, а просто сетит 0

2024-08-23 16:41 UTC, qkrorlqr commented on cloud/filestore/libs/storage/tablet/tablet_state_sessions.cpp
> +        UpdateNodeCounters(
это некорректный код - он меняет счетчики только в памяти
у нас специально сделаны TIndexTabletState::{Set,Increment,Decrement}{$CounterName}(TIndexTabletDatabase& db, ...) методы, которые меняют стейт не только в памяти, но еще и применяют изменение в LSM-базе таблетки

2024-08-23 16:41 UTC, qkrorlqr commented on cloud/filestore/libs/storage/tablet/tablet_ut_nodes.cpp
> +        const auto countersValidate =
при фейле UNIT_ASSERT-а в качестве строчки будет указана строчка в этой ф-ции и будет непонятно, в какой из валидаций мы упали

поэтому лучше валидационный хелпер макросом оформить

2024-08-23 16:41 UTC, qkrorlqr commented on cloud/filestore/private/api/protos/tablet.proto
> +    uint64 NodesWriteMultiSessionCount  = 115;
отступы надо сделать аналогично соседним полям

2024-08-26 12:57 UTC, qkrorlqr commented on cloud/filestore/libs/storage/tablet/tablet_state.h
> +};
надо добавить пустую строку перед отбивкой, а также перед классом нужна отбивка

2024-08-29 12:17 UTC, qkrorlqr commented on cloud/filestore/libs/storage/tablet/model/node_session_stat.h
> +#include "util/generic/hash.h"
для абсолютных инклюдов используем <> (как в аркадии)

2024-08-29 14:26 UTC, qkrorlqr approved these changes

2024-08-30 19:22 UTC, yegorskii approved these changes

2024-08-31 16:06 UTC, merged

2024-09-01 12:25 UTC, drbasic commented on cloud/filestore/libs/storage/tablet/model/node_session_stat.h
> +        THashMap<TString, i32> ReadSessions;
почему счетчик знаковый?