[Filestore] Implement throttling for DescribeData and GenerateBlobIds requests
ydb-platform/nbs pull request #1838
Opened 2024-08-21 22:33 UTC by proller

https://github.com/ydb-platform/nbs/issues/1709

2024-08-23 16:09 UTC, qkrorlqr reviewed
Нужны ut

2024-08-23 16:09 UTC, qkrorlqr commented on cloud/filestore/libs/storage/service/service_actor_writedata.cpp
> +            WriteRequest.MutableHeaders()->SetThrottled(true);
так а зачем тут - WriteData fallback же может вызываться в том числе в ответ на ошибку GenerateBlobIds и ошибку AddData

давай выставим этот флаг прямо внутри ф-ции WriteData(...)
и давай лучше назовем флаг ThrottlingDisabled (по аналогии с похожим флагом в blockstore)

2024-08-23 16:09 UTC, qkrorlqr commented on cloud/filestore/libs/storage/service/service_actor_readdata.cpp
> +        ReadRequest.MutableHeaders()->SetThrottled(true);
давай выставим флаг в ф-ции ReadData(...)

2024-08-28 10:58 UTC, qkrorlqr requested changes
и давай все-таки ut добавим

2024-09-11 19:37 UTC, qkrorlqr submitted a review, later dismissed

2024-09-12 13:25 UTC, qkrorlqr approved these changes

2024-09-12 14:07 UTC, yegorskii approved these changes

2024-09-13 19:26 UTC, merged