NBS-179: support using multiple devices from the same rdma endpoint
ydb-platform/nbs pull request #185
Opened 2024-01-19 17:09 UTC by budevg

2024-01-19 17:27 UTC, tpashkin approved these changes

2024-01-22 12:23 UTC, drbasic requested changes

2024-01-22 12:23 UTC, drbasic commented on cloud/blockstore/libs/service_local/storage_rdma.cpp
> -            return std::tie(Host, Port) < std::tie(other.Host, other.Port);
Жду написания теста на эту машинерию

2024-01-23 06:17 UTC, drbasic approved these changes

2024-01-23 09:13 UTC, tpashkin approved these changes

2024-01-23 09:15 UTC, merged