[Disk Manager] better YDB client errors metric
ydb-platform/nbs pull request #1853
Opened 2024-08-23 14:11 UTC by Rattysed

[#1744 ](https://github.com/ydb-platform/nbs/issues/1744)

2024-08-23 18:10 UTC, SvartMetal commented on cloud/tasks/persistence/ydb.go
> +		fmt.Sprintf("At path: %v", fullPath),
at path %q

2024-08-23 18:10 UTC, SvartMetal commented on cloud/tasks/persistence/ydb.go
> +		fmt.Sprintf("At path: %v", fullPath),
at path %q

2024-08-23 18:11 UTC, SvartMetal commented on cloud/tasks/persistence/ydb.go
> +		func(ctx context.Context, s *Session) (err error) {
здесь не нужен именованный return arg

2024-08-23 18:11 UTC, SvartMetal commented on cloud/tasks/persistence/ydb.go
> +		"client/MakeDirs",
client/makeDirs

2024-08-23 18:11 UTC, SvartMetal commented on cloud/tasks/persistence/ydb.go
> +		fmt.Sprintf("At path: %v", absolutePath),
at path %q

2024-08-29 14:50 UTC, Rattysed commented on cloud/tasks/persistence/ydb_metrics.go
> +				errorCounter = errorRegistry.Counter("error")
"error" а не "errors", т.к. если назвать Counter одинаково с разными тегами, произойдет паника
https://github.com/temporalio/sdk-go/issues/1450

2024-08-29 15:47 UTC, Rattysed commented on cloud/tasks/persistence/ydb_metrics.go
> +				errorType = "unhandled"
Нет возможности сделать одновременно счётчик без тега и с тегом. Это приводит к панике. Похожая ситуация есть тут https://github.com/temporalio/sdk-go/issues/1450

2024-08-29 17:54 UTC, BarkovBG approved these changes

2024-08-30 09:25 UTC, SvartMetal commented on cloud/tasks/persistence/ydb_metrics.go
> +				errorType = "unhandled"
unhandled -> unknown

2024-08-30 13:21 UTC, jkuradobery requested changes

2024-08-30 13:21 UTC, jkuradobery commented on cloud/tasks/persistence/ydb_test.go
> +) (*YDBClient, error) {
Тебе не нужно добавлять этот параметр. db.metrics ты можешь использовать потому что тест лежит в том же пакете что и ydb.go.

2024-08-30 13:21 UTC, jkuradobery commented on cloud/tasks/persistence/ydb_test.go
> +	folder := fmt.Sprintf("ydb_test/%v/%v", extraLargeString, t.Name())
Зачем %v/%v? %s будет достаточно, все строки же.

2024-08-30 13:40 UTC, Rattysed commented on cloud/tasks/persistence/ydb_test.go
> +	folder := fmt.Sprintf("ydb_test/%v/%v", extraLargeString, t.Name())
А между ними есть существенная разница?

2024-08-30 14:05 UTC, SvartMetal approved these changes

2024-08-30 14:59 UTC, BarkovBG approved these changes

2024-08-30 15:00 UTC, jkuradobery approved these changes

2024-08-30 19:51 UTC, SvartMetal commented
Надо посмотреть почему упал тест https://github-actions-s3.website.nemax.nebius.cloud/ydb-platform/nbs/PR-check/10634880274/1/nebius-x86-64/summary/ya-test.html#FAIL

2024-08-30 19:51 UTC, SvartMetal commented on cloud/tasks/persistence/ydb.go
Надо посмотреть почему упал тест https://github-actions-s3.website.nemax.nebius.cloud/ydb-platform/nbs/PR-check/10634880274/1/nebius-x86-64/summary/ya-test.html#FAIL

2024-08-30 19:59 UTC, Rattysed commented on cloud/tasks/persistence/ydb.go
Уже смотрю, не могу пока что ошибку локально повторить

2024-09-02 21:43 UTC, merged