fix ydb sync, arc pr 6551995
ydb-platform/nbs pull request #1857
Opened 2024-08-23 15:36 UTC by rekby

2024-08-24 12:18 UTC, qkrorlqr requested changes
А это зачем? Речь про какой синк?

2024-08-26 07:44 UTC, rekby commented
> А это зачем? Речь про какой синк?
@qkrorlqr 

Привет, речь про синк YDB из github в аркадию. Мы удалили у себя в конструкторе Daemon'а [параметр stdin_file](https://github.com/ydb-platform/ydb/pull/7185/files#diff-eafbdabef2a0b065a1ebec005af79e85afb4262b807161105d5c2bb3e9d71d8dL62), т.к. по факту он не используется. В этом коммите удаляется использование уже несуществующего параметра.

 коммит уже проверен в аркадии на PR 6551995

2024-08-26 09:33 UTC, qkrorlqr commented on cloud/filestore/tests/python/lib/client.py
> +        files.pop('stdin_file', None)
это костыли какие-то, почему бы просто не поправить тут https://github.com/ydb-platform/nbs/blob/b4d83e4447bd186d83a7807560f209f58576a9e9/cloud/filestore/tests/python/lib/common.py#L37 ?

2024-08-26 10:20 UTC, rekby commented on cloud/filestore/tests/python/lib/client.py
> +        files.pop('stdin_file', None)
@qkrorlqr можно и тут, если функция больше нигде не используется.
в Python это не всегда можно определить точно, поэтому я воспользовался более безопасным вариантом.

Поправить?

2024-08-26 10:24 UTC, qkrorlqr commented on cloud/filestore/tests/python/lib/client.py
> +        files.pop('stdin_file', None)
> в Python это не всегда можно определить точно, поэтому я воспользовался более безопасным вариантом.

ну, поиском по коду вполне однозначно находятся ровно 3 места использования - и это как раз те места, которые ты правишь

да, поправить

2024-08-27 19:12 UTC, qkrorlqr approved these changes

2024-08-28 08:46 UTC, EvgeniyKozev approved these changes

2024-08-28 09:01 UTC, merged