moved parameters for registration from server to storage config + added registration tests for nbs
ydb-platform/nbs pull request #1859
Opened 2024-08-23 17:00 UTC by yegorskii

2024-08-26 17:35 UTC, qkrorlqr requested changes

2024-08-26 17:35 UTC, qkrorlqr commented on cloud/blockstore/libs/daemon/ydb/bootstrap.cpp
> +        .NodeType = Configs->StorageConfig->GetNodeType(),
слово "deprecated" НЕ означает "нахер выпилил использование", а означает "параметр все еще используется, но планируется к удалению, так что лучше его перестать использовать в пользу чего-то еще"

2024-09-01 11:41 UTC, qkrorlqr commented on cloud/blockstore/libs/daemon/ydb/config_initializer.cpp
> +        storageConfig.SetDisableManuallyPreemptedVolumesTracking(true);
это вроде нерелевантно данному PR?

2024-09-01 11:41 UTC, qkrorlqr commented on cloud/blockstore/libs/daemon/ydb/config_initializer.cpp
>  void TConfigInitializerYdb::ApplyCustomCMSConfigs(const NKikimrConfig::TAppConfig& config)
мм, что-то не понимаю, как правки в логике загрузки конфигов из CMS сюда попали

2024-09-01 11:41 UTC, qkrorlqr commented on cloud/blockstore/libs/disk_agent/config_initializer.cpp
> +void TConfigInitializer::AdaptNodeRegistrationParams(
копипаста?

2024-09-01 11:41 UTC, qkrorlqr commented on cloud/blockstore/libs/storage/core/config.cpp
> +
лишняя пустая строка

2024-09-01 11:41 UTC, qkrorlqr commented on cloud/filestore/libs/storage/core/config.cpp
> +    xxx(NodeRegistrationErrorTimeout,        TDuration, TDuration::Seconds(1) )\
а серт добавишь отдельным PR?

2024-09-02 08:18 UTC, yegorskii commented on cloud/filestore/libs/storage/core/config.cpp
> +    xxx(NodeRegistrationErrorTimeout,        TDuration, TDuration::Seconds(1) )\
Он там уже давно есть https://github.com/ydb-platform/nbs/blob/main/cloud/filestore/libs/storage/core/config.cpp#L176

2024-09-02 08:20 UTC, yegorskii commented on cloud/blockstore/libs/disk_agent/config_initializer.cpp
> +void TConfigInitializer::AdaptNodeRegistrationParams(
По факту да. У нас почему-то диск агент лежит отдельно от blockstore (не в libs/daemon). По-хорошему надо бы порефакторить, но не в этом пр, он и так уже большой

2024-09-02 08:23 UTC, yegorskii commented on cloud/blockstore/libs/daemon/ydb/config_initializer.cpp
>  void TConfigInitializerYdb::ApplyCustomCMSConfigs(const NKikimrConfig::TAppConfig& config)
Мне нужно было сериализвать загрузку ServerConfig и StorageConfig (ServerConfig должен загрузиться раньше StorageConfig чтобы подтянуть параметры регистрации). Поэтому и пришлось здесь код поправить

2024-09-02 08:25 UTC, yegorskii commented on cloud/blockstore/libs/daemon/ydb/config_initializer.cpp
> +        storageConfig.SetDisableManuallyPreemptedVolumesTracking(true);
Ну просто в глаза бросилось что при загрузке из cms код отличается от того что происходит при загрузке из конфигов. Хотя кажется в обоих случаях результат должен быть одинаковым

2024-09-02 09:49 UTC, qkrorlqr commented on cloud/blockstore/libs/disk_agent/config_initializer.cpp
> +void TConfigInitializer::AdaptNodeRegistrationParams(
заведи, пожалуйста, issue на себя про рефакторинг

2024-09-03 20:59 UTC, yegorskii commented on cloud/blockstore/libs/disk_agent/config_initializer.cpp
> +void TConfigInitializer::AdaptNodeRegistrationParams(
https://github.com/ydb-platform/nbs/issues/1946

2024-09-04 09:33 UTC, qkrorlqr approved these changes

2024-09-04 13:28 UTC, EvgeniyKozev approved these changes

2024-09-04 13:30 UTC, merged