issue-176: encryption operations should return TError
ydb-platform/nbs pull request #1908
Opened 2024-08-29 20:42 UTC by sharpeye

2024-08-30 10:49 UTC, drbasic requested changes

2024-08-30 10:49 UTC, drbasic commented on cloud/blockstore/libs/encryption/encryptor.cpp
> +        if (!EVP_EncryptInit_ex(ctx.get(), EVP_aes_128_xts(), nullptr, Key, iv)) {
тут и ниже было сравнение с 1

2024-08-30 10:54 UTC, sharpeye commented on cloud/blockstore/libs/encryption/encryptor.cpp
> +        if (!EVP_EncryptInit_ex(ctx.get(), EVP_aes_128_xts(), nullptr, Key, iv)) {
Функции из openssl в случае успеха возвращают 1, а в случае неудачи - 0. https://docs.openssl.org/3.0/man3/EVP_EncryptInit/#examples

2024-08-30 11:02 UTC, drbasic approved these changes

2024-08-30 17:42 UTC, tpashkin commented on cloud/blockstore/libs/encryption/encryptor.cpp
> +            return MakeError(
Кажется, здесь можно было бы использовать `MakeDifferentSizesError`

2024-09-01 16:40 UTC, drbasic approved these changes

2024-09-02 09:12 UTC, tpashkin approved these changes

2024-09-02 09:52 UTC, merged