issue-652: add test reproducing the error
ydb-platform/nbs pull request #1919
Opened 2024-08-30 15:36 UTC by debnatkh

2024-09-11 17:40 UTC, qkrorlqr approved these changes

2024-09-11 17:51 UTC, qkrorlqr requested changes
Хотя нет, unship, теперь у нас FlushBytes начинает отличаться от Compaction. Compaction генерирует CommitId один раз и использует его как для своих dstBlobs, так и для установки барьера. Не хочется, чтобы FlushBytes отличался от Compaction в этом месте, т.к. по своей сути он делает то же самое, что и Compaction.

2024-09-12 15:39 UTC, debnatkh commented on cloud/filestore/libs/storage/tablet/tablet_actor_flush_bytes.cpp
> -    }
К переменной CollectCommitId нет обращений до 800 строки

2024-09-12 17:09 UTC, qkrorlqr commented on cloud/filestore/libs/storage/tablet/tablet_actor_flush_bytes.cpp
> +    // prepare stage, may be tempered with by the time of the transaction
tampered with

2024-09-12 17:09 UTC, qkrorlqr commented on cloud/filestore/libs/storage/tablet/tablet_actor_flush_bytes.cpp
> +    args.CollectCommitId = GenerateCommitId();
давай назовем просто args.CommitId

2024-09-12 19:20 UTC, qkrorlqr approved these changes

2024-09-16 11:32 UTC, yegorskii approved these changes

2024-09-16 11:40 UTC, merged