Harmonize MaxRequestSize with minimum value
ydb-platform/nbs pull request #2082
Opened 2024-09-20 05:05 UTC by drbasic

2024-09-22 09:03 UTC, budevg requested changes

2024-09-23 05:27 UTC, drbasic commented on cloud/blockstore/libs/rdma/iface/client.h
> +    ui32 MaxBufferSize = 4_MB + 4_KB;
4198400 = 4096 * 1024 + 4096

2024-09-23 05:42 UTC, budevg approved these changes

2024-09-23 08:26 UTC, komarevtsev-d approved these changes

2024-09-23 08:31 UTC, merged