[Filestore] Implement a tool which replays filestore-vhost's profile log
ydb-platform/nbs pull request #2124
Opened 2024-09-25 00:06 UTC by proller

https://github.com/ydb-platform/nbs/issues/1733

2024-10-03 19:03 UTC, debnatkh commented on cloud/filestore/tools/testing/loadtest/lib/request_replay.h
> +            FileSystemId = TString{EventLogMessagePtr->GetFileSystemId()};
Нужно сообщение в логе, что FileSystemId выставлен. Не хватает фильтрации на случай, если FileSystemId не совпадает

2024-10-03 19:03 UTC, debnatkh commented on cloud/filestore/tools/testing/loadtest/lib/request_replay.h
> +        }
Тут тоже надо выфильтровывать по FileSystemId, кажется

2024-10-04 14:17 UTC, proller commented on cloud/filestore/tools/testing/loadtest/lib/request_replay.h
> +        }
Для фильтрации надо еще одну переменную иметь -
для возможности чтения лога с одним id и записи по grpc в другой id

2024-10-09 14:38 UTC, debnatkh commented on cloud/filestore/tools/testing/loadtest/protos/loadtest.proto
> +    double TimeScale = 7;
Для 4-10 пунктов, наверное, нужны пояснения 

По аналогии с нашими другими протобуфами: https://github.com/ydb-platform/nbs/blob/main/cloud/blockstore/tools/testing/loadtest/protos/loadtest.proto#L167-L190

2024-10-09 14:38 UTC, debnatkh commented on cloud/filestore/tools/testing/loadtest/lib/ya.make
> +    library/cpp/testing/unittest
Это не нужно почти точно

2024-10-09 14:38 UTC, debnatkh commented on cloud/filestore/tools/testing/loadtest/lib/test.cpp
> +            if (request->Stop) {
Stopped/IsStopped?

2024-10-09 14:38 UTC, debnatkh commented on cloud/filestore/tools/testing/loadtest/lib/test.cpp
> +                    request->Action,
request->Action – не int же? `request->Action.DebugString().Quote.c_str()`

2024-10-09 14:38 UTC, debnatkh commented on cloud/filestore/tools/testing/loadtest/lib/request.h
>      virtual TInstant NextRequestAt() = 0;
Поправь меня, если я ошибаюсь, но NextRequestAt нигде, кажется, не используется

2024-10-09 14:38 UTC, debnatkh commented on cloud/filestore/tools/testing/loadtest/lib/request_replay.cpp
> +IReplayRequestGenerator::IReplayRequestGenerator(
newline + отбивка

2024-10-09 14:38 UTC, debnatkh commented on cloud/filestore/tools/testing/loadtest/lib/request_replay.cpp
> +    options.SetForceStrongOrdering(true);   // need this?
А зачем это нужно?

2024-10-09 14:38 UTC, debnatkh commented on cloud/filestore/tools/testing/loadtest/lib/request_replay_fs.cpp
> +                STORAGE_ERROR(
Тут и во всём остальном логгинге предлагаю юзать format string

2024-10-09 15:43 UTC, proller commented on cloud/filestore/tools/testing/loadtest/lib/request.h
>      TDuration Elapsed;
так {} поставит первое, ACTION_CREATE_NODE - вроде подходит?

2024-10-09 16:00 UTC, proller commented on cloud/filestore/tools/testing/loadtest/lib/request.h
>      TDuration Elapsed;
Использоваться оно будет только для сообщения stop - где не важны все  остальные поля, инициализация только чтоб не случайное

2024-10-10 18:22 UTC, debnatkh commented on cloud/filestore/tools/testing/loadtest/lib/request_replay_fs.cpp
> +    TString PathByNode(TNodeLocal nodeid)
`util/folder/path.h` 
TFsPath вместо TString?

2024-10-10 18:22 UTC, debnatkh commented on cloud/filestore/tools/testing/loadtest/lib/request_replay_fs.cpp
> +            } break;
break вовнутрь {} по аналогии с остальным проектом бы унести

2024-10-10 18:22 UTC, debnatkh commented on cloud/filestore/tools/testing/loadtest/lib/request_replay_fs.cpp
> +        auto fullName = Spec.GetReplayRoot() + "/" + PathByNode(parentNode) +
Если юзать TFsPath, то можно operator/

2024-10-10 18:22 UTC, debnatkh commented on cloud/filestore/tools/testing/loadtest/lib/request_replay_fs.cpp
> +                                     << logHandle)));   // todo
Напиши, плиз ,поподробнее, что тут TODO, если не сложно

2024-10-10 18:22 UTC, debnatkh commented on cloud/filestore/tools/testing/loadtest/lib/request_replay_fs.cpp
> +        NProto::THeaders headers)
tab

2024-10-10 18:22 UTC, debnatkh commented on cloud/filestore/tools/testing/loadtest/lib/request_replay_fs.cpp
> +        TString Path;
Unused

2024-10-10 18:33 UTC, debnatkh commented on cloud/filestore/tools/testing/loadtest/lib/request_replay_fs.cpp
> +    std::atomic<ui64> LastRequestId = 0;
unused

2024-10-10 18:33 UTC, debnatkh commented on cloud/filestore/tools/testing/loadtest/lib/request_replay_fs.cpp
> +                    MakeError(E_IO, TStringBuilder{} << "nothing writed"));
written

2024-10-10 18:33 UTC, debnatkh commented on cloud/filestore/tools/testing/loadtest/lib/request_replay_fs.cpp
> +        return 0;
InvalidNodeId

2024-10-10 18:33 UTC, debnatkh commented on cloud/filestore/tools/testing/loadtest/lib/request_replay_fs.cpp
> +        return 0;
InvalidHandle

2024-10-11 18:45 UTC, debnatkh commented on cloud/filestore/tools/testing/loadtest/lib/request.h
> +    TCompletedRequest(bool stop) noexcept
Договорились сделать так, что ExecuteNextRequest может ыозвращать optional/пустую future, чтобы сигнализировать о том, что исполнение завершилось. Надо описать про это в описании интерфейса ExecuteNextRequest, а то сходу непонятно. 

И в test.cpp написать типа

```
        const auto future = RequestGenerator->ExecuteNextRequest();
        if (!future) { ... }
        future.Apply(
            [=](const TFuture<TCompletedRequest>& future)
```

2024-10-11 18:45 UTC, debnatkh commented on cloud/filestore/tools/testing/loadtest/lib/request.h
> +    virtual bool ShouldImmediatelyProcessQueue()
Нужен комментарий про то, что имеется ввиду. Со следующим параметром интерфейса вопросов нет – он понятен, а тут надо вчитываться в код, чтобы понять

2024-10-11 18:45 UTC, debnatkh commented on cloud/filestore/tools/testing/loadtest/lib/request_replay.cpp
> +            STORAGE_DEBUG("Skipped event with FileSystemId=" << fileSystemId);
Для консистентности со следующей строчкой логирования может тут тоже format string?

2024-10-11 18:45 UTC, debnatkh commented on cloud/filestore/tools/testing/loadtest/lib/request_replay.cpp
> +                ToString(request.AsJSON()).c_str());
А зачем json? Может просто (DebugString/ShortDebugString).Quote().c_str()?

2024-10-11 18:45 UTC, debnatkh commented on cloud/filestore/tools/testing/loadtest/lib/request_replay.cpp
> +                const auto& action = request.GetRequestType();
Логику в {} может лучше в отдельную функцию, чтобы эта не разбухала?

2024-10-11 18:45 UTC, debnatkh commented on cloud/filestore/tools/testing/loadtest/lib/request_replay.h
> +    TString TargetFilesystemId;   // Only for GRPC
TargetFilesystemId вообще тогда в этом PR не нужен же?

2024-10-11 18:45 UTC, debnatkh commented on cloud/filestore/tools/testing/loadtest/protos/loadtest.proto
> +    string FileSystemIdFilter = 3;
Тут тоже комментарий нужен, потому что это то, что отличается с другими спеками

2024-10-11 18:45 UTC, debnatkh commented on cloud/filestore/tools/testing/loadtest/protos/loadtest.proto
> +    bool NoRead = 4;
Тогда уж SkipRead/SkipWrite?

2024-10-11 18:45 UTC, debnatkh commented on cloud/filestore/tools/testing/loadtest/protos/loadtest.proto
> +    bool WriteEmpty = 9;
bool WriteRandom = 8;
    bool WriteEmpty = 9;

Это не enum?

2024-10-17 19:39 UTC, debnatkh commented on cloud/filestore/tools/testing/loadtest/lib/request_replay_fs.cpp
> +    // Relative to local root path of node. Dirs ends with /
А, ну и если мы договорились заменить на TFsPath, то необходимости в этом предложении нет

2024-10-17 19:39 UTC, debnatkh commented on cloud/filestore/tools/testing/loadtest/lib/request_replay_fs.cpp
> +              std::move(filesystemId),
лишние табы

2024-10-17 19:39 UTC, debnatkh commented on cloud/filestore/tools/testing/loadtest/lib/request_replay_fs.cpp
> +    TNodeLocal NodeIdMapped(const TNodeLog id)
GetLocalNodeBy....

2024-10-17 19:39 UTC, debnatkh commented on cloud/filestore/tools/testing/loadtest/lib/request_replay_fs.cpp
> +    THandleLocal HandleIdMapped(const THandleLog id)
same

2024-10-17 19:39 UTC, debnatkh commented on cloud/filestore/tools/testing/loadtest/lib/request_replay_fs.cpp
> +                MakeError(E_PRECONDITION_FAILED, "disabled")});
Не надо фейлить – надо игнорить. Тут и везде ниже

2024-10-17 19:39 UTC, debnatkh commented on cloud/filestore/tools/testing/loadtest/lib/request_replay_fs.cpp
> +                MakeError(E_PRECONDITION_FAILED, "disabled")});
А, ну и логгировать

2024-10-17 19:39 UTC, debnatkh commented on cloud/filestore/tools/testing/loadtest/lib/request_replay_fs.cpp
> +                MakeError(E_FAIL, "cancelled")});
Содержательное сообщение об ошибке

2024-10-17 19:39 UTC, debnatkh commented on cloud/filestore/tools/testing/loadtest/lib/request_replay_fs.cpp
> +    TNodeLocal CreateDirIfMissingByNodeLog(TNodeLog nodeIdLog)
Нужно чуть более содержательное описание того, что делает функция. Тогда будет понятно, о чём комментарий

2024-10-17 19:39 UTC, debnatkh commented on cloud/filestore/tools/testing/loadtest/lib/request_replay_fs.cpp
> +        if (const auto& nodeIdLocal = NodeIdMapped(nodeIdLog);
то же про вынос определения вне условия. Понятно, что это работает, но всё-таки требуется бОльшая mental capacity для этого. Это скорее нетривиальная синтаксическая конструкция

2024-10-17 19:39 UTC, debnatkh commented on cloud/filestore/tools/testing/loadtest/lib/request_replay_fs.cpp
> +            return 0;
Правильно я понимаю, что тут идея в том, что траверс по дереву вверх закончен? 

надо возвращать InvalidNodeIde

2024-10-17 19:39 UTC, debnatkh commented on cloud/filestore/tools/testing/loadtest/lib/request_replay_fs.cpp
> +        if (parent == InvalidNodeId && it->second.ParentLog &&
&& it->second.ParentLog != InvalidNodeId

2024-10-17 19:39 UTC, debnatkh commented on cloud/filestore/tools/testing/loadtest/lib/request_replay_fs.cpp
> +            nodeIdLog != it->second.ParentLog)
В каком случае может быть `nodeIdLog == it->second.ParentLog`?

2024-10-17 19:39 UTC, debnatkh commented on cloud/filestore/tools/testing/loadtest/lib/request_replay_fs.cpp
> +
Тут не нужна проверка на то, что parent не Invalid?

2024-10-17 19:39 UTC, debnatkh commented on cloud/filestore/tools/testing/loadtest/lib/request_replay_fs.cpp
> +                (it->second.Name.empty() ? "_nodeid_" + ToString(nodeIdLog)
константу _nodeid_ вместе с _lost_ лучше в одном месте держать и иметь описание того, что означает эта константа

2024-10-17 19:39 UTC, debnatkh commented on cloud/filestore/tools/testing/loadtest/lib/request_replay_fs.cpp
> +            if (auto path = PathByNode(logRequest.GetNodeInfo().GetNodeId())) {
лишний if

2024-10-17 19:39 UTC, debnatkh commented on cloud/filestore/tools/testing/loadtest/lib/request_replay_fs.cpp
> +        }
else ?

2024-10-17 19:39 UTC, debnatkh commented on cloud/filestore/tools/testing/loadtest/lib/request_replay_fs.cpp
> +                    MakeError(E_FAIL, "cancelled")});
same про ошибку

2024-11-07 20:02 UTC, debnatkh commented on cloud/filestore/tools/testing/loadtest/lib/request_replay_fs.cpp
> +            buffer = TString{bytes, ' '};
' ' лишнее

2024-11-07 20:02 UTC, debnatkh commented on cloud/filestore/tools/testing/loadtest/lib/request_replay_fs.cpp
> +            buffer = TString{bytes, ' '};
TString(bytes)

2024-11-07 20:05 UTC, debnatkh commented on cloud/filestore/tools/testing/loadtest/lib/request_replay_fs.cpp
> +            // fh,
лишнее

2024-11-07 20:05 UTC, debnatkh commented on cloud/filestore/tools/testing/loadtest/lib/request_replay_fs.cpp
> +        // TODO(proller): TEST USE AFTER FREE on buffer
А что тут имеется ввиду?

2024-11-07 20:09 UTC, debnatkh commented on cloud/filestore/tools/testing/loadtest/lib/request_replay_fs.cpp
> +                    MakeError(E_IO, TStringBuilder{} << "nothing written"));
```
$ ~/nbs/cloud$ grep -hroEw '(TStringBuilder\{\}|TStringBuilder\(\))' | sort | uniq -c
    945 TStringBuilder()
      1 TStringBuilder{}
```

2024-11-07 20:10 UTC, debnatkh commented on cloud/filestore/tools/testing/loadtest/lib/request_replay_fs.cpp
> +        // node_name=tfrgYZ1}
странное форматирование, лишнее название операции, в отличии от других аналогичных комментариев

2024-11-07 20:11 UTC, debnatkh commented on cloud/filestore/tools/testing/loadtest/lib/request_replay.cpp
> +        // case EFileStoreRequest:: ? :
DoFlush же имплементирован

2024-11-11 18:53 UTC, debnatkh requested changes

2024-11-11 18:53 UTC, debnatkh commented on cloud/filestore/tools/testing/loadtest/lib/request_replay_fs.cpp
> +              std::move(filesystemId),
https://github.com/ydb-platform/nbs/blob/79223f7a976206017b0460bb63c3b14374eadb06/cloud/filestore/libs/client/durable.cpp#L119-L129

2024-11-11 18:53 UTC, debnatkh commented on cloud/filestore/tools/testing/loadtest/lib/request_replay_fs.cpp
> +        if (logRequest.GetNodeInfo().GetNodeId()) {
!= InvalidNodeId

2024-11-11 18:53 UTC, debnatkh commented on cloud/filestore/tools/testing/loadtest/lib/request_replay_fs.cpp
> +                GetLocalNodeId(logRequest.GetNodeInfo().GetParentNodeId());
// case 2: parent node id + name

2024-11-11 18:53 UTC, debnatkh commented on cloud/filestore/tools/testing/loadtest/lib/request_replay_fs.cpp
> +        if (logRequest.GetNodeInfo().GetNodeId()) {
case 1 : by empty name and nodeid

ну что-то такое

2024-11-13 15:06 UTC, debnatkh requested changes

2024-11-13 15:06 UTC, debnatkh commented on cloud/filestore/tools/testing/loadtest/lib/request_replay_fs.cpp
> +        // case 1 : by nodeid with already known name
тут комментарий неправильный
Всё-таки тут открытие по пустому name, наверное?

2024-11-13 15:06 UTC, debnatkh commented on cloud/filestore/tools/testing/loadtest/lib/request_replay_fs.cpp
> +        }
да. согласен

2024-11-13 15:06 UTC, debnatkh commented on cloud/filestore/tools/testing/loadtest/lib/request_replay_fs.cpp
> +        // size=0}
лишний перенос

2024-11-13 15:48 UTC, proller commented on cloud/filestore/tools/testing/loadtest/lib/request_replay_fs.cpp
> +        // size=0}
это форматер, непонятно зачем он вообще комменты трогает

2024-11-13 17:28 UTC, proller commented on cloud/filestore/tools/testing/loadtest/lib/request_replay_fs.cpp
> +            buffer = TString{bytes, ' '};
не лишнее, нужена строка из пробелов а не \0

2024-11-13 19:33 UTC, proller commented on cloud/filestore/tools/testing/loadtest/lib/request_replay_fs.cpp
> +            case NProto::E_SOCK_NODE:
break после return ?

2024-11-13 20:57 UTC, debnatkh commented
В другом пр договорились добавить тесты с канонизацией результатов и с походами по grpc api

2024-11-13 20:58 UTC, debnatkh approved these changes

2024-11-14 16:33 UTC, yegorskii submitted a review, later dismissed

2024-11-14 19:40 UTC, yegorskii approved these changes

2024-11-15 07:23 UTC, debnatkh approved these changes

2024-11-18 09:22 UTC, debnatkh approved these changes

2024-11-18 13:14 UTC, merged