issue-1146: enforce that RO tx can not read stale data not commited yet by RW tx
ydb-platform/nbs pull request #2161
Opened 2024-09-27 17:14 UTC by debnatkh

References #1146

Through the unittest enforces that RO transaction can not observe stale data

2024-09-29 17:35 UTC, qkrorlqr approved these changes

2024-09-29 17:36 UTC, qkrorlqr commented on cloud/filestore/libs/storage/tablet/tablet_ut_nodes.cpp
> +                            Cerr << "Dropping put event" << Endl;
Cerr

2024-09-29 17:36 UTC, qkrorlqr commented on cloud/filestore/libs/storage/tablet/tablet_ut_nodes.cpp
> +        Cerr << "Sending put event" << Endl;
Cerr

2024-09-29 17:36 UTC, qkrorlqr requested changes
Надо убрать дебажный вывод

2024-10-01 10:00 UTC, qkrorlqr approved these changes

2024-10-01 10:32 UTC, yegorskii approved these changes

2024-10-01 10:36 UTC, merged