filestore-client findgarbage paging fix
ydb-platform/nbs pull request #2225
Opened 2024-10-04 19:36 UTC by qkrorlqr

2024-10-05 09:33 UTC, budevg requested changes

2024-10-05 09:33 UTC, budevg commented on cloud/filestore/apps/client/lib/find_garbage.cpp
> +            .RequiredArgument("STR")
STR -> NUM

2024-10-05 09:34 UTC, BarkovBG submitted a review, later dismissed

2024-10-05 09:34 UTC, debnatkh commented on cloud/filestore/tests/client/test.py
> +    out += client.find_garbage(fs_id, [shard1_id, shard2_id], page_size=1024)
В корне же выше генерируется всего 100 файлов. То есть оно всё в одну страницу попадёт?

2024-10-05 15:44 UTC, qkrorlqr commented on cloud/filestore/tests/client/test.py
> +    out += client.find_garbage(fs_id, [shard1_id, shard2_id], page_size=1024)
Они попадают более чем в одну страницу

2024-10-05 16:49 UTC, budevg approved these changes

2024-10-06 21:12 UTC, yegorskii approved these changes

2024-10-06 21:39 UTC, merged