issue-1146: load NodeRefs upon tablet load
ydb-platform/nbs pull request #2241
Opened 2024-10-08 17:26 UTC by debnatkh

References #1146

Add `InMemoryIndexCacheLoadOnTabletStart` option to load all noderefs to memory upon tablet startup. The loading is done in a batched manner: every iteration loads only `InMemoryIndexCacheLoadOnTabletStarRowsPerTx` refs.

2024-10-10 09:58 UTC, qkrorlqr requested changes

2024-10-10 09:58 UTC, qkrorlqr commented on cloud/filestore/config/storage.proto
> +    optional uint64 InMemoryIndexCacheLoadOnTabletStarRowsPerTx = 397;
TabletStar -> TabletStart

2024-10-10 09:58 UTC, qkrorlqr commented on cloud/filestore/libs/storage/core/config.cpp
> +    xxx(InMemoryIndexCacheLoadOnTabletStarRowsPerTx,    ui64,      100000     )\
думаю, можно сильно больше
1млн, 10млн - что-то такое
надо проверить, сколько времени займет итерация на 10млн строк
а еще у значения отступ не выровнен по остальным дефолтам

2024-10-10 09:58 UTC, qkrorlqr commented on cloud/filestore/libs/storage/tablet/tablet_actor_loadstate.cpp
> +        LoadNodeRefsIfNeeded(ctx, 0, "");
что такое 0?

2024-10-10 09:58 UTC, qkrorlqr commented on cloud/filestore/libs/storage/tablet/tablet_actor_loadstate.cpp
> +        "%s LoadNodeRefs iteration started (nodeId: %llu, name: %s, maxNodeRefs: %llu)",
разве для ui64 недостаточно просто %lu?

2024-10-10 09:58 UTC, qkrorlqr commented on cloud/filestore/libs/storage/tablet/tablet_actor_loadstate.cpp
> +void TIndexTabletActor::LoadNodeRefsIfNeeded(
лучше в отдельный файл переместить код загрузки node refs

2024-10-10 09:58 UTC, qkrorlqr commented on cloud/filestore/libs/storage/tablet/tablet_actor_loadstate.cpp
> +    Y_UNUSED(ctx);
used

2024-10-10 09:58 UTC, qkrorlqr commented on cloud/filestore/libs/storage/tablet/tablet_actor_loadstate.cpp
> +        TString(ready ? "finished" : "restarted").c_str());
а зачем TString? можно же просто (ready ? "finished" : "restarted")

2024-10-10 09:58 UTC, qkrorlqr commented on cloud/filestore/libs/storage/tablet/tablet_database.cpp
> +        NodeUpdates.emplace_back(ExtractWriteNodeRefsFromNodeRef(*ref));
lookup по nodeId будет виден в профиле
надо будет отдельным PR приделать батчевание по nodeId, чтоб один раз находить entry в кэше для nodeId и потом разом все загруженные child ref-ы добавлять в кэш для nodeId

2024-10-10 09:58 UTC, qkrorlqr commented on cloud/filestore/libs/storage/tablet/tablet_database.cpp
> +    ui64& nextNodeId,
output-параметры обычно передаем через указатели, чтоб в месте вызова было видно, что это output

2024-10-10 09:58 UTC, qkrorlqr commented on cloud/filestore/libs/storage/tablet/tablet_state_cache.cpp
> +    IsNodeRefsExhaustive = !IsNodeRefsEvictionObserved;
потом можно сделать exhaustive-флаг per directory node

2024-10-10 09:58 UTC, qkrorlqr commented on cloud/filestore/libs/storage/tablet/tablet_state_cache.cpp
> +    // This method is supposed to be called only upon tablet load in order to
а не нужно ли тогда написать тут Y_DEBUG_ABORT_UNLESS?

2024-10-10 12:56 UTC, debnatkh commented on cloud/filestore/libs/storage/tablet/tablet_actor_loadstate.cpp
> +        LoadNodeRefsIfNeeded(ctx, 0, "");
(0, "") – ключ, начиная с которого нужно вычитывать таблицу

2024-10-10 13:03 UTC, debnatkh commented on cloud/filestore/libs/storage/tablet/tablet_state_cache.cpp
> +    // This method is supposed to be called only upon tablet load in order to
Нет, в это место код зайдёт, попытавшись исполнить её как RO транзакцию, ожидается, что он не справится и пойдёт в локальную базу читать:

https://github.com/ydb-platform/nbs/blob/a835bd60d3a7c999184012defe542dbc392459b0/cloud/filestore/libs/storage/tablet/tablet_actor.h#L398-L407

2024-10-11 14:46 UTC, WilyTiger commented on cloud/filestore/libs/storage/tablet/tablet_state_nodes.cpp
> +        .ReadNodeRefs(startNodeId, startCookie, maxCount, refs, nextNodeId, nextCookie);
```
echo "        .ReadNodeRefs(startNodeId, startCookie, maxCount, refs, nextNodeId, nextCookie);" | wc -c
89
```

2024-10-11 14:52 UTC, WilyTiger commented on cloud/filestore/libs/storage/tablet/tablet_database.cpp
> +    auto it = Table<TTable>().GreaterOrEqual(startNodeId, startCookie).Select();
```
echo "    auto it = Table<TTable>().GreaterOrEqual(startNodeId, startCookie).Select();" | wc -c
81

```

2024-10-15 14:11 UTC, qkrorlqr commented on cloud/filestore/libs/storage/tablet/tablet_actor_loadstate.cpp
> -            TEvIndexTabletPrivate::TEvLoadCompactionMapChunkResponse;
тогда надо сделать так, чтоб Response Event в принципе не был нигде определен
а то Response-евент есть, но никакой код его никогда не получит

2024-10-15 14:34 UTC, debnatkh commented on cloud/filestore/libs/storage/tablet/tablet_database.h
> +        TVector<IIndexTabletDatabase::TNodeRef>& refs,
Я сделал по аналогии с другими методами ReadNodeRefs, чтобы не плодить неконсистентность 
<img width="425" alt="image" src="https://github.com/user-attachments/assets/090f32ab-6c8b-427b-a4a0-7b05f418e20a">

2024-10-15 16:53 UTC, debnatkh commented on cloud/filestore/libs/storage/tablet/tablet_actor_loadstate.cpp
> -            TEvIndexTabletPrivate::TEvLoadCompactionMapChunkResponse;
Там для нескольких макросов всё-таки нужно, чтобы он был определён – кажется, правки в них всё-таки будут довольно объёмными. Предлагаю в следующем ПР порефакторить – там будут не только LoadCompactionMapChunk/LodeNodeRefs, но и SyncSessions

2024-10-15 17:56 UTC, qkrorlqr commented on cloud/filestore/libs/storage/tablet/tablet_database.h
> +        TVector<IIndexTabletDatabase::TNodeRef>& refs,
давай тогда, раз эти параметры тут не могут быть нуллами, сделаем консистентно в рамках данного класса, то есть все output-параметры передадим как reference

2024-10-15 21:23 UTC, qkrorlqr commented on cloud/filestore/libs/storage/tablet/tablet_actor_loadstate.cpp
> -            TEvIndexTabletPrivate::TEvLoadCompactionMapChunkResponse;
не надо использовать эти макросы, если тебе не нужна request-response логика

тебе нужно событие, чтоб отдать команду на загрузку очередной страницы, и completion-событие - их можно руками объявить

каждое из них ты пошлешь ровно в одном месте и обработаешь ровно в одном месте, тут макросы не нужны

2024-10-16 09:56 UTC, qkrorlqr commented on cloud/filestore/libs/storage/tablet/tablet_private.h
> +    struct TLoadNodeRefsCompleted
лишнее

2024-10-16 09:57 UTC, qkrorlqr commented on cloud/filestore/libs/storage/tablet/tablet_actor_loadstate_noderefs.cpp
> +    LoadNodeRefsStatus.State = TLoadNodeRefsStatus::EState::LOADING;
вроде не используешь этот State нигде

2024-10-16 11:16 UTC, qkrorlqr approved these changes

2024-10-16 16:45 UTC, yegorskii approved these changes

2024-10-16 16:56 UTC, merged