[Filestore] Implement a tool which replays filestore-vhost's profile log - Tool for removing sensitive data
ydb-platform/nbs pull request #2284
Opened 2024-10-15 14:39 UTC by proller

…

2024-10-15 14:50 UTC, debnatkh commented on cloud/filestore/tools/testing/unsensitivifier/ya.make
> +
лишняя строка

2024-10-15 14:55 UTC, qkrorlqr commented on cloud/filestore/tools/testing/unsensitivifier/app.cpp
> +        unsensitivifier.Unsensitivifie(
Unsensitivify?
А вообще лучше назвать каким-то реально существующим словом или несколькими словами - например, MaskSensitiveData

2024-10-15 14:57 UTC, qkrorlqr commented on cloud/filestore/tools/testing/unsensitivifier/unsensitivifier.cpp
> +    Seed = ToString(random()) + ToString(random()) + ToString(random()) +
util/random/random.h RandomNumber()

2024-10-15 14:58 UTC, qkrorlqr commented on cloud/filestore/tools/testing/unsensitivifier/unsensitivifier.cpp
> +    Seed = ToString(random()) + ToString(random()) + ToString(random()) +
а еще удобнее - https://github.com/ydb-platform/nbs/blob/c4f11321df0d6592be38d86ced131b9d99f3bbb6/util/generic/guid.h#L70

2024-10-28 13:38 UTC, qkrorlqr approved these changes

2024-10-28 15:48 UTC, drbasic requested changes

2024-10-28 15:48 UTC, drbasic commented on cloud/filestore/tools/analytics/profile_tool/lib/mask.h
> +    THolder<NEventLog::IIterator> CurrentEvent;
Зачем THolder? это легаси

2024-10-28 15:48 UTC, drbasic commented on cloud/filestore/tools/analytics/profile_tool/lib/mask.cpp
> +#include "public.h"
clang-format так расставил переносы строк?

2024-10-28 15:48 UTC, drbasic commented on cloud/filestore/tools/analytics/profile_tool/lib/mask.cpp
> +
анонимный неймспейс в начале файла

2024-10-28 15:48 UTC, drbasic commented on cloud/filestore/tools/analytics/profile_tool/lib/mask.cpp
> +        }
я бы возвращал true только если получилось понять режим

2024-10-28 18:03 UTC, proller commented on cloud/filestore/tools/analytics/profile_tool/lib/mask.h
> +    THolder<NEventLog::IIterator> CurrentEvent;
cpp/eventlog/iterator.h : 
    THolder<IIterator> CreateIterator(const TOptions& o);

2024-10-28 18:15 UTC, qkrorlqr approved these changes

2024-10-29 12:40 UTC, drbasic approved these changes

2024-10-29 14:09 UTC, qkrorlqr approved these changes

2024-10-29 14:15 UTC, merged