Add support for variable block size in the vhost server
ydb-platform/nbs pull request #2322
Opened 2024-10-21 17:49 UTC by komarevtsev-d

https://github.com/ydb-platform/nbs/issues/2307

2024-10-21 18:14 UTC, SvartMetal commented on cloud/disk_manager/api/disk.proto
> +    DISK_KIND_HDD_LOCAL = 8;
не стоит мешать провки в blockstore и disk_manager в одном ПРе

потому что:
* неудобно ревьюить
* неудобно черри-пикать

2024-10-29 12:15 UTC, komarevtsev-d commented on cloud/blockstore/vhost-server/server_ut.cpp
Тут пришлось немного переписать. В тестах везде использовался сектор, а не блок. 
Переписал на блок и добавил парамтризацию по нему.

От сектора полностью не уйти, т.к. vhost в секторах работает

2024-10-30 13:36 UTC, budevg requested changes

2024-10-30 13:36 UTC, budevg commented on cloud/blockstore/vhost-server/request_aio_ut.cpp
> +        InitSplitDevices(5, 1_MB, 512_B);
let's extract the test into function `CheckPrepareOfCompoundIOForSplitDevices(ui32 blockSize)`
and use it in tests
`ShouldPrepareIOForSplitDevices512` 
`ShouldPrepareIOForSplitDevices4KB`

2024-10-30 13:36 UTC, budevg commented on cloud/blockstore/vhost-server/request_aio_ut.cpp
> +        InitDevices(93_GB, 512_B);
let's extract this test into function and try it with more block size variations

2024-10-30 14:23 UTC, komarevtsev-d commented on cloud/blockstore/vhost-server/request_aio_ut.cpp
> +        InitDevices(93_GB, 512_B);
Перевёл на GTest, т.к. они проще параметризируются и у нас уже есть рядышком такой тест

2024-10-30 14:34 UTC, budevg approved these changes

2024-10-30 16:39 UTC, drbasic approved these changes

2024-10-30 16:43 UTC, merged