Always retry request after DA timeout
ydb-platform/nbs pull request #2359
Opened 2024-10-28 13:23 UTC by drbasic

2024-10-30 11:49 UTC, drbasic commented on cloud/blockstore/libs/storage/partition_nonrepl/config.h
> +        if (error.GetCode() == E_IO_SILENT) {
если кто-то генерирует ошибку E_IO_SILENT, то ей проставляем флаг NCloud::NProto::EF_SILENT

2024-10-30 11:49 UTC, drbasic commented on cloud/blockstore/libs/storage/partition_nonrepl/part_nonrepl_actor.cpp
> +    if (!stat.LastTimeoutTs) {
1. оставил логику, что время таймаутов накапливается только если идут запросы.
2. Так же оставил логику, что переход в состояние "сломан" из "сломан по-тихому" проходит через заданный период времени, вне зависимости, были в это время запросы или нет.

2024-10-30 11:49 UTC, drbasic commented on cloud/blockstore/libs/storage/partition_nonrepl/part_nonrepl_actor_checksumblocks.cpp
> +    using EStatus = TEvNonreplPartitionPrivate::TOperationCompleted::EStatus;
5 файлов ниже имеют одинаковые правки. Надо будет подумать про рефакторинг?

2024-10-30 11:49 UTC, drbasic commented on cloud/blockstore/libs/storage/partition_nonrepl/part_nonrepl_actor_checksumblocks.cpp
> +    completion->ExecutionTime = ctx.Now() - StartTime;
переименовал ActorSystemTime в ExecutionTime

2024-10-30 11:49 UTC, drbasic commented on cloud/blockstore/libs/storage/partition_nonrepl/part_nonrepl_actor_checksumblocks.cpp
> +    HandleError(
Вот тут вопрос на обсудить - если не могли доставить, то мы ждали истечения всего таймаута. Я поправил чтобы отвечать сразу. Но это может привести к тому, что мы будем медленно накапливать время недоступности девайса.
Может нужно отвечать сразу, но засчитывать время как будто ждали истечения таймаута?

2024-10-30 12:29 UTC, komarevtsev-d commented on cloud/blockstore/libs/storage/partition_nonrepl/part_nonrepl_actor.cpp
> +    TRequestTimeoutPolicy* timeoutPolicy)
Если эта штука всегда не nullptr, то лучше ссылку

2024-10-30 12:37 UTC, komarevtsev-d commented on cloud/blockstore/libs/storage/partition_nonrepl/part_nonrepl_actor.cpp
> +            // Accessing to a non-allocated device causes the disk to break.
Я не понял комент. Почему он "non-allocated"? И почему доступ "causes the disk to break" ?

2024-10-30 12:39 UTC, komarevtsev-d commented on cloud/blockstore/libs/storage/partition_nonrepl/part_nonrepl_events_private.h
> +            Success,    // The request was completed successfully
Тут либо Successed, либо остальные Fail и Timeout?

2024-10-30 12:47 UTC, komarevtsev-d commented on cloud/blockstore/libs/storage/partition_nonrepl/part_nonrepl_actor.cpp
> +            Min(executionTime, now - stat.LastTimeoutTs);
А точно Min, а не Max?

2024-10-30 12:52 UTC, komarevtsev-d commented on cloud/blockstore/libs/storage/partition_nonrepl/part_nonrepl_actor.cpp
> +            DeviceStats[dr.DeviceIdx].DeviceStatus = EDeviceStatus::Broken;
А эти две строки зачем?

2024-10-30 13:24 UTC, komarevtsev-d commented on cloud/blockstore/libs/storage/partition_nonrepl/part_nonrepl_actor.cpp
> +                Config->GetExpectedClientBackoffIncrement());
Получается теперь ExpectedClientBackoffIncrement - не инкремент? А просто какое-то значение на которое один раз увеличиваем таймаут?

2024-10-31 06:40 UTC, drbasic commented on cloud/blockstore/libs/storage/partition_nonrepl/part_nonrepl_actor.cpp
> +    TRequestTimeoutPolicy* timeoutPolicy)
это выходной параметр, по этому указатель. как и для deviceRequests

2024-10-31 09:51 UTC, drbasic commented on cloud/blockstore/libs/storage/partition_nonrepl/part_nonrepl_actor.cpp
> +                Config->GetExpectedClientBackoffIncrement());
да, теперь это так. надо как-то переименовать, или может вообще убрать эту настройку. не понятна ее полезность.

2024-10-31 19:15 UTC, qkrorlqr commented on cloud/blockstore/libs/storage/partition_nonrepl/part_nonrepl_actor.cpp
> +                Config->GetExpectedClientBackoffIncrement());
ExpectedClientBackoffIncrement нужен, чтобы сматчить суммарное ожидание в DurableClient с расчетом TimedOutStateDuration в этом акторе

Если мы теперь считаем TimedOutStateDuration НЕ как сумму ожиданий ответов на запросы, а как сумму времен от LastTimeoutTs до now, то этот BackoffIncrement в partition_nonrepl не нужен

2024-10-31 19:21 UTC, qkrorlqr commented on cloud/blockstore/libs/storage/partition_nonrepl/part_nonrepl_actor.cpp
> +            Min(executionTime, now - stat.LastTimeoutTs);
если ты избавляешься от BackoffIncrement, то Min с executionTime делать неправильно и надо просто добавлять now - stat.LastTimeoutTs (как мы обсуждали голосом)

2024-10-31 19:22 UTC, qkrorlqr commented on cloud/blockstore/libs/storage/partition_nonrepl/part_nonrepl_actor.h
> +// Adjusts the behavior when a response is not received from the server during
within the timeout

2024-10-31 19:22 UTC, qkrorlqr commented on cloud/blockstore/libs/storage/partition_nonrepl/part_nonrepl_actor.h
> +    // An error that needs to be generated when a timeout occurs.
The error

2024-10-31 19:22 UTC, qkrorlqr commented on cloud/blockstore/libs/storage/partition_nonrepl/part_nonrepl_actor.h
> +    // Message for response.
the response

2024-10-31 19:26 UTC, qkrorlqr commented on cloud/blockstore/libs/storage/partition_nonrepl/part_nonrepl_actor_checksumblocks.cpp
> +    using EStatus = TEvNonreplPartitionPrivate::TOperationCompleted::EStatus;
Можно попробовать. Но вообще код в этих файлах довольно тупой и большой проблемы в копипасте я не вижу. Но, может, через темплейты получится оформить компактнее и аккуратнее.

2024-10-31 19:26 UTC, qkrorlqr commented on cloud/blockstore/libs/storage/partition_nonrepl/part_nonrepl_actor_checksumblocks.cpp
> +        bool timedout);
timedOut

2024-11-01 07:32 UTC, drbasic commented on cloud/blockstore/libs/storage/partition_nonrepl/part_nonrepl_actor.cpp
> +            Min(executionTime, now - stat.LastTimeoutTs);
Выбор минимума является предохранителем от того, что время движется скачком вперед, так получается безопаснее.

2024-11-02 07:28 UTC, komarevtsev-d submitted a review, later dismissed

2024-11-02 11:08 UTC, qkrorlqr commented on cloud/blockstore/libs/storage/partition_nonrepl/part_nonrepl_actor.cpp
> +            Min(executionTime, now - stat.LastTimeoutTs);
там у тебя не безопасный код, а просто неправильный код, который фактически складывает только executionTime-ы, потому что backoff-ы между ними ты выпилил

2024-11-02 11:26 UTC, drbasic commented on cloud/blockstore/libs/storage/partition_nonrepl/part_nonrepl_actor.cpp
> +            Min(executionTime, now - stat.LastTimeoutTs);
Когда приходит первый таймаут, мы засчитываем в суммарное время таймаута ровно столько он сказал в executionTime.
Когда приходит второй - мы увеличиваем время на дельту между тем сколько времени прошло от последнего инкремента таймаута до текущего времени, но не больше чем executionTime.

2024-11-02 11:37 UTC, drbasic commented on cloud/blockstore/libs/storage/partition_nonrepl/part_nonrepl_actor.cpp
> +            Min(executionTime, now - stat.LastTimeoutTs);
Ааа, кажется понял. Ты все-таки хочешь засчитывать время даже когда запросы не выполнялись?

2024-11-02 14:33 UTC, qkrorlqr commented on cloud/blockstore/libs/storage/partition_nonrepl/part_nonrepl_actor.cpp
> +            Min(executionTime, now - stat.LastTimeoutTs);
Да, потому что DurableClient ждет на бэкоффе и реальное время, которое гость ожидает выполнения запроса, на самом деле идет. За этим и был нужен ExpectedClientBackoffIncrement - чтобы по сути повторить в partition_nonrepl логику вычисления backoff в DurableClient и засчитать в TimedOutDuration полное время - и время выполнения, и время искусственного ожидания на backoff.

2024-11-02 14:44 UTC, drbasic commented on cloud/blockstore/libs/storage/partition_nonrepl/part_nonrepl_actor.cpp
> +            Min(executionTime, now - stat.LastTimeoutTs);
Если мы хотим считать так: 
```
|-----|      |---------|        |---------------|
   |-----|      |---------|         |-----------------|
<-----------TimedOutDuration------------> 
```
то я сделаю проще, буду запоминать время первого затаймаутившегося запроса.
В таком случае изменений в тестах будет больше, сейчас они написаны из ожидания первой картинки.

2024-11-05 17:31 UTC, qkrorlqr commented on cloud/blockstore/libs/storage/partition_nonrepl/part_nonrepl_actor.cpp
> +            Min(executionTime, now - stat.LastTimeoutTs);
> Если мы хотим считать так:

ну, когда ты голосом рассказывал, что хочешь сделать, я тебя понял именно так

надо делать либо так, либо не трогать то, как сделано сейчас

2024-11-05 18:45 UTC, qkrorlqr requested changes
И еще сильнее теперь смущает копипаста между акторами, выполняющими разные типы запросов

В следующем за этим PR-е стоит постараться от копипасты избавиться

2024-11-05 18:45 UTC, qkrorlqr commented on cloud/blockstore/libs/storage/partition_nonrepl/part_nonrepl_actor.cpp
> +        return policy;
а почему игнорируем worstDeviceStatus в этой ветке?

2024-11-05 18:45 UTC, qkrorlqr commented on cloud/blockstore/libs/storage/partition_nonrepl/part_nonrepl_events_private.h
> +        EStatus Status = EStatus::Success;
мне не очень нравится такой дефолт
мы, например, прямо сейчас дебажим проблему, когда при разрыве rdma-соединения в некоторые реплики может не дойти запись, при этом слой выше ошибку не видит и считает, что все ок
давай сделаем по дефолту Fail?

2024-11-06 03:46 UTC, drbasic commented on cloud/blockstore/libs/storage/partition_nonrepl/part_nonrepl_actor.cpp
> +            Min(executionTime, now - stat.LastTimeoutTs);
После твоего комментария про 
> Да, потому что DurableClient ждет на бэкоффе и реальное время, которое гость ожидает выполнения запроса, на самом деле идет. За этим и был нужен ExpectedClientBackoffIncrement - чтобы по сути повторить в partition_nonrepl логику вычисления backoff в DurableClient и засчитать в TimedOutDuration полное время - и время выполнения, и время искусственного ожидания на backoff.
картинка сложилась и сделал так:
```
|-----|      |---------|        |---------------|
   |-----|      |---------|         |-----------------|
<-------------------------TimedOutDuration------------> 
```

2024-11-06 03:54 UTC, drbasic commented on cloud/blockstore/libs/storage/partition_nonrepl/part_nonrepl_actor.cpp
> +        return policy;
Если не было никаких таймаутов, то и в ошибку никто не мог уйти.

2024-11-06 11:08 UTC, qkrorlqr commented on cloud/blockstore/libs/storage/partition_nonrepl/part_nonrepl_actor.cpp
> +        return policy;
по коду выше это не очевидно

2024-11-06 11:40 UTC, drbasic commented on cloud/blockstore/libs/storage/partition_nonrepl/part_nonrepl_actor.cpp
> +        return policy;
Дописал комментариев и чуть попереставлял код.

2024-11-07 13:05 UTC, merged