Support per-VM volumes
ydb-platform/nbs pull request #2361
Opened 2024-10-28 14:25 UTC by aikuchin

2024-10-29 15:24 UTC, antonmyagkov submitted a review, later dismissed

2024-10-30 11:28 UTC, drbasic commented on cloud/blockstore/tools/csi_driver/internal/driver/node.go
> -const instanceIDKey = "instanceId"
А можно не менять ID на Id. 
У нас линтер начинает ругаться.
Я вроде выкусил сборку всего что связано с csi но не уверен что таска линтера будет тоже игнорировать csi.

2024-10-30 11:49 UTC, aikuchin commented on cloud/blockstore/tools/csi_driver/internal/driver/node.go
> -const instanceIDKey = "instanceId"
А сейчас не ругается? В коде и так был зоопарк из ID и Id, так что я ожидал бы что оно уже должно было ругаться.

2024-10-30 11:58 UTC, aikuchin commented on cloud/blockstore/tools/csi_driver/internal/driver/node.go
> -const instanceIDKey = "instanceId"
В частности у нас в public api такая капитализация используется - https://github.com/ydb-platform/nbs/blob/main/cloud/blockstore/public/api/protos/endpoints.proto#L29

Но если это принципиально могу вернуть как было. Линтер только на эту переменную ругается или в других местах тоже? Можно пример ошибки чтобы сразу пофиксить всё что ему не нравится?

2024-10-30 18:13 UTC, aikuchin commented
Rebased to resolve conflict after merge of #2372

2024-10-30 18:20 UTC, SvartMetal commented on cloud/blockstore/tools/csi_driver/internal/driver/node.go
> -const instanceIDKey = "instanceId"
> В коде и так был зоопарк из ID и Id
"Id" в нашем go-коде возникают из-за протобуфов, "ID" - из-за go-линтера.
Я за то, чтобы расслабить линтер и сделать рефакторинг ID -> Id

2024-10-30 18:21 UTC, SvartMetal commented on cloud/blockstore/tools/csi_driver/internal/driver/node.go
> -const instanceIDKey = "instanceId"
Но в текущем ПРе придётся сделать Id -> ID

2024-10-31 14:30 UTC, SvartMetal commented on cloud/blockstore/tools/csi_driver/internal/driver/node.go
> -const instanceIDKey = "instanceId"
@drbasic @BarkovBG а расскажите пожалуйста как правильно запустить линтер на нашем гитхабном коде? 
Вызов `ya tool go vet xxx.go` не находит проблемы с "Id"

2024-11-01 12:28 UTC, drbasic commented on cloud/blockstore/tools/csi_driver/internal/driver/node.go
> -const instanceIDKey = "instanceId"
Его не запустить. Это какая-то приблуда в аркадии

2024-11-01 12:39 UTC, drbasic commented on cloud/blockstore/tools/csi_driver/internal/driver/node.go
> -const instanceIDKey = "instanceId"
Так. Давайте я попробую проверить в аркадии, правда ли такой линтер есть. Что-то я не могу найти где я такое правил. 
А вам принципиально сделать буковки Id ? Раньше же никого это не смущало.

2024-11-01 14:05 UTC, aikuchin commented on cloud/blockstore/tools/csi_driver/internal/driver/node.go
> -const instanceIDKey = "instanceId"
> А вам принципиально сделать буковки Id ? Раньше же никого это не смущало.
Совершенно не принципиально, сделаю как скажешь. Я просто хочу узнать только эту константу нужно исприваить или ещё какие-то локальные переменные, имена функций и аргументы.

2024-11-02 03:32 UTC, drbasic requested changes

2024-11-02 03:32 UTC, drbasic commented on cloud/blockstore/tools/csi_driver/internal/driver/node.go
> -const instanceIDKey = "instanceId"
![image](https://github.com/user-attachments/assets/b260b94d-9771-4996-8a89-657df3d2b766)
![image](https://github.com/user-attachments/assets/4cdc1821-c920-42b7-953a-6074149a951e)

2024-11-02 13:50 UTC, drbasic commented on cloud/blockstore/tools/csi_driver/internal/driver/node.go
> -const instanceIDKey = "instanceId"
команда которая выполняет проверки
``
ya test -DAUTOCHECK=yes --style 
```

2024-11-03 01:04 UTC, aikuchin commented on cloud/blockstore/tools/csi_driver/internal/driver/node.go
> -const instanceIDKey = "instanceId"
> `ya test -DAUTOCHECK=yes --style`

Это у меня не захотело работать без аркадии, но по ошибке [ST1003](https://staticcheck.dev/docs/checks/#ST1003) нашлось что это `staticcheck`, просто не с дефолтным конфигом (по дефолту у него эта проверка отключена, видимо в аркадии он вызывается с флагом `-check=all`)

Добавил комит с отключением этой проверки точечно в файлах которые я меняю в этом ПР т.к. хочется влить его как можно быстрее.
Планирую на следующей неделе обсудить это с командой и отдельным ПР-ом добавить `staticcheck.conf` в наши директории чтобы не нужно было в каждом файле прописывать отключение проверки и починить вам линтер и здесь и в `disk_manager`.

Такой вариант ОК?

2024-11-03 01:07 UTC, aikuchin commented
Disabled linter check of identifier naming
Rebased to resolve conflict after merge of #2375

2024-11-04 11:10 UTC, antonmyagkov approved these changes

2024-11-04 11:36 UTC, drbasic approved these changes

2024-11-04 12:02 UTC, aikuchin commented
Merge please. I don't have write permissions to this repo.

2024-11-04 12:03 UTC, merged