[Blockstore] handle disk allocation errors when updating the volume config
ydb-platform/nbs pull request #2370
Opened 2024-10-29 09:45 UTC by sharpeye

If an allocation error occurs during a volume configuration update, the volume stores inconsistent data in Meta (non-empty replicas containing empty device lists).

2024-10-29 10:54 UTC, qkrorlqr commented on cloud/blockstore/libs/storage/volume/volume_actor_updateconfig.cpp
> -    UnfinishedUpdateVolumeConfig.Clear();
так, может, Clear() починить?

2024-10-29 10:56 UTC, qkrorlqr requested changes
в Description нужно описание сценария, который в этом PR чинится

2024-10-29 10:57 UTC, qkrorlqr commented on cloud/blockstore/libs/storage/volume/volume_ut.cpp
> +        runtime->SetObserverFunc(
EventFilter

2024-10-31 09:49 UTC, qkrorlqr commented on cloud/blockstore/libs/storage/volume/volume_actor_allocatedisk.cpp
> +                UnfinishedUpdateVolumeConfig.Replicas.push_back(r.GetDevices());
не хочешь поресетить Replicas перед тем, как заполнять?

2024-10-31 10:18 UTC, qkrorlqr approved these changes

2024-10-31 11:51 UTC, yegorskii approved these changes

2024-10-31 12:03 UTC, merged