add checkpoints request validation and postponed checkpoint requests
ydb-platform/nbs pull request #239
Opened 2024-01-25 09:40 UTC by gy2411

2024-01-30 08:19 UTC, drbasic requested changes

2024-01-30 08:19 UTC, drbasic commented on cloud/blockstore/libs/storage/volume/volume_actor_checkpoint.cpp
> +    TrySaveCheckpointRequest(ctx, request, info);
почему именно try, разве мы не можем решить тут будем или нет сохранять запрос персистентно?

2024-01-30 08:19 UTC, drbasic commented on cloud/blockstore/libs/storage/volume/volume_actor_checkpoint.cpp
> +void TVolumeActor::ReplyToCheckpointRequestWithoutSaving(
кажется излишнее разбитие на функции, может TryReplyToCheckpointRequestWithoutSaving и ReplyToCheckpointRequestWithoutSaving слить вместе? или где-то еще зовется ReplyToCheckpointRequestWithoutSaving?

2024-01-30 08:19 UTC, drbasic commented on cloud/blockstore/libs/storage/volume/volume_actor_checkpoint.cpp
> +ECheckpointRequestValidityStatus TVolumeActor::ValidateCheckpointRequest(
Может удобнее чтобы возвращался ```Optional<TError>```
Если нужн выполнять запрос возвращаешь std::nullopt
если ответить already: return MakeError(S_OK)
для ошибки MakeError(E_PRECONDITION_FAILED, message, flags)

2024-01-30 08:19 UTC, drbasic commented on cloud/blockstore/libs/storage/volume/volume_actor_checkpoint.cpp
> +        !checkpointsWithSavedRequest.contains(checkpointRequestCopy.CheckpointId);
повторюсь, что может проверить нужно ли сохранять до запуска транзакции?

2024-01-30 08:19 UTC, drbasic commented on cloud/blockstore/libs/storage/volume/volume_actor_checkpoint.cpp
> +            args.TraceTs}});
в этой ветке нужно ли запустить ProcessPostponedCheckpointRequests() ?

2024-01-30 14:05 UTC, gy2411 commented on cloud/blockstore/libs/storage/volume/volume_actor_checkpoint.cpp
> +        !checkpointsWithSavedRequest.contains(checkpointRequestCopy.CheckpointId);
Да, сделал проверку до запуска транзакции.

2024-01-30 14:10 UTC, gy2411 commented on cloud/blockstore/libs/storage/volume/volume_actor_checkpoint.cpp
> +            args.TraceTs}});
Вызывать ProcessPostponedCheckpointRequests здесь не обязательно -- если не смогли сохранить запрос, то сейчас уже есть другой сохранённый запрос с этим checkpoint id. Для него потом вызовится CompleteUpdateCheckpointRequest, а оттуда уже вызовится ProcessPostponedCheckpointRequests.

Но если вызвать, то тоже ничего плохого не будет.

2024-01-30 14:12 UTC, gy2411 commented on cloud/blockstore/libs/storage/volume/volume_actor_checkpoint.cpp
> +void TVolumeActor::ReplyToCheckpointRequestWithoutSaving(
Слил в одну функцию

2024-01-30 14:19 UTC, gy2411 commented on cloud/blockstore/libs/storage/volume/model/checkpoint.h
> +template<typename TCheckpointRequestInfo>
Ох, это попытка справиться с такой проблемой.

В TPostponedCheckpointRequest мы хотим хранить [TCheckpointRequestInfo](https://github.com/ydb-platform/nbs/blob/024c54e6b8631f84b9eb3a28a453bf63ab89b4a4/cloud/blockstore/libs/storage/volume/volume_actor.h#L306), который опеделён в volume_actor.h. Файл volume_actor.h инклудит checkpoint.h. Получается зависимость двух файлов друг от друга.

Можно было бы ещё вынести TCheckpointRequestInfo в какой-нибудь другой .h файл, который заинклудить и в volume_actor.h, и в checkpoing.h. Но я не придумал, куда бы его вынести, чтобы это выглядело адекватно.

Если ты знаешь какой-нибудь более хороший способ решить эту проблему, то подскажи, пожалуйста.

2024-01-31 09:25 UTC, drbasic commented on cloud/blockstore/libs/storage/volume/model/checkpoint.h
> +template<typename TCheckpointRequestInfo>
перенести TCheckpointRequestInfo в checkpoint.h

2024-01-31 09:29 UTC, drbasic commented on cloud/blockstore/libs/storage/volume/volume_actor_checkpoint.cpp
> +            LOG_DEBUG(ctx, TBlockStoreComponents::VOLUME,
получается что запрос отсался в списке PostponedCheckpointRequests.
Почему в следущий раз с ним получится разобраться?

2024-01-31 09:32 UTC, drbasic commented on cloud/blockstore/libs/storage/volume/model/checkpoint.h
> +    TSet<TString>& GetCheckpoitsWithSavedRequest();
Не хорошо наружу давать доступ к кишочкам, что их кто-то снаружи может модифицировать.
Должен быть метод который меняет внутреннее состояние класса. Это гарантирует что внутреннее состояние будет консистентно.
Т.е. примененеие любого публичного метода должно оставлять класс в консистентном состоянии

2024-01-31 10:28 UTC, gy2411 commented on cloud/blockstore/libs/storage/volume/volume_actor_checkpoint.cpp
> +            LOG_DEBUG(ctx, TBlockStoreComponents::VOLUME,
С этим запросом получится разобраться тогда, когда мы завершим исполнение другого запроса с тем же checkpoint id, из-за которого у нас и не получилось сохранить этот запрос.

А ProcessPostponedCheckpointRequests для этого checkpoint id в слудеющий раз вызовется как раз по окончании того запроса.

2024-01-31 15:14 UTC, gy2411 commented on cloud/blockstore/libs/storage/volume/volume_actor_checkpoint.cpp
> +    std::optional<NProto::TError> error =
Переименовал error -> validationResult

2024-02-01 06:34 UTC, drbasic approved these changes

2024-02-01 06:35 UTC, drbasic commented
А на mon-странице про чекпоинты мы увидим только какие запросы, которые сохранены персистентно?

2024-02-01 09:21 UTC, gy2411 commented
> А на mon-странице про чекпоинты мы увидим только какие запросы, которые сохранены персистентно?

Да.

Для дублирующихся запросов мы как раз и хотели, чтобы они не отображались на монстранице.

Для некорректных запросов можно было бы сделать и так, и так. Но ранее сошлись на том, чтобы и их не сохранять:
https://st.yandex-team.ru/NBS-4665#6552439afc13bb21b8af3560
> Думаю что в обоих случаях не нужно запоминать запрос персистентно, ведь семантика обработки запросов от этого не изменится

2024-04-11 17:54 UTC, qkrorlqr requested changes

2024-04-11 17:54 UTC, qkrorlqr commented on cloud/blockstore/libs/storage/volume/model/checkpoint.cpp
> +bool TCheckpointStore::IsCheckpointInSavedStatusExist(const TString& checkpointId) const
DoesCheckpointInSavedStatusExist

2024-04-11 17:54 UTC, qkrorlqr commented on cloud/blockstore/libs/storage/volume/model/checkpoint.cpp
> +        *message = ToString(requestType) + " request makes sence for normal checkpoints only";
слишком длинная строка

2024-04-11 17:54 UTC, qkrorlqr commented on cloud/blockstore/libs/storage/volume/model/checkpoint.cpp
> +        *message = "Checkpoint id should be nonempty";
should not be empty

2024-04-11 17:54 UTC, qkrorlqr commented on cloud/blockstore/libs/storage/volume/model/checkpoint.cpp
> +        *message = ToString(requestType) + " request makes sence for normal checkpoints only";
sence -> sense

2024-04-11 17:54 UTC, qkrorlqr commented on cloud/blockstore/libs/storage/volume/model/checkpoint.cpp
> +                return ECheckpointRequestValidityStatus::Already;
почему статус для Delete отличается от статуса для DeleteData? если чекпоинт никогда не существовал, почему нельзя и там, и там вернуть Invalid?

2024-04-11 17:54 UTC, qkrorlqr commented on cloud/blockstore/libs/storage/volume/model/checkpoint.cpp
> +        *message = "Checkpoint validation should never reach this line";
значит, тут должен быть как минимум VERIFY_DEBUG, а лучше STORAGE_CHECK_PRECONDITION (кстати, в других местах, где дебажные верифайки, тоже лучше STORAGE_CHECK_PRECONDITION)

2024-04-11 17:54 UTC, qkrorlqr commented on cloud/blockstore/libs/storage/volume/model/checkpoint.h
> +// Request status that determines either the request should be executed or return immediately
either -> whether

2024-04-11 17:54 UTC, qkrorlqr commented on cloud/blockstore/libs/storage/volume/model/checkpoint.h
> +    TSet<TString> DeletedCheckpoints;
а почему не THashSet?

2024-04-11 17:54 UTC, qkrorlqr commented on cloud/blockstore/libs/storage/volume/model/checkpoint.h
> +template<typename TCheckpointRequestInfo>
не надо тут шаблонов, надо просто перенести TCheckpointRequestInfo, да
и лучше отдельным PR

2024-04-11 17:54 UTC, qkrorlqr commented on cloud/blockstore/libs/storage/volume/model/checkpoint.h
> +struct TPostponedCheckpointRequest {
{ не там

2024-04-11 17:54 UTC, qkrorlqr commented on cloud/blockstore/libs/storage/volume/model/checkpoint.h
> +    void AddPostponedRequest(TString checkpointId, TRequest request)
const TString& checkpointId, раз уж ты не муваешь checkpointId

2024-04-11 17:54 UTC, qkrorlqr commented on cloud/blockstore/libs/storage/volume/model/checkpoint.h
> +        Y_DEBUG_ABORT_UNLESS(queue);
смысл в дебажной верифайке, если ты потом безусловно лезешь в queue и все равно упадешь в релизе
сделай тогда уж if или тут сделай STORAGE_VERIFY

2024-04-11 17:54 UTC, qkrorlqr commented on cloud/blockstore/libs/storage/volume/volume_actor_checkpoint.cpp
> +        auto ponstponedRequestInfo =
ponstponed -> postponed

2024-04-11 17:54 UTC, qkrorlqr commented on cloud/blockstore/libs/storage/volume/volume_actor_checkpoint.cpp
> +            if (!State->GetCheckpointStore().HasSavedRequest(request.CheckpointId)) {
как мы можем сюда попасть, если мы всегда сначала сохраняем запрос и только потом добавляем в очередь отложенных?

2024-04-11 17:54 UTC, qkrorlqr commented on cloud/blockstore/libs/storage/volume/volume_actor_checkpoint.cpp
> +    if (validityStatus == ECheckpointRequestValidityStatus::Already) {
я не понимаю, зачем эта прослойка в виде энума - можно же сразу из CheckpointStore отдавать TError

2024-04-11 17:54 UTC, qkrorlqr commented on cloud/blockstore/libs/storage/volume/volume_actor_checkpoint.cpp
> -        default:
почему?

2024-04-11 17:54 UTC, qkrorlqr commented on cloud/blockstore/libs/storage/volume/volume_actor_checkpoint.cpp
> +    checkpointRequestCopy.State = ECheckpointRequestState::Saved;
правки в этой функции не нужны - тут просто переносы строк, которые ничего не улучшают

2024-04-11 17:54 UTC, qkrorlqr commented on cloud/blockstore/libs/storage/volume/volume_actor_checkpoint.cpp
> +    auto checkpointRequestCopy =
а зачем копия? почему не вернуть const& или const*?

2024-04-11 17:54 UTC, qkrorlqr commented on cloud/blockstore/libs/storage/volume/volume_ut_checkpoint.cpp
> +            // In this case, some requests are replied immidiately,
immediately
replied to

2024-04-11 17:54 UTC, qkrorlqr commented on cloud/secret_ids
> +3781164a-cff3-11ee-9baa-c668395ed730
что это за файл?

2024-04-11 17:54 UTC, qkrorlqr commented on cloud/blockstore/libs/storage/volume/volume_actor.h
>          {}
этот PR надо разделить на 2: один в model, другой в актора
иначе, боюсь, ревью будет тянуться долго

2024-04-12 15:28 UTC, qkrorlqr commented
Обсудили голосом - кажется, можно все сильно упростить. Жду нового PR от Гриши.

2024-05-29 09:58 UTC, gy2411 commented
Закрываю этот pr, так как вместо него закоммитили следующие:
https://github.com/ydb-platform/nbs/pull/1084
https://github.com/ydb-platform/nbs/pull/1134
https://github.com/ydb-platform/nbs/pull/1239

2024-05-29 09:58 UTC, closed without merging

2024-05-29 09:59 UTC, gy2411 commented
^