issue-1541: postpone DestroyHandle request if HandleOpsQueue overflows
ydb-platform/nbs pull request #2394
Opened 2024-10-31 16:54 UTC by WilyTiger

#1541

2024-11-06 11:44 UTC, drbasic commented on cloud/filestore/libs/vfs_fuse/fs_impl.cpp
> +                [this, ptr = weak_from_this(), callContext](const auto& future)
зачем this?
Не удобнее будет сделать метод и позвать его?

2024-11-06 11:48 UTC, drbasic commented on cloud/filestore/libs/vfs_fuse/fs_impl_data.cpp
> +        const auto& res = HandleOpsQueue->AddDestroyRequest(ino, fh);
const auto

2024-11-06 11:48 UTC, drbasic commented on cloud/filestore/libs/vfs_fuse/fs_impl_data.cpp
> +                MakeError(
clang-format

2024-11-06 12:02 UTC, budevg requested changes

2024-11-11 12:09 UTC, budevg approved these changes

2024-11-11 12:38 UTC, qkrorlqr commented on cloud/filestore/libs/vfs_fuse/fs_impl.h
> +    );
на предыдущую строку

2024-11-11 12:38 UTC, qkrorlqr commented on cloud/filestore/libs/vfs_fuse/fs_impl.cpp
> +    TCallContextPtr callContext,
тут не нужен указатель, можно передать как TCallContext& callContext

2024-11-11 12:38 UTC, qkrorlqr commented on cloud/filestore/libs/vfs_fuse/fs_impl_data.cpp
> +    with_lock(HandleOpsQueueLock) {
with_lock пробел (

2024-11-11 12:39 UTC, qkrorlqr commented on cloud/filestore/libs/vfs_fuse/fs_impl_data.cpp
> +        if (res == THandleOpsQueue::EResult::QueueOveflow) {
QueueOveflow -> QueueOverflow

2024-11-11 12:40 UTC, qkrorlqr commented on cloud/filestore/libs/vfs_fuse/fs_impl_data.cpp
> +            with_lock(DelayedReleaseQueueLock) {
with_lock пробел (

2024-11-11 13:05 UTC, qkrorlqr approved these changes

2024-11-11 16:03 UTC, yegorskii approved these changes

2024-11-11 16:06 UTC, merged