issue-2141: resync range after scrubbing mismatch only if majority of checksums are equal
ydb-platform/nbs pull request #2408
Opened 2024-11-01 20:23 UTC by WilyTiger

#2141

2024-11-04 11:30 UTC, qkrorlqr commented on cloud/blockstore/libs/storage/partition_nonrepl/part_mirror_ut.cpp
> +        TTestEnv& testEnv)
необязательно тут переносить

2024-11-04 11:30 UTC, qkrorlqr commented on cloud/blockstore/libs/storage/partition_nonrepl/part_mirror_ut.cpp
> +    void WaitUntilScrubbingFinishCurrentCycle(
Finish -> Finishes

2024-11-04 11:30 UTC, qkrorlqr commented on cloud/blockstore/libs/storage/partition_nonrepl/part_mirror_ut.cpp
> +        {
тут тоже не надо переносить

2024-11-04 11:30 UTC, qkrorlqr commented on cloud/blockstore/libs/storage/partition_nonrepl/part_mirror_ut.cpp
> +    Y_UNIT_TEST(ShouldStartResyncAfterScrubbingOnlyIfMajorityOfChecksumsEqual)
Equal -> AreEqual

2024-11-04 12:07 UTC, qkrorlqr commented on cloud/blockstore/libs/storage/partition_nonrepl/part_mirror_ut.cpp
> +    void WaitUntilScrubbingFinishesCurrentCycle(TTestEnv& testEnv) {
но {-то надо оставить на следующей строке

2024-11-05 09:22 UTC, qkrorlqr submitted a review, later dismissed

2024-11-05 10:12 UTC, drbasic requested changes

2024-11-05 10:12 UTC, drbasic commented on cloud/blockstore/libs/storage/partition_nonrepl/part_mirror_ut.cpp
> +    void WaitUntilScrubbingFinishesCurrentCycle(TTestEnv& testEnv)
эту функцию нужно в анонимный неймспейс

2024-11-05 10:12 UTC, drbasic commented on cloud/blockstore/libs/storage/partition_nonrepl/part_mirror_actor.cpp
Лучше явно выделить переменную, чтобы понимать что имел ввиду автор.
Выбери имя переменной на свой вкус.
```
const bool hasQuorum = majorCount > checksums.size() / 2;
if (Config->GetResyncRangeAfterScrubbing() && hasQuorum)
```

2024-11-05 10:12 UTC, drbasic commented on cloud/blockstore/libs/storage/partition_nonrepl/part_mirror_actor.cpp
> +            majorCount > checksums.size() / 2)
Напомни как мы обрабатываем ситуацию когда все 3 реплики разные?

2024-11-05 12:03 UTC, WilyTiger commented on cloud/blockstore/libs/storage/partition_nonrepl/part_mirror_actor.cpp
> +            majorCount > checksums.size() / 2)
Сейчас никак. Непонятно какими данными нужно восстанавливать, поэтому хочется чтобы было время среагировать на такое и посмотреть что произошло

2024-11-05 12:19 UTC, drbasic approved these changes

2024-11-05 12:36 UTC, qkrorlqr approved these changes

2024-11-05 12:59 UTC, merged