add block validation mode to eternal_tests/range-validator
ydb-platform/nbs pull request #2440
Opened 2024-11-07 18:19 UTC by tpashkin

2024-11-07 19:53 UTC, sharpeye commented on cloud/blockstore/tools/testing/eternal_tests/range-validator/main.cpp
> +                    ui64 last = lastStr.empty() ? first : FromString<ui64>(lastStr);
Кажется, тут SplitOff может помочь:
```cpp
TStringBuf firstStr;
while (buf.NextTok(',', firstStr)) {
    TStringBuf lastStr = firstStr.SplitOff('-');
    ui64 first = FromString<ui64>(firstStr);
    ui64 last = lastStr.empty() ? first : FromString<ui64>(lastStr);
```

2024-11-07 19:58 UTC, sharpeye commented on cloud/blockstore/tools/testing/eternal_tests/range-validator/main.cpp
> +enum class EValidationMode {
{ не там

2024-11-08 09:33 UTC, tpashkin commented on cloud/blockstore/tools/testing/eternal_tests/range-validator/main.cpp
> +            File.Read(buf, PAGE_SIZE);
Я всё же переделал это место. Во-первых странно, что изначальный код не использовал O_DIRECT, а во-вторых O_DIRECT предполагает, что офсет кратен по сектору, а длина странце

2024-11-08 10:09 UTC, sharpeye approved these changes

2024-11-08 10:24 UTC, drbasic requested changes

2024-11-08 10:24 UTC, drbasic commented on cloud/blockstore/tools/testing/eternal_tests/range-validator/main.cpp
> +
clang-format по-моему против таких переносов

2024-11-08 10:24 UTC, drbasic commented on cloud/blockstore/tools/testing/eternal_tests/range-validator/main.cpp
> +            .StoreResult(&BlockSize);
BlockSize должен быть больше PAGE_SIZE ?

2024-11-08 10:24 UTC, drbasic commented on cloud/blockstore/tools/testing/eternal_tests/range-validator/main.cpp
> +            File.Read(buf, PAGE_SIZE);
а зачем читать всю страницу? и что будет если читаются данные в конце файла, там просто не будет целой страницы на прочитать

2024-11-08 10:24 UTC, drbasic commented on cloud/blockstore/tools/testing/eternal_tests/range-validator/main.cpp
> +    TFile File(options.DevicePath, EOpenModeFlag::RdOnly | EOpenModeFlag::DirectAligned);
file с маленькой буквы

2024-11-08 10:24 UTC, drbasic commented on cloud/blockstore/tools/testing/eternal_tests/range-validator/main.cpp
> +        std::set<TBlockData, decltype(compare)> uniqueBlocks(compare);
компаратор должен сравнивать на "меньше"

2024-11-08 10:24 UTC, drbasic commented on cloud/blockstore/tools/testing/eternal_tests/range-validator/main.cpp
> +        return memcmp(&x, &y, sizeof(TBlockData));
лучше сделай оператор сравнения меньше внутри TBlockData

2024-11-08 10:24 UTC, drbasic commented on cloud/blockstore/tools/testing/eternal_tests/range-validator/main.cpp
> +            file.Seek(blockIndex * options.BlockSize, sSet);
снова не понятно зачем читать целую страницу

2024-11-08 10:24 UTC, drbasic commented on cloud/blockstore/tools/testing/eternal_tests/range-validator/main.cpp
> +                << " " << block.RequestNumber
сделай внешний оператор вывод а поток для TBlockData

2024-11-08 10:32 UTC, tpashkin commented on cloud/blockstore/tools/testing/eternal_tests/range-validator/main.cpp
> +            file.Seek(blockIndex * options.BlockSize, sSet);
Смотри мой комментарий выше – O_DIRECT подразумевает, что операции кратны размеру сектора

2024-11-08 10:32 UTC, tpashkin commented on cloud/blockstore/tools/testing/eternal_tests/range-validator/main.cpp
> +                << " " << block.RequestNumber
а давай мы не будем заниматься тратой времени в one-shot туле?

2024-11-08 10:41 UTC, tpashkin commented on cloud/blockstore/tools/testing/eternal_tests/range-validator/main.cpp
> +            .StoreResult(&BlockSize);
нет, может быть 512

2024-11-10 04:05 UTC, drbasic approved these changes

2024-11-11 09:51 UTC, merged