Destroy shadow disk actor before shadow disk deallocation
ydb-platform/nbs pull request #2494
Opened 2024-11-14 08:21 UTC by drbasic

2024-11-19 14:04 UTC, budevg requested changes

2024-11-19 14:04 UTC, budevg commented on cloud/blockstore/libs/storage/volume/volume_events_private.h
> +    struct TExternalDrainDone
maybe instead of `ExtrnalDrainDone` we will call everything explicitly for example `ShadowActorDestryoDone` , `WaitForShadowActorDestroy` and etc.

2024-11-20 07:14 UTC, drbasic commented on cloud/blockstore/libs/storage/volume/volume_events_private.h
> +    struct TExternalDrainDone
I don't want the details of the implementation of another actor to be known here. Therefore, it is just a drain and it is done in an external way relative to this aсtor.

2024-11-20 08:17 UTC, budevg approved these changes

2024-11-20 10:19 UTC, komarevtsev-d approved these changes

2024-11-20 10:22 UTC, merged