Added tests, added EHistogramCounterOption to THistogram
ydb-platform/nbs pull request #2503
Opened 2024-11-14 17:36 UTC by dvrazumov

2024-12-16 10:32 UTC, sharpeye commented on cloud/blockstore/libs/storage/core/disk_counters.h
> +        EHistogramCounterOptions histCounterOptions)
\t ?

2024-12-16 10:32 UTC, sharpeye commented on cloud/blockstore/libs/storage/core/disk_counters.h
> +        EHistogramCounterOptions histCounterOptions)
\t ?

2024-12-16 10:32 UTC, sharpeye commented on cloud/blockstore/libs/storage/core/histogram_ut.cpp
> +    using TDynamicCounters = NMonitoring::TDynamicCounters;
/////

2024-12-16 10:32 UTC, sharpeye commented on cloud/blockstore/libs/storage/testlib/counters_printer.h
> +
/////

2024-12-16 10:32 UTC, sharpeye commented on cloud/blockstore/libs/storage/testlib/counters_printer.h
> +    int Level = 0;
Поля не там - в самом начале класса

2024-12-16 10:32 UTC, sharpeye commented on cloud/blockstore/libs/storage/stats_service/stats_service_state.h
> +        EHistogramCounterOptions histCounterOptions)
/t

2024-12-16 10:32 UTC, sharpeye commented on cloud/blockstore/libs/storage/stats_service/stats_service_state.h
> +        EHistogramCounterOptions histCounterOptions)
/t

2024-12-18 15:55 UTC, sharpeye approved these changes

2024-12-18 15:55 UTC, sharpeye commented on cloud/blockstore/libs/storage/core/disk_counters.h
> +        EHistogramCounterOptions histCounterOptions)
\t

2024-12-19 10:38 UTC, sharpeye approved these changes

2024-12-22 12:46 UTC, drbasic requested changes

2024-12-22 12:46 UTC, drbasic commented on cloud/blockstore/libs/diagnostics/ut_helpers.h
> +inline TDiagnosticsConfigPtr CreateDiagnosticsConfig()
код все-таки лучше выносить в cpp

2024-12-22 12:46 UTC, drbasic commented on cloud/blockstore/libs/diagnostics/ut_helpers.h
> +
настрой в редакторе чтобы добавлялись переносы строки в конце файла

2024-12-22 12:46 UTC, drbasic commented on cloud/blockstore/libs/storage/core/disk_counters.h
> +            EHistogramCounterOptions histCounterOptions)
если сохранить поле EHistogramCounterOptions в классе, то не придется все поля инициализировать в конструкторе. мне кажется удобнее инициализировать поля в месте объявления.

2024-12-22 12:46 UTC, drbasic commented on cloud/blockstore/libs/storage/core/histogram_ut.cpp
> +    using TDynamicCounterPtr = NMonitoring::TDynamicCounterPtr;
clang-format

2024-12-22 12:46 UTC, drbasic commented on cloud/blockstore/libs/storage/core/histogram_ut.cpp
> +    auto CreateTestHistogram1(
эти функции внутрь анонимного неймспеса

2024-12-22 12:46 UTC, drbasic commented on cloud/blockstore/libs/storage/core/histogram_ut.cpp
> +}  // namespace NCloud::NBlockStore::NStorage
переноса строки не хватает

2024-12-22 12:46 UTC, drbasic commented on cloud/blockstore/libs/storage/core/storage_request_counters.h
> +        : Total(histCounterOptions)
здесь тоже поле EHistogramCounterOptions лучше сохранить

2024-12-22 12:46 UTC, drbasic commented on cloud/blockstore/libs/storage/testlib/counters_printer.h
> +        Indent(Out, Level) << labelName << ':' << labelValue << " = "
код в  cpp

2024-12-22 12:46 UTC, drbasic commented on cloud/blockstore/libs/storage/testlib/counters_printer.h
> +private:
публичное наследование и приватные методы override - не видишь противоречия?
такие методы нужно делать публичными.

2024-12-22 12:46 UTC, drbasic commented on cloud/blockstore/libs/storage/partition_nonrepl/part_nonrepl_migration_common_actor.h
> +    const TDiagnosticsConfigPtr DiagnosticsConfig;
точно нужно в секцию protected ?

2025-01-02 21:36 UTC, dvrazumov commented on cloud/blockstore/libs/storage/partition_nonrepl/part_nonrepl_migration_common_actor.h
> +    const TDiagnosticsConfigPtr DiagnosticsConfig;
да, он используется в наследованных классах, например, в TShadowDiskActor

2025-01-09 10:47 UTC, drbasic commented on cloud/blockstore/libs/storage/core/disk_counters.h
> +    TCounter ActorQueue;
а тут ?

2025-01-09 10:47 UTC, drbasic commented on cloud/blockstore/libs/storage/core/disk_counters.h
> +    TCounter ReadBlocks;
и тут?

2025-01-09 10:47 UTC, drbasic commented on cloud/blockstore/libs/storage/core/disk_counters.h
> +    explicit TPartitionDiskCounters(
explicit не нужен если параметр не ровно один

2025-01-09 10:47 UTC, drbasic commented on cloud/blockstore/libs/storage/core/disk_counters.h
> +    explicit TVolumeSelfCounters(
и тут не нужен explicit

2025-01-09 10:47 UTC, drbasic commented on cloud/blockstore/libs/storage/stats_service/stats_service_state.h
> +        , VolumeAcc(policy, histCounterOptions){};
{} на новой строке и ; не нужна

2025-01-09 10:47 UTC, drbasic commented on cloud/blockstore/libs/storage/testlib/counters_printer.cpp
> +    Y_UNUSED(snapshot);
snapshot используется

2025-01-14 09:49 UTC, sharpeye submitted a review, later dismissed

2025-01-14 11:58 UTC, drbasic approved these changes

2025-01-14 12:48 UTC, sharpeye approved these changes

2025-01-14 21:36 UTC, merged