Simplify companion for GetChangedBlocksRequest
ydb-platform/nbs pull request #2536
Opened 2024-11-20 11:04 UTC by drbasic

1. В состоянии StateZombie теперь тоже обрабатываем запросы
2. Оказалось что нет смысла перенаправлять запросы в другой актор, потому что все акторы, которые могут оказаться в иерархии, отвечают ошибкой. Отвечать осмысленно умеет только TShadowDiskActor::HandleGetChangedBlocks

2024-11-20 11:05 UTC, drbasic commented on cloud/blockstore/libs/storage/partition_nonrepl/part_nonrepl_events_private.h
> -        // TODO(drbasic) remove and use non-default constructor in
Вспомнил про тудушку, и почистил ее.

2024-11-25 06:23 UTC, komarevtsev-d commented on cloud/blockstore/libs/storage/partition_common/get_changed_blocks_companion.cpp
> +void TGetChangedBlocksCompanion::RejectGetChangedBlocks(
Reject звучит как ретрабельная ошибка, а там внутри E_ARGUMENT.
Может лучше Decline?

2024-11-25 08:42 UTC, komarevtsev-d approved these changes

2024-11-25 09:24 UTC, budevg requested changes

2024-11-25 09:24 UTC, budevg commented on cloud/blockstore/libs/storage/partition_common/get_changed_blocks_companion.h
>  class TGetChangedBlocksCompanion
there is no state left in this class ... so maybe just replace this to function `DeclineGetChangedBlocks` and even move it to `part_nonrepl_common.cpp`

2024-11-25 10:06 UTC, komarevtsev-d approved these changes

2024-11-25 10:35 UTC, budevg approved these changes

2024-11-25 12:10 UTC, merged