Introduce GetDeviceForRange method and companion for it
ydb-platform/nbs pull request #2539
Opened 2024-11-20 13:03 UTC by drbasic

2024-11-27 09:14 UTC, budevg requested changes

2024-11-27 09:14 UTC, budevg commented on cloud/blockstore/libs/storage/partition_nonrepl/part_mirror_resync_ut.cpp
> +                response->Device.GetDeviceUUID(),
let's validate that we have correct `DeviceBlockRange` returned as well, here and in other tests

2024-12-01 08:44 UTC, budevg approved these changes

2024-12-02 07:19 UTC, komarevtsev-d approved these changes

2024-12-02 07:23 UTC, merged