Create direct_data_transfer.md
ydb-platform/nbs pull request #2551
Opened 2024-11-22 08:04 UTC by drbasic

2024-11-24 12:50 UTC, budevg requested changes

2024-11-24 12:50 UTC, budevg commented on doc/blockstore/direct_data_transfer.md
> +Currently, a volume is used to transfer data to a new replica or shadow disk. It reads from one ghent disk and writes data to another agent disk. This leads to a doubling of the data passing through
ghent -> agent

2024-11-24 12:50 UTC, budevg commented on doc/blockstore/direct_data_transfer.md
> +
"This leads to a doubling of the data passing through the network" -> "This doubles the amount of data transmitted over the network"

2024-11-24 12:50 UTC, budevg commented on doc/blockstore/direct_data_transfer.md
> +Next, we send the new message TEvDirectCopyBlocksRequest to the source DiskAgent and wait for execution. If an error has occurred, it is handled in the usual way at the upper level.
I wonder if it's possible in this design to somehow corrupt data. For example if after `TDirectCopyRangeActor` collects devices information from source/target actors, these actors deleted and the devices reassigned to other actors. Then the `TEvDirectCopyBlocksRequest` arrives to disk agent and overwrites new data.

2024-11-25 05:54 UTC, budevg submitted a review, later dismissed

2024-11-25 07:46 UTC, komarevtsev-d submitted a review, later dismissed

2024-11-25 10:59 UTC, komarevtsev-d commented on doc/blockstore/storage/direct_data_transfer.md
> +To collect information about devices from the source and target actors, we will send a new GetDeviceForRange request. This request should be able to handle all types of partitions and return the Disk
> This request should be able to handle all types of partitions and return the DiskAgent, device UUID, and offset for this device.

Имеется ввиду что запрос обрабатывается партишионами же?
Во-первых пропало слово nonrepl, которое не лишнее.
Во-вторых, сейчас смысл другой. Нужно тогда 
```
All types of (nonrepl ?) partitions  should be able to handle this request and return the DiskAgent, device UUID, and offset for this device.

2024-11-25 11:00 UTC, komarevtsev-d commented on doc/blockstore/storage/direct_data_transfer.md
> +The TCopyRangeActor, which copies data, has a source and a target actor. It reads data from the source and writes it to the target. We need to replicate this functionality with TDirectCopyRangeActor
minor:
destination -> target.
Лучше придерживатся терминов которые в коде.

2024-11-25 11:56 UTC, komarevtsev-d approved these changes

2024-11-27 08:01 UTC, budevg approved these changes

2024-11-27 08:10 UTC, merged