Introduce DiskAgent method DirectCopyBlocks
ydb-platform/nbs pull request #2568
Opened 2024-11-26 07:07 UTC by drbasic

2024-12-02 08:41 UTC, komarevtsev-d approved these changes

2024-12-03 16:13 UTC, budevg requested changes

2024-12-03 16:13 UTC, budevg commented on cloud/blockstore/libs/storage/disk_agent/disk_agent_actor_direct_copy.cpp
> +    LOG_INFO(
Will INFO logging here be too verbose especially if we direct copy small chunks of data ?
Additionally let's add the data range and offsets

2024-12-04 04:05 UTC, komarevtsev-d approved these changes

2024-12-04 08:41 UTC, merged