Add optional dashboard link
ydb-platform/nbs pull request #2657
Opened 2024-12-09 10:49 UTC by vladstepanyuk

#2656

2024-12-09 11:03 UTC, komarevtsev-d commented on cloud/blockstore/config/diagnostics.proto
> +    optional string MonitoringDashboardUrl = 8;
Это уже есть внутри MonitoringUrl.

2024-12-09 11:04 UTC, komarevtsev-d commented on cloud/blockstore/config/diagnostics.proto
> +    optional string MonitoringDashboardId = 9;
Тут нужно более говорящее название, типа 
`MonitoringYDBGroupDashboard`

2024-12-09 11:12 UTC, komarevtsev-d commented on cloud/blockstore/libs/storage/partition/part_actor_monitoring.cpp
> +        { BuildReassignChannelButton(out, hiveTabletId, tabletId, c); },
Не надо лишний раз форматировать что-то, если там нет смыслового diff

2024-12-09 11:13 UTC, komarevtsev-d commented on cloud/blockstore/libs/storage/partition2/part2_actor_monitoring.cpp
> +                                auto monitoringDashboardUrl = GetMonitoringDashboardYDBGroupUrl(config, latestEntry->GroupID);
Строчка длинная какая-то. clang-format?

2024-12-09 11:13 UTC, komarevtsev-d commented
Добавь скриншот с тем что получилось сюда?

2024-12-09 11:15 UTC, komarevtsev-d requested changes

2024-12-09 11:15 UTC, komarevtsev-d commented on cloud/blockstore/libs/storage/partition2/part2_actor_monitoring.cpp
> +                                auto monitoringDashboardUrl = GetMonitoringDashboardYDBGroupUrl(config, latestEntry->GroupID);
Строчка длинная какая-то. clang-format?

2024-12-10 07:49 UTC, komarevtsev-d requested changes

2024-12-10 08:09 UTC, komarevtsev-d approved these changes

2024-12-10 11:11 UTC, antonmyagkov commented on cloud/blockstore/libs/diagnostics/hostname.cpp
> +        "%s?from=now-1d&to=now&refresh=60000&p.cluster=*&p.group=%" PRIu32;
Тут не пропущен спецификатор числа?
`group=%` -> `group=%u`

2024-12-10 11:20 UTC, antonmyagkov commented on cloud/blockstore/libs/diagnostics/hostname.cpp
> +        R"(q.0.s=histogram_percentile(100, {project="kikimr", cluster="*", storagePool="%s", group="%)" PRIu32
А в чем смысл использовать PRIu32 вместо %u?

2024-12-10 11:21 UTC, antonmyagkov approved these changes

2024-12-10 11:33 UTC, komarevtsev-d commented on cloud/blockstore/libs/diagnostics/hostname.cpp
> +        R"(q.0.s=histogram_percentile(100, {project="kikimr", cluster="*", storagePool="%s", group="%)" PRIu32
На разных платформах может быть разный спецификатор формата. 
Сейчас наверно не актуально, но если будем собираться под arm, например, то может понадобиться.

2024-12-11 06:59 UTC, komarevtsev-d approved these changes

2024-12-11 11:10 UTC, antonmyagkov approved these changes

2024-12-11 11:11 UTC, merged