[Filestore] Allow to configure shards for a shard if the force flag i…
ydb-platform/nbs pull request #2675
Opened 2024-12-11 16:10 UTC by debnatkh

…s enabled

2024-12-11 18:08 UTC, qkrorlqr approved these changes

2024-12-11 18:10 UTC, qkrorlqr requested changes
давай сделаем так, чтоб можно было только обнулить список шардов шарда, но не посетить непустой список

2024-12-11 18:12 UTC, qkrorlqr requested changes
хотя не, это ок, давай только добавим пару строк в тест https://github.com/ydb-platform/nbs/blob/3dcb7664b597e6f27db483329a5a668dc03bd9df/cloud/filestore/libs/storage/service/service_ut_sharding.cpp#L3808

2024-12-11 18:44 UTC, qkrorlqr approved these changes

2024-12-12 10:07 UTC, ya-ksgamora approved these changes

2024-12-12 10:08 UTC, merged