NOTICKET: refactoring eternal db tests
ydb-platform/nbs pull request #2685
Opened 2024-12-12 13:25 UTC by ya-ksgamora

2024-12-12 13:31 UTC, debnatkh requested changes

2024-12-12 13:31 UTC, debnatkh commented on cloud/blockstore/tools/testing/eternal_tests/test_runner/lib/main.py
> +        self.run_command_in_background(
else потерялся

2024-12-12 14:02 UTC, ya-ksgamora commented on cloud/blockstore/tools/testing/eternal_tests/test_runner/lib/main.py
> +        self.run_command_in_background(
а он здесь и не нужен, команду генерит `generate_run_load_db_command`, а копировать тестовый скрипт надо только в кейсе mysql

2024-12-12 14:09 UTC, debnatkh approved these changes

2024-12-12 14:36 UTC, gy2411 approved these changes

2024-12-12 15:32 UTC, debnatkh submitted a review, later dismissed

2024-12-12 15:41 UTC, gy2411 approved these changes

2024-12-12 17:59 UTC, debnatkh approved these changes

2024-12-13 08:05 UTC, gy2411 approved these changes

2024-12-13 08:27 UTC, merged