[NBS] make new volume counters to fix UsedQuota strange values
ydb-platform/nbs pull request #2704
Opened 2024-12-16 04:39 UTC by vladstepanyuk

#2703

2024-12-16 06:38 UTC, komarevtsev-d requested changes

2024-12-16 06:38 UTC, komarevtsev-d commented on cloud/blockstore/libs/storage/volume/model/volume_throttling_policy.cpp
> +                static_cast<double>(1) / static_cast<double>(maxIops);
```suggestion
                1.0 / maxIops;
```

2024-12-16 06:38 UTC, komarevtsev-d commented on cloud/blockstore/libs/storage/volume/model/volume_throttling_policy.cpp
> +    mutable double UsedBandwidthBudget = 0;
Почему mutable?

2024-12-16 06:38 UTC, komarevtsev-d commented on cloud/blockstore/libs/storage/volume/model/volume_throttling_policy.cpp
> +}
А зачем эти flush методы?

2024-12-16 06:38 UTC, komarevtsev-d commented on cloud/blockstore/libs/storage/volume/model/volume_throttling_policy.cpp
> +                static_cast<double>(1) / static_cast<double>(maxIops);
Ну и у тебя тут получается суммируются read и write квоты. Из-за этого можно получить сумму метрик больше 100 процентов. 
Видимо нужно делить на сумму мультипликаторов (1 + `WriteCostMultiplier`)? Но не уверен.

2024-12-16 06:53 UTC, vladstepanyuk commented on cloud/blockstore/libs/storage/volume/model/volume_throttling_policy.cpp
> +}
сбросить счетчики использованного бюджета

2024-12-16 06:58 UTC, komarevtsev-d commented on cloud/blockstore/libs/storage/volume/model/volume_throttling_policy.cpp
> +}
Ну понятно. А зачем?)

2024-12-16 08:46 UTC, vladstepanyuk commented on cloud/blockstore/libs/storage/volume/model/volume_throttling_policy.cpp
> +                static_cast<double>(1) / static_cast<double>(maxIops);
добавил умножение на WriteCostMultiplier и пересчет maxIops maxBandwidth

2024-12-18 09:40 UTC, komarevtsev-d commented on cloud/blockstore/libs/storage/volume/model/volume_throttling_policy.cpp
> +    double UsedBandwidthQuota = 0;
Почему один `Budget`, а второй `Quota` ?

2024-12-18 09:43 UTC, komarevtsev-d requested changes

2024-12-18 09:43 UTC, komarevtsev-d commented on cloud/blockstore/libs/storage/volume/model/volume_throttling_policy.cpp
> +    double UsedBandwidthQuota = 0;
Почему один `Budget`, а второй `Quota` ?

2024-12-18 09:43 UTC, komarevtsev-d commented on cloud/blockstore/libs/storage/volume/volume_actor.cpp
> +    Config->GetCalculateUsedQuotaFromOtherMetrics();
Это зачем?)
Прогреваешь кеш?)

2024-12-19 05:27 UTC, komarevtsev-d commented on cloud/blockstore/libs/storage/volume/volume_actor.cpp
> +                return (usedIoQuota + usedBandwidthQuota) * 100.0;
Новая квота точно за 100 не выйдет же?

2024-12-19 05:37 UTC, vladstepanyuk commented on cloud/blockstore/libs/storage/volume/volume_actor.cpp
> +                return (usedIoQuota + usedBandwidthQuota) * 100.0;
так он же в Min(..., 100.0) обернут

2024-12-19 07:42 UTC, komarevtsev-d commented on cloud/blockstore/libs/storage/volume/volume_actor.cpp
> +                return (usedIoQuota + usedBandwidthQuota) * 100.0;
я слеп

2024-12-19 07:42 UTC, komarevtsev-d approved these changes

2024-12-19 08:26 UTC, qkrorlqr reviewed
Отдельно по iops и bandwidth считать неправильно, потому что троттлер работает не так - он троттлит не независимо по iops и по bandwidth, а считает стоимость каждого запроса и троттлит по стоимости. За секунду суммарная стоимость запросов, проходящих через троттлер, не может быть больше 1. В общем, метрика должна показывать стоимость идущего через троттлер потока запросов, умноженную на 100 (чтоб получились проценты)

2024-12-19 10:45 UTC, drbasic commented on cloud/blockstore/libs/storage/volume/volume_actor.cpp
> +        [&]()
100 * (Config->GetCalculateUsedQuotaFromOtherMetrics() ? (usedIopsQuota + usedBandwidthQuota): tp.CalculateCurrentSpentBudgetShare(ctx.Now()) )

2024-12-19 11:40 UTC, vladstepanyuk commented
> Отдельно по iops и bandwidth считать неправильно, потому что троттлер работает не так - он троттлит не независимо по iops и по bandwidth, а считает стоимость каждого запроса и троттлит по стоимости. 

Сейчас стоимость считается таким образом 
```
const auto recalculatedMaxIops =
            CalculateThrottlerC1(maxIops, maxBandwidth);
const auto recalculatedMaxBandwidth =
            CalculateThrottlerC2(maxIops, maxBandwidth);

double cost = m * (1.0 / static_cast<double>(recalculatedMaxIops) + static_cast<double>(byteCount)
        / static_cast<double>(maxBandwidth));

```
метрика UsedIopsQuota:
https://github.com/ydb-platform/nbs/blob/89f0f43ac1ecdabe4f9dec5c99d82ca7fcb69c6c/cloud/blockstore/libs/storage/volume/model/volume_throttling_policy.cpp#L269

метрика UsedBandwidthQuota:
https://github.com/ydb-platform/nbs/blob/89f0f43ac1ecdabe4f9dec5c99d82ca7fcb69c6c/cloud/blockstore/libs/storage/volume/model/volume_throttling_policy.cpp#L265-L267

т.е. в сумме они дают реальную стоимость, которая идет в тротлер, просто разделены на 2 слагаемых.

2024-12-19 11:50 UTC, komarevtsev-d approved these changes

2024-12-25 11:22 UTC, drbasic approved these changes

2024-12-25 11:47 UTC, drbasic submitted a review, later dismissed

2025-01-09 07:40 UTC, komarevtsev-d submitted a review, later dismissed

2025-01-13 08:55 UTC, drbasic submitted a review, later dismissed

2025-01-15 15:45 UTC, SvartMetal commented on cloud/blockstore/config/storage.proto
> +    optional bool CalculateUsedQuotaFromOtherMetrics = 397;
SplitUsedQuotaMetric?

или CalculateSplittedUsedQuotaMetric

2025-01-15 15:50 UTC, SvartMetal commented on cloud/blockstore/libs/storage/volume/model/volume_throttling_policy.cpp
> +                         static_cast<double>(recalculatedMaxBandwidth));
хочется писать код так чтобы было очевидно что деление на ноль невозможно, а тут для верификации придётся заглянуть ещё в CalculateThrottlerC1, CalculateThrottlerC2

2025-01-15 15:51 UTC, SvartMetal commented on cloud/blockstore/libs/storage/volume/model/volume_throttling_policy.cpp
> +            UsedIopsQuota += m * (1.0 / recalculatedMaxIops);
как защищаемся от деления на ноль?

2025-01-15 15:52 UTC, SvartMetal commented on cloud/blockstore/libs/storage/volume/model/volume_throttling_policy.cpp
> +    std::pair<double, double> TakeUsedQuota()
TakeSplittedUsedQuota

2025-01-15 15:53 UTC, SvartMetal commented on cloud/blockstore/libs/storage/volume/model/volume_throttling_policy.h
> +    // Returns pair of UsedIopsQuota and UsedBandwidthQuota.
лучше для таких вещей структуру использовать

2025-01-15 16:00 UTC, SvartMetal commented on cloud/blockstore/libs/storage/volume/model/volume_throttling_policy.cpp
> +    std::pair<double, double> TakeUsedQuota()
либо 

`TUsedQuota TakeUsedQuota()`

`
struct TUsedQuota
{
    double Iops;
    double Bandwidth;
};
`

2025-01-15 16:05 UTC, SvartMetal commented on cloud/blockstore/libs/storage/volume/volume_actor.cpp
> +            100.0));
мне кажется будет лучше читаться если разбить это выражение на части

2025-01-15 16:06 UTC, SvartMetal commented on cloud/blockstore/libs/storage/volume/volume_actor.cpp
> +            100.0));
да и выше уже есть умножение на 100 https://github.com/ydb-platform/nbs/pull/2704/files#diff-13e7a0dbb3c30c992076ae6b62b382577b15a1d98ca685134fc80dc7ce4c7814R222

2025-01-15 16:11 UTC, SvartMetal commented on cloud/blockstore/libs/storage/volume/model/volume_throttling_policy.cpp
> +    std::pair<double, double> TakeUsedQuota()
хотя наверное лучше явно сказать что это splitted used quota

TSplittedUsedQuota TakeSplittedUsedQuota

2025-01-16 04:57 UTC, vladstepanyuk commented on cloud/blockstore/libs/storage/volume/model/volume_throttling_policy.cpp
> +            UsedIopsQuota += m * (1.0 / recalculatedMaxIops);
добавил панику в случае нуля
https://github.com/ydb-platform/nbs/blob/9d885ed061a5667c4500dc951e655e6f827d883b/cloud/blockstore/libs/storage/volume/model/volume_throttling_policy.cpp#L250-L252

2025-01-16 09:54 UTC, vladstepanyuk commented on cloud/blockstore/libs/storage/volume/model/volume_throttling_policy_ut.cpp
> +        const auto [usedIopsQuota, usedBandwidthQuota] = tp.TakeUsedQuota();
поправить вызов функции

2025-01-17 13:46 UTC, SvartMetal commented on cloud/blockstore/libs/storage/volume/model/volume_throttling_policy.cpp
> +            UsedIopsQuota += m * (1.0 / recalculatedMaxIops);
не надо панику пожалуйста

в релизе тут всё равно крэш будет

2025-01-17 13:47 UTC, SvartMetal commented on cloud/blockstore/libs/storage/volume/model/volume_throttling_policy.h
> +        double Iops;
= 0;

на всякий случай

2025-01-17 13:47 UTC, SvartMetal commented on cloud/blockstore/libs/storage/volume/model/volume_throttling_policy.h
> +    // Returns pair of UsedIopsQuota and UsedBandwidthQuota.
комментарий уже не актуален

2025-01-17 13:48 UTC, SvartMetal commented on cloud/blockstore/libs/storage/volume/model/volume_throttling_policy_ut.cpp
> +        auto [usedIopsQuotaAfterTake, usedBandwidthQuotaAfterTake] =
суффикс AfterTake не нужен

2025-01-17 13:49 UTC, SvartMetal commented on cloud/blockstore/libs/storage/volume/model/volume_throttling_policy_ut.cpp
> +    Y_UNIT_TEST(CollectThrotlingDiagnostics)
CalculateSpliitedUsedQuota

2025-01-17 13:49 UTC, SvartMetal commented on cloud/blockstore/libs/storage/volume/model/volume_throttling_policy_ut.cpp
> +        const auto [usedIopsQuota, usedBandwidthQuota] =
зачем работать со структурой как с туплом?

2025-01-17 13:51 UTC, SvartMetal commented on cloud/blockstore/libs/storage/volume/volume_actor.cpp
> +    const auto [usedIopsQuotaPrecentage, usedBandwidthQuotaPrecentage] = [&]()
Precentage -> Percentage

2025-01-17 13:51 UTC, SvartMetal commented on cloud/blockstore/libs/storage/volume/volume_actor.cpp
> +    }();
зачем тут лямбда?

2025-01-17 13:53 UTC, SvartMetal commented on cloud/blockstore/libs/storage/volume/model/volume_throttling_policy_ut.cpp
> +    Y_UNIT_TEST(UsedBandwidthQuotaZeroWithoutBytesThrotling)
Throttling

2025-01-17 13:54 UTC, SvartMetal commented on cloud/blockstore/libs/storage/volume/model/volume_throttling_policy_ut.cpp
> +    Y_UNIT_TEST(UsedBandwidthQuotaZeroWithoutBytesThrotling)
По названию теста не понятна его суть

2025-01-17 13:54 UTC, SvartMetal commented on cloud/blockstore/libs/storage/volume/model/volume_throttling_policy_ut.cpp
> +
лишний отступ

2025-01-17 13:55 UTC, SvartMetal commented on cloud/blockstore/libs/storage/volume/model/volume_throttling_policy_ut.cpp
> +        const auto ioOperation = 2;
requestCount?

2025-01-18 15:51 UTC, vladstepanyuk commented on cloud/blockstore/libs/storage/volume/model/volume_throttling_policy.cpp
> +            UsedIopsQuota += m * (1.0 / recalculatedMaxIops);
как я понимаю, тут предполагается, что значение recalculatedMaxIops никогда не равно нулю, т.к. это значение и раньше передавалось в функцию CostPerIO, где так же происзодит паника в случае 0 и затем обычное деление без проверок
https://github.com/ydb-platform/nbs/blob/d73c679b1ba4a7a2529b4b9f34aed9534874f034/cloud/storage/core/libs/throttling/helpers.cpp#L48-L61

2025-01-18 15:56 UTC, vladstepanyuk commented on cloud/blockstore/libs/storage/volume/model/volume_throttling_policy_ut.cpp
> +    Y_UNIT_TEST(UsedBandwidthQuotaZeroWithoutBytesThrotling)
поменял на CalculateSplittedUsedQuotaCorrectlyWhenBytesThrottlingDisabled

2025-01-20 10:55 UTC, SvartMetal commented on cloud/blockstore/libs/storage/volume/model/volume_throttling_policy_ut.cpp
> +    Y_UNIT_TEST(CalculateSplittedUsedQuotaCorrectlyWhenBytesThrottlingDisabled)
Что такое BytesThrottling?

Имеется ввиду ThrottlingByBandwidth?

2025-01-20 11:52 UTC, SvartMetal approved these changes

2025-01-20 12:44 UTC, komarevtsev-d approved these changes

2025-01-20 13:30 UTC, merged