issue-2713: add version on da stub mon page
ydb-platform/nbs pull request #2714
Opened 2024-12-17 04:13 UTC by vladstepanyuk

#2713 
![image](https://github.com/user-attachments/assets/76ba9f4c-20a0-4910-85dc-e1314fe5b7b1)

2024-12-17 07:10 UTC, komarevtsev-d commented on cloud/blockstore/libs/disk_agent/bootstrap.cpp
> +    std::stringstream stubMonPageBuilder;
`TStringBuilder`

2024-12-17 07:10 UTC, komarevtsev-d commented on cloud/blockstore/libs/disk_agent/bootstrap.cpp
> +    Cerr << stubMonPageBuilder.str() << Endl;
Cerr

2024-12-17 09:24 UTC, SvartMetal commented
Давайте писать аббревиатуры нормально da -> DA

2024-12-18 06:58 UTC, komarevtsev-d submitted a review, later dismissed

2024-12-18 09:50 UTC, sharpeye commented on cloud/blockstore/libs/disk_agent/bootstrap.cpp
> +#include "library/cpp/build_info/build_info_static.h"
`#include <library/cpp/build_info/build_info_static.h>`

2024-12-18 09:50 UTC, sharpeye commented on cloud/blockstore/libs/disk_agent/bootstrap.cpp
> +    const auto* version = GetProgramSvnVersion();
Можно в TStringBuf сложить версию

2024-12-18 11:48 UTC, sharpeye commented on cloud/blockstore/libs/disk_agent/bootstrap.cpp
> +#include <library/cpp/build_info/build_info_static.h>
Разве нужен не `library/cpp/svnversion/svnversion.h` ?

2024-12-18 11:48 UTC, sharpeye commented on cloud/blockstore/libs/disk_agent/bootstrap.cpp
> +    if (!TString(version).EndsWith("\n")) {
У TStringBuf тоже есть EndsWith:
```cpp
if (!version.EndsWith("\n")) {
```
Но вообще, можно без временной переменной:
```cpp
stubMonPageBuilder << GetProgramSvnVersion();
if (!stubMonPageBuilder.EndsWith("\n")) {
    stubMonPageBuilder << "\n";
}
```

2024-12-19 05:18 UTC, komarevtsev-d requested changes
Замечания тут не все исправлены

2024-12-19 10:24 UTC, sharpeye approved these changes

2024-12-19 10:36 UTC, merged