issue-2715: add critical events for NBS-3726
ydb-platform/nbs pull request #2716
Opened 2024-12-17 06:18 UTC by vladstepanyuk

#2715

2024-12-17 07:20 UTC, komarevtsev-d requested changes

2024-12-17 07:20 UTC, komarevtsev-d commented on cloud/blockstore/libs/storage/disk_registry/disk_registry_state.cpp
> +            if (std::ranges::find(disk.Devices, deviceId) == disk.Devices.end())
```suggestion
            if (Find(disk.Devices, deviceId) == disk.Devices.end())
```

2024-12-17 07:20 UTC, komarevtsev-d commented on cloud/blockstore/libs/diagnostics/critical_events.h
> +    xxx(DiskRegistryMigrationOfNotFoundDisk)                                   \
```suggestion
    xxx(DiskRegistryWrongMigratedDeviceOwnership)                                   \
```

2024-12-17 09:25 UTC, SvartMetal commented
Что за NBS-3726?
Нужно нормальное описание

2024-12-18 05:54 UTC, vladstepanyuk commented
> Что за NBS-3726? Нужно нормальное описание

NBS-3726 это из коментария в коде. Описание поправил, расписал в чем проблема.

2024-12-18 06:58 UTC, komarevtsev-d submitted a review, later dismissed

2024-12-18 10:02 UTC, sharpeye commented on cloud/blockstore/libs/storage/disk_registry/disk_registry_state.cpp
> +                ReportDiskRegistryWrongMigratedDeviceOwnership(
Нужно добавить информацию о том, из какой функции вызывается DiskRegistryWrongMigratedDeviceOwnership - чтобы проще было потом дебажить.

2024-12-18 10:26 UTC, komarevtsev-d commented on cloud/blockstore/libs/storage/disk_registry/disk_registry_state.cpp
> +                    TStringBuilder() << __PRETTY_FUNCTION__ << ": device "
Да словами просто напиши )
`ApplyAgentStateChange`

2024-12-18 10:33 UTC, komarevtsev-d approved these changes

2024-12-19 11:48 UTC, merged