Issue 2709: add cleanup of leaked devices
ydb-platform/nbs pull request #2745
Opened 2024-12-20 11:11 UTC by vladstepanyuk

#2709

2024-12-20 11:14 UTC, vladstepanyuk commented on cloud/blockstore/libs/storage/disk_registry/model/device_list.h
> +    GetAllDevices() const;
GetAllDevices

2024-12-20 11:15 UTC, vladstepanyuk commented on cloud/blockstore/libs/storage/disk_registry/model/device_list.cpp
> +TDeviceList::GetAllDevices() const
убрать

2024-12-23 06:23 UTC, drbasic requested changes

2024-12-23 06:23 UTC, drbasic commented on cloud/blockstore/libs/storage/disk_registry/ya.make
> +    disk_registry_actor_cleanupdeviceswithoutagent.cpp
сleanup_devices_without_agent

2024-12-23 06:23 UTC, drbasic commented on cloud/blockstore/libs/storage/disk_registry/testlib/test_state.cpp
> +        db.ReadDiskRegistryAgentListParams(builder.DiskRegistryAgentListParams),
убери последнюю запятую и clang-format

2024-12-23 06:23 UTC, drbasic commented on cloud/blockstore/libs/storage/disk_registry/disk_registry_state.cpp
> +    auto filterLeakedDevices = [&](const TString& id)
isDeviceUnknown(const TString& deviceUUID)

2024-12-23 06:23 UTC, drbasic commented on cloud/blockstore/libs/storage/disk_registry/disk_registry_state.cpp
> +            const auto& deviceId = device.GetDeviceUUID();
deviceUUID

2024-12-23 06:23 UTC, drbasic commented on cloud/blockstore/libs/storage/disk_registry/disk_registry_state.cpp
> +    auto addIdToVector = [&](TString id)
addIdToVector не улучшает читаемость. лучше без нее, напрямую добавлять в devicesToRemoveVector

2024-12-23 06:23 UTC, drbasic commented on cloud/blockstore/libs/storage/disk_registry/disk_registry_state.cpp
> +    TVector<TString> devicesToRemoveVector;
devicesToRemoveVector -> devicesToRemove

2024-12-23 06:23 UTC, drbasic commented on cloud/blockstore/libs/storage/disk_registry/disk_registry_state.cpp
> +            auto idIt = AutomaticallyReplacedDeviceIds.find(id);
idIt -> it

2024-12-23 06:23 UTC, drbasic commented on cloud/blockstore/libs/storage/disk_registry/disk_registry_state.cpp
> +        {
помещать в {} не нужно

2024-12-23 06:23 UTC, drbasic commented on cloud/blockstore/libs/storage/disk_registry/disk_registry_state.cpp
> +            if (idIt != AutomaticallyReplacedDeviceIds.end()) {
вызова DeleteAutomaticallyReplacedDevice() не достаточно?

2024-12-23 10:46 UTC, drbasic commented on cloud/blockstore/libs/storage/disk_registry/disk_registry_state.cpp
> +    SortUnique(devicesToRemove);
Давай в лог отпишем что нашли такие-то девайсы и что мы их чистим.

2024-12-23 10:48 UTC, drbasic commented on cloud/blockstore/libs/storage/disk_registry/disk_registry_state.h
> +    void CleanupDevices(TDiskRegistryDatabase& db);
имя метода уточни, какие девайсы чистятся

2024-12-23 11:13 UTC, vladstepanyuk commented on cloud/blockstore/libs/storage/disk_registry/disk_registry_state.cpp
> +    SortUnique(devicesToRemove);
Добавил логирование внутрь тела транзакции https://github.com/ydb-platform/nbs/blob/890da703e4e8bfdaf91be5e24510ebbaf76eb65d/cloud/blockstore/libs/storage/disk_registry/disk_registry_actor_cleanup_devices_without_agent.cpp#L34-L40

чтобы не прокидывать контекст актора в состояние

2024-12-23 13:33 UTC, drbasic requested changes

2024-12-23 13:33 UTC, drbasic commented on cloud/blockstore/libs/storage/disk_registry/disk_registry_actor_cleanup_devices_without_agent.cpp
> +    LOG_INFO(
давай писать в лог только если что-то сделали

2024-12-23 14:55 UTC, sharpeye commented on cloud/blockstore/libs/storage/disk_registry/disk_registry_actor_cleanup_devices_without_agent.cpp
> +#include "util/string/join.h"
`#include <...>`

2024-12-23 14:55 UTC, sharpeye commented on cloud/blockstore/libs/storage/disk_registry/disk_registry_tx.h
> +    struct TCleanupDevicesWithoutAgent
TRemoveOrphanDevices ?

2024-12-23 14:55 UTC, sharpeye commented on cloud/blockstore/libs/storage/disk_registry/model/device_list.cpp
> +    return devices;
```cpp
return {DirtyDevices.cbegin(), DirtyDevices.cend()};
```

2024-12-23 14:55 UTC, sharpeye commented on cloud/blockstore/libs/storage/disk_registry/disk_registry_actor_loadstate.cpp
> +    ExecuteTx<TCleanupDevicesWithoutAgent>(ctx);
Заводим функцию FindOrphanDevices:
```cpp
if (auto orphanDevices: State->FindOrphanDevices()) {
    LOG_INFO(...);
    RemoveOrphanDevices(ctx, std::move(orphanDevices));
}
```

2024-12-23 14:55 UTC, sharpeye commented on cloud/blockstore/libs/storage/disk_registry/disk_registry_state.cpp
> +    }
Не надо пока ranges:
```cpp
for (auto& device: DeviceList.GetSuspendedDevices()) {
    if (!allKnownDevicesWithAgents.contains(device.GetId())) {
        devicesWithoutAgentToRemove.emplace_back(
            std::move(*device.MutableId()));
    }
}
```

2024-12-23 14:55 UTC, sharpeye commented on cloud/blockstore/libs/storage/disk_registry/testlib/test_state.cpp
> +std::optional<TDiskRegistryStateBuilder> TDiskRegistryStateBuilder::LoadState(
Зачем это понадобилось?

2024-12-24 06:10 UTC, vladstepanyuk commented on cloud/blockstore/libs/storage/disk_registry/disk_registry_actor_loadstate.cpp
> +    ExecuteTx<TCleanupDevicesWithoutAgent>(ctx);
Как мне кажется разделять метод CleanupOrphanDevices на FindOrphanDevices и ForgetDevices не очень, так как надо будет делать метод ForgetDevices публичным, что даст больше возсожностей для ошибки и удаления не утекших девайсов и также в этом, как будто бы, нет необходимости.

Если суть комментария была в том, чтобы лишний раз не запускать транзакцию очистки, то можно сделать так:
https://github.com/ydb-platform/nbs/blob/79f7c5b799bf02137528c2a92b32700a57a69590/cloud/blockstore/libs/storage/disk_registry/disk_registry_actor_loadstate.cpp#L205-L207

2024-12-24 06:13 UTC, vladstepanyuk commented on cloud/blockstore/libs/storage/disk_registry/testlib/test_state.cpp
> +std::optional<TDiskRegistryStateBuilder> TDiskRegistryStateBuilder::LoadState(
в тестах я сначала задаю какое-то состояние через класс TDiskRegistryState и бдшку и затем это состояние подгружаю из бд и для него запускаю очистку, мне показалось, что так будет удобнее чем руками прописывать состояние.

2024-12-24 07:03 UTC, drbasic commented on cloud/blockstore/libs/storage/disk_registry/disk_registry_tx.h
> +    xxx(CleanupOrphanDevices,         __VA_ARGS__)                       \
съехало

2024-12-24 07:11 UTC, drbasic submitted a review, later dismissed

2024-12-25 20:12 UTC, sharpeye commented on cloud/blockstore/libs/storage/disk_registry/disk_registry_state_ut.cpp
> +Y_UNIT_TEST(ShouldCleanupAlreadyLeakedDevices)
\t

2024-12-25 20:12 UTC, sharpeye commented on cloud/blockstore/libs/storage/disk_registry/testlib/test_state.cpp
> +}   // namespace
Это уже не нужно?

2024-12-25 20:12 UTC, sharpeye commented on cloud/blockstore/libs/storage/disk_registry/disk_registry_tx.h
> +        const TRequestInfoPtr RequestInfo;
RequestInfo не используется?

2024-12-25 20:12 UTC, sharpeye commented on cloud/blockstore/libs/storage/disk_registry/disk_registry_actor_cleanup_orphan_devices.cpp
> +            JoinSeq(" ", args.OrphanDevices).c_str());
Это сообщение логичнее унести туда, где действительно искали девайсы.

2024-12-25 20:12 UTC, sharpeye commented on cloud/blockstore/libs/storage/disk_registry/disk_registry_actor_cleanup_orphan_devices.cpp
> +    Y_UNUSED(args);
Это не нужно

2024-12-27 11:52 UTC, drbasic submitted a review, later dismissed

2024-12-27 12:58 UTC, sharpeye commented on cloud/blockstore/libs/storage/disk_registry/disk_registry_tx.h
> +    struct TCleanupOrphanDevices
У нас есть транзакция [TCleanupDevices](https://github.com/ydb-platform/nbs/blob/9e190a164a7442f80d28fbe7f897f4802d49845f/cloud/blockstore/libs/storage/disk_registry/disk_registry_tx.h#L303) , которая чистит девайсы. А TCleanupOrphanDevices удаляет девайсы. Давай переименуем в TRemoveOrphanDevices.

2025-01-09 09:24 UTC, vladstepanyuk commented on cloud/blockstore/libs/storage/disk_registry/disk_registry_tx.h
> +        const TRequestInfoPtr RequestInfo;
Без поля RequestInfo не собирается, сделал наличие этого поля опциональным

2025-01-09 10:12 UTC, komarevtsev-d approved these changes

2025-01-09 10:52 UTC, sharpeye approved these changes

2025-01-09 12:03 UTC, merged