[Blockstore] preventing the rejection of a significant fraction of Disk Agents in the cluster
ydb-platform/nbs pull request #2746
Opened 2024-12-20 11:37 UTC by sharpeye

2024-12-21 13:57 UTC, qkrorlqr requested changes
#issue

2024-12-24 13:24 UTC, komarevtsev-d submitted a review, later dismissed

2024-12-27 17:49 UTC, tpashkin submitted a review, later dismissed

2024-12-27 18:05 UTC, qkrorlqr approved these changes

2024-12-29 14:37 UTC, merged