add fs and fs shard counters
ydb-platform/nbs pull request #2756
Opened 2024-12-23 18:55 UTC by yegorskii

2024-12-23 19:30 UTC, qkrorlqr commented on cloud/filestore/libs/storage/tablet/tablet_actor.h
> +        std::atomic<i64> FsCount{0};
э, что еще за FsCount у конкретной таблетки? он же должен быть равен единице
не надо его тут

2024-12-23 19:31 UTC, qkrorlqr commented on cloud/filestore/libs/storage/tablet/tablet_actor.h
> +        std::atomic<i64> FsShardCount{0};
просто ShardCount

2024-12-23 19:31 UTC, qkrorlqr requested changes
ut

2024-12-24 16:57 UTC, yegorskii commented on cloud/filestore/libs/storage/tablet/tablet_actor.h
> +        std::atomic<i64> FsCount{0};
Он не будет репортиться в метрики соответствующей фс. Так же как и следующий. будет только в аггрегированном виде в component=storage

2024-12-30 10:13 UTC, qkrorlqr commented on cloud/filestore/libs/storage/tablet/tablet_actor.h
> +        std::atomic<i64> FsCount{0};
нет, выглядит странно
https://github.com/ydb-platform/nbs/blob/d43b5bb0517273371560d5800bb0d6eed355c094/cloud/filestore/libs/storage/service/service_actor_update_stats.cpp#L19 - почему ты не можешь вот в этой ф-ции посчитать TabletCount и FileSystemCount (название FsCount тоже ну, блин, режет глаз - у нас везде FileSystem)?

2024-12-31 15:50 UTC, yegorskii commented on cloud/filestore/libs/storage/tablet/tablet_actor.h
> +        std::atomic<i64> FsCount{0};
Я не понимаю, зачем считать руками то что за меня могут посчитать автоматически в storage (придется пробрасывать в сервис информацию о том является ли таблетка шардом или нет и еще пересчитывать с учетом media kind). Зачем тащить в сервис то что ему совершенно не нужно?

2025-01-17 13:53 UTC, closed without merging