[NBS] Issue 2732: add change device/agent state buttons
ydb-platform/nbs pull request #2760
Opened 2024-12-24 07:50 UTC by vladstepanyuk

#2732

2024-12-24 12:13 UTC, sharpeye commented on cloud/blockstore/libs/storage/disk_registry/disk_registry_actor_change_agent_state.cpp
> +                << static_cast<int>(NewState) << ": " << FormatError(error),
NewState в поток разве не выводится правильно, как имя AGENT_STATE_ONLINE и тд?

2024-12-24 12:13 UTC, sharpeye commented on cloud/blockstore/libs/storage/disk_registry/disk_registry_actor_change_agent_state.cpp
> +    auto newState = it->first;
Сначала присваиваем, а потом проверяем на валидность?

2024-12-24 12:13 UTC, sharpeye commented on cloud/blockstore/libs/storage/disk_registry/disk_registry_actor_change_agent_state.cpp
> +        [&](const auto& state) { return state.second == newStateRaw; });
Протобуф генерит EAgentState_Parse - её можно использовать вместо ручной проверки:
```cpp
NProto::EAgentState newState;
if (!EAgentState_Parse(newStateRaw, &newState)) {
    // 
}
```

2024-12-24 12:13 UTC, sharpeye commented on cloud/blockstore/libs/storage/disk_registry/disk_registry_actor_change_device_state.cpp
> +                << " state to " << static_cast<int>(NewState) << ": " << FormatError(error),
>80

2024-12-24 12:13 UTC, sharpeye commented on cloud/blockstore/libs/storage/disk_registry/disk_registry_actor_change_device_state.cpp
> +    if (it == NewStateWhiteList.end()) {
EDeviceState_Parse

2024-12-24 12:13 UTC, sharpeye commented on cloud/blockstore/libs/storage/disk_registry/disk_registry_actor_monitoring.cpp
> +                BuildChangeDeviceStateButton(
Не стоит ли эти кнопки спрятать под фичефлаг? Как это сделано для Replace

2024-12-24 15:41 UTC, drbasic commented on cloud/blockstore/libs/storage/disk_registry/disk_registry_actor_monitoring.cpp
> +                BuildChangeDeviceStateButton(
 переводить warn в online  и обратно кажется относительно безопасно.

2024-12-25 04:54 UTC, vladstepanyuk commented on cloud/blockstore/libs/storage/disk_registry/disk_registry_actor_change_agent_state.cpp
> +                << static_cast<int>(NewState) << ": " << FormatError(error),
У меня с просто ```out << NewState``` не линковалось, поправил на  ```out << EAgentState_Name(NewState)```

2024-12-25 05:06 UTC, drbasic requested changes

2024-12-25 05:06 UTC, drbasic commented on cloud/blockstore/libs/storage/disk_registry/disk_registry_actor_change_agent_state.cpp
> +    if (newState == NProto::EAgentState::AGENT_STATE_UNAVAILABLE) {
давай наоборот проверять по белому списку

2024-12-25 05:06 UTC, drbasic commented on cloud/blockstore/libs/storage/disk_registry/disk_registry_actor_change_device_state.cpp
> +    const TActorId& owner,
тут тоже сдвинуть вправо

2024-12-25 05:06 UTC, drbasic commented on cloud/blockstore/libs/storage/disk_registry/disk_registry_actor_change_device_state.cpp
> +        std::make_unique<NMon::TEvRemoteHttpInfoRes>(std::move(out.Str()));
std::move() лишний

2024-12-25 05:06 UTC, drbasic commented on cloud/blockstore/libs/storage/disk_registry/disk_registry_actor_change_device_state.cpp
> +    if (newState == NProto::EDeviceState::DEVICE_STATE_ERROR) {
тут тоже по белому списку

2024-12-25 05:06 UTC, drbasic commented on cloud/blockstore/libs/storage/disk_registry/disk_registry_actor_change_device_state.cpp
> +    if (device.GetState() == NProto::DEVICE_STATE_ERROR) {
@sharpeye 
Паша, что думаешь, может разрешить из ошибки переводить?
у нас есть такие девайсы которые ошибочно в ошибке висят.

2024-12-25 20:03 UTC, sharpeye commented on cloud/blockstore/libs/storage/disk_registry/disk_registry_actor_change_device_state.cpp
> +    if (device.GetState() == NProto::DEVICE_STATE_ERROR) {
Мне, если честно, вообще идея изменения состояний агентов/девайсов в не тестовых фолдерах/кластерах кажется не очень - можно наизменять всякого, тикета нет - концы искать сложно будет.

2025-01-09 10:50 UTC, komarevtsev-d commented on cloud/blockstore/libs/storage/disk_registry/disk_registry_actor_monitoring.cpp
> +            BuildChangeAgentStateButton(out, TabletID(), agent->GetAgentId());
А почему тут нет проверки состояния агента как у девайса выше?

2025-01-09 11:02 UTC, sharpeye commented on cloud/blockstore/libs/storage/disk_registry/disk_registry_actor_change_device_state.cpp
> +    if (device.GetState() == NProto::DEVICE_STATE_ERROR) {
@drbasic м.б. под флажок убрать? Вы себе его включите и сможете с монстаницы как угодно стейты менять.

2025-01-10 06:58 UTC, vladstepanyuk commented on cloud/blockstore/libs/storage/disk_registry/disk_registry_actor_change_device_state.cpp
> +    if (device.GetState() == NProto::DEVICE_STATE_ERROR) {
убрал под отдельные флаги сами кнопки и перевод из состояния Error/Unavailable

2025-01-10 07:21 UTC, komarevtsev-d requested changes

2025-01-10 07:21 UTC, komarevtsev-d commented on cloud/blockstore/config/storage.proto
> +    optional bool EnableToChangeStatesFromMonpage = 397;
```suggestion
    optional bool EnableToChangeStatesFromDiskRegistryMonpage = 397;
```

2025-01-10 07:21 UTC, komarevtsev-d commented on cloud/blockstore/config/storage.proto
> +    optional bool EnableToChangeErrorStatesFromMonpage = 398;
```suggestion
    optional bool EnableToChangeErrorStatesFromDiskRegistryMonpage = 398;
```

2025-01-10 07:21 UTC, komarevtsev-d commented on cloud/blockstore/libs/storage/disk_registry/disk_registry_actor_change_agent_state.cpp
> +        }
Мне кажется это не имеет смысла. Агента практически никогда не нужно ни вводить в UNAVAILABLE, ни наоборот выводить оттуда.
В UI только мешать будет к.м.к

2025-01-10 07:21 UTC, komarevtsev-d commented on cloud/blockstore/libs/storage/disk_registry/disk_registry_actor_change_agent_state.cpp
> +    request->Record.SetAgentState(NewState);
Добавь reason? 
Это сообщение будет видно после изменения состояния. Нужно чтобы было понятно что из юайчика состояние меняли

2025-01-10 07:21 UTC, komarevtsev-d commented on cloud/blockstore/libs/storage/disk_registry/disk_registry_actor_change_device_state.cpp
> +    request->Record.SetDeviceState(NewState);
И тут reason

2025-01-10 07:21 UTC, komarevtsev-d commented on cloud/blockstore/libs/storage/disk_registry/disk_registry_actor_change_device_state.cpp
> +                             << ": " << FormatError(error),
Совсем красота будет если передашь в актор старое состояние агента/девайса и напишешь его здесь

2025-01-10 07:21 UTC, komarevtsev-d commented on cloud/blockstore/libs/storage/disk_registry/disk_registry_actor_change_agent_state.cpp
> +    static const THashSet<NProto::EAgentState> NewStateWhiteList{
`WhiteList` -> `Allowlist`

2025-01-10 07:21 UTC, komarevtsev-d commented on cloud/blockstore/libs/storage/disk_registry/disk_registry_actor_change_device_state.cpp
> +        "Change state of device[%s] from monitoring page to %s",
И тут тоже лучше залогировать с какого состояния переводим

2025-01-13 07:11 UTC, komarevtsev-d commented on cloud/blockstore/libs/storage/disk_registry/disk_registry_actor_change_device_state.cpp
> +        "Changing state of device[%s] from monitoring page from %s to %s",
on moniting page

2025-01-13 07:45 UTC, komarevtsev-d approved these changes

2025-01-13 11:11 UTC, sharpeye commented on cloud/blockstore/libs/storage/disk_registry/disk_registry_actor_change_device_state.cpp
> +        NProto::EDeviceState::DEVICE_STATE_ONLINE,
Должно работать без указания `EDeviceState`: `NProto::DEVICE_STATE_ONLINE`

2025-01-15 10:07 UTC, sharpeye commented on cloud/blockstore/libs/storage/disk_registry/disk_registry_actor_change_device_state.cpp
> +    if (SUCCEEDED(error.GetCode())) {
`!HasError(error)`

2025-01-15 10:07 UTC, sharpeye commented on cloud/blockstore/libs/storage/disk_registry/disk_registry_actor_change_agent_state.cpp
> +    if (SUCCEEDED(error.GetCode())) {
`!HasError(error)`

2025-01-15 11:18 UTC, sharpeye approved these changes

2025-01-15 11:23 UTC, sharpeye approved these changes

2025-01-15 11:26 UTC, komarevtsev-d approved these changes

2025-01-16 05:07 UTC, merged