issue-2725: add direct acruire release disk sending
ydb-platform/nbs pull request #2767
Opened 2024-12-27 06:49 UTC by vladstepanyuk

#2725

2024-12-27 18:53 UTC, komarevtsev-d requested changes

2024-12-27 18:53 UTC, komarevtsev-d commented on cloud/blockstore/libs/storage/volume/volume_state.h
> +    bool AcquireInProgress = false;
Зачем эта булка, если в volume уже есть `AcquireReleaseDiskRequests` ?

2024-12-27 18:53 UTC, komarevtsev-d commented on cloud/blockstore/libs/storage/volume/volume_actor_acquire.cpp
> +    }
девайсы заполняются и тут и в `StartAcquireDisk` выше. Надо как-то в одном месте.

2024-12-27 18:53 UTC, komarevtsev-d commented on cloud/blockstore/libs/storage/volume/volume_actor_acquire.cpp
> +        }
А есть гарантия что у нас не будет нескольких запросов в одного агента?

2024-12-27 18:53 UTC, komarevtsev-d commented on cloud/blockstore/libs/storage/volume/volume_events_private.h
> +        NProto::TReleaseDiskResponse ResponceRecord;
```suggestion
        NProto::TReleaseDiskResponse ResponseRecord;
```

2024-12-27 18:53 UTC, komarevtsev-d commented on cloud/blockstore/libs/storage/volume/volume_events_private.h
> +    };
Не обязательно делать Response сообщеньки, если они не нужны. 
И не все сообщеньки обязаны заканчиваться на Request/Response.


TFinishAcquireDiskRequest - можно, например, назвать `TDevicesAcquireFinished` и снизу объявить его именно как `TRequestEvent`

2024-12-27 18:53 UTC, komarevtsev-d commented on cloud/blockstore/libs/storage/volume/volume_actor_acquire.cpp
> +    auto responseRecord = NProto::TAcquireDiskResponse();
Этот актор отправляет `AcquireDevices`, а в Volume отдает результат в виде `AcquireDisk`. 
Мне кажется это неправильно, и в будущем, когда полностью перейдем на схему без DR, из кода полностью должен пропасть AcquireDisk код.

2024-12-28 05:33 UTC, vladstepanyuk commented on cloud/blockstore/libs/storage/volume/volume_actor_acquire.cpp
> +        }
Да, мы в конструкторе сортируем по NodeId

2025-01-09 04:50 UTC, vladstepanyuk commented on cloud/blockstore/libs/storage/volume/volume_state_ut.cpp
> +#include "cloud/blockstore/libs/storage/disk_registry/testlib/test_state.h"
убрать лишнее форматирование

2025-01-09 05:01 UTC, vladstepanyuk commented on cloud/blockstore/libs/storage/volume/volume_events_private.h
> +    struct TRemoveDiskSessionResponse
убрать

2025-01-09 05:04 UTC, vladstepanyuk commented on cloud/blockstore/libs/storage/volume/volume_events_private.h
> +    // RemoveDiskSession
поменять коментарий

2025-01-09 05:05 UTC, vladstepanyuk commented on cloud/blockstore/libs/storage/volume/volume_events_private.h
> +    // FinishAcquireDisk
Поменять коментарий

2025-01-09 05:10 UTC, vladstepanyuk commented on cloud/blockstore/libs/storage/volume/volume_events_private.h
> +
убрать строчку

2025-01-09 05:27 UTC, vladstepanyuk commented on cloud/blockstore/libs/storage/volume/volume_actor.h
> +    void HandleDeviceAcquireFinished(
Поправить сигнатуру и имя

2025-01-09 05:29 UTC, vladstepanyuk commented on cloud/blockstore/libs/storage/volume/volume_actor.h
> +    void HandleReleaseDevicesResponseImpl(
Поправить имя

2025-01-09 06:17 UTC, vladstepanyuk commented on cloud/blockstore/libs/storage/volume/volume_actor_release.cpp
> +    if (MuteIOErrors) {
перенести в OnReleaseResponce

2025-01-09 06:21 UTC, vladstepanyuk commented on cloud/blockstore/libs/storage/volume/volume_actor.h
> +            TRequestInfoPtr requestInfo,
remove fmt

2025-01-09 06:23 UTC, komarevtsev-d commented on cloud/blockstore/libs/storage/volume/volume_actor.h
> -
Тут лишний дифф тоже

2025-01-09 06:24 UTC, komarevtsev-d commented on cloud/blockstore/libs/storage/volume/volume_actor_acquire.cpp
> +    auto sentRequests =
они только созданы пока, но еще не отправлены. Поэтому лучше просто `auto requests = <...>`

2025-01-09 07:22 UTC, komarevtsev-d commented on cloud/blockstore/libs/storage/volume/volume_actor_release.cpp
> +    }
if (HasError(error)) {
        LOG_LOG(
            ctx,
            MuteIOErrors ? NLog::PRI_WARN : NLog::PRI_ERROR,
            TBlockStoreComponents::VOLUME,
            <...>);
}

2025-01-13 09:33 UTC, komarevtsev-d commented on cloud/blockstore/config/storage.proto
> +    optional bool UseDirectAcquireReleaseDevicesSending = 397;
Если включен `UseDirectAcquireReleaseDevicesSending`, то стоит выключить отправку закешированных сессий при регистрации агента в `SendCachedAcquireRequestsToAgent()`.

2025-01-13 09:49 UTC, komarevtsev-d commented on cloud/blockstore/libs/storage/disk_registry/disk_registry_actor_register.cpp
> +    }
Добавь проверку внутрь метода? На всякий случай. Эту можно убрать

2025-01-13 09:52 UTC, komarevtsev-d submitted a review, later dismissed

2025-01-13 11:43 UTC, sharpeye commented on cloud/blockstore/libs/storage/disk_registry/disk_registry_actor_release.cpp
> +#include "cloud/blockstore/libs/storage/core/proto_helpers.h"
<>

2025-01-13 11:43 UTC, sharpeye commented on cloud/blockstore/libs/storage/testlib/disk_agent_mock.h
> +        switch (typeRewrite) {
Это для чего?

2025-01-13 11:43 UTC, sharpeye commented on cloud/blockstore/libs/storage/volume/volume_actor_acquire.cpp
> +#include "cloud/blockstore/libs/storage/core/proto_helpers.h"
<>

2025-01-13 11:43 UTC, sharpeye commented on cloud/blockstore/libs/storage/volume/volume_actor_acquire.cpp
> +
Не хватает отбивки ////...//

2025-01-13 11:43 UTC, sharpeye commented on cloud/blockstore/libs/storage/volume/volume_actor_acquire.cpp
> +    bool muteIOErrors)
/t

2025-01-13 11:43 UTC, sharpeye commented on cloud/blockstore/libs/storage/volume/volume_actor_acquire.cpp
> +class TAcquireDevicesActor final
Переиспользовать из DR [актор](https://github.com/ydb-platform/nbs/blob/main/cloud/blockstore/libs/storage/disk_registry/disk_registry_actor_acquire.cpp#L20) не получится?

2025-01-13 11:48 UTC, sharpeye commented on cloud/blockstore/libs/storage/volume/volume_actor_removeclient.cpp
> +    }
Это можно проверять до создания запроса

2025-01-15 10:32 UTC, closed without merging