add date&time to chaos monkey logs
ydb-platform/nbs pull request #330
Opened 2024-02-02 17:14 UTC by dvrazumov

2024-02-04 11:30 UTC, budevg requested changes

2024-02-04 11:30 UTC, budevg commented on cloud/blockstore/tools/testing/chaos-monkey/main.go
> +			log.Printf("cleanup: %v\n", o)
no need for `\n` when you use `log.Printxxx`
change here and in all other places

2024-02-04 11:30 UTC, budevg commented on cloud/blockstore/tools/testing/chaos-monkey/main.go
> +	log.Println("DiskInfo:")
consider printing in one line and not split it into two lines ... different go routines can interleave other data into the logs between the two lines

same remark to other places where you
```go
log.Println("title:")
...
log.Println(data)
```

2024-02-06 16:31 UTC, budevg submitted a review, later dismissed

2024-02-07 11:11 UTC, debnatkh commented on cloud/blockstore/tools/testing/chaos-monkey/main.go
> +	log.Println("Targets to heal: " + string(output))
Наверное, тут и в других местах можно использовать `log.Printf`

2024-02-07 11:46 UTC, drbasic submitted a review, later dismissed

2024-02-07 11:59 UTC, qkrorlqr approved these changes

2024-02-13 15:25 UTC, drbasic approved these changes

2024-02-13 15:53 UTC, debnatkh approved these changes

2024-02-13 16:49 UTC, merged