NBSNEBIUS-104: fix race, do refactoring of EndpointManager
ydb-platform/nbs pull request #335
Opened 2024-02-03 22:02 UTC by sanek325

2024-02-04 10:55 UTC, budevg approved these changes

2024-02-06 17:31 UTC, qkrorlqr commented
Не надо так делать. fix race - отдельный PR, refactoring - отдельный PR

+848 −699 - где среди этих строк фиксится race и не вносится ли пачка новых race - совершенно непонятно

2024-02-06 17:32 UTC, qkrorlqr requested changes
Не надо так делать. fix race - отдельный PR, refactoring - отдельный PR

+848 −699 - где среди этих строк фиксится race и не вносится ли пачка новых race - совершенно непонятно

2024-02-06 17:34 UTC, qkrorlqr commented
> No description provided.

и как людям из правой части понять, а о чем вообще этот PR? issue на github с описанием проблемы нет, description нет

2024-02-06 17:35 UTC, qkrorlqr requested changes
> No description provided.

и как людям из правой части понять, а о чем вообще этот PR? issue на github с описанием проблемы нет, description нет

2024-02-06 20:39 UTC, qkrorlqr commented on cloud/blockstore/libs/endpoints/endpoint_manager.cpp
> +    std::variant<
Эта штука допускает 9 вариантов типов в полях, хотя на самом деле валидных только 3. Так что на самом деле эта структура должна сама шаблонизироваться TMethod-ом, а TEndpointManager::ProcessingSockets должен быть коллекцией variant-ов TProcessingEndpointState<>, шаблонизированных тремя вариантами методов - Start/Stop/Refresh

2024-02-07 10:56 UTC, sanek325 commented on cloud/blockstore/libs/endpoints/endpoint_manager.cpp
> +    std::variant<
Поправил

2024-02-09 12:28 UTC, sharpeye commented on cloud/blockstore/libs/endpoints/endpoint_manager.cpp
> +    if (auto it = ProcessingSockets.find(socketPath)) {
Не надо проверить на ProcessingSockets.end() ?

2024-02-09 12:28 UTC, sharpeye commented on cloud/blockstore/libs/endpoints/endpoint_manager.cpp
> +        if (!std::holds_alternative<TRequestState<TStopEndpointMethod>>(st)) {
Можно через get_if:
```cpp
if (auto* state = std::get_if<TRequestState<TStopEndpointMethod>>(&st)) {
    Executor->WaitFor(state->Result);
    return state->Result.GetValue();
}
```

2024-02-09 17:47 UTC, sanek325 commented on cloud/blockstore/libs/endpoints/endpoint_manager.cpp
> +        if (!std::holds_alternative<TRequestState<TStopEndpointMethod>>(st)) {
Поправил, спасибо. 
JFYI: прям так, как ты написал делать нельзя, потому что после WaitFor указатель state может стать невалидным.
Сделал return Executor->WaitFor(state->Result);

2024-02-09 17:47 UTC, sanek325 commented on cloud/blockstore/libs/endpoints/endpoint_manager.cpp
> +    if (auto it = ProcessingSockets.find(socketPath)) {
Надо, поправил.

2024-02-09 19:24 UTC, sharpeye approved these changes

2024-02-12 09:54 UTC, NewBediver submitted a review, later dismissed

2024-02-12 16:53 UTC, qkrorlqr commented on cloud/blockstore/libs/endpoints/endpoint_manager.cpp
> +        if (!IsSameStartEndpointRequests(*request, state->Request)) {
AreSameRequests или IsSameRequest, но не IsSameRequests

2024-02-12 16:53 UTC, qkrorlqr commented on cloud/blockstore/libs/endpoints/endpoint_manager.cpp
> +                << "endpoint " << socketPath.Quote() << " is occupied now");
вроде обычно говорят busy в таком контексте, а не occupied

2024-02-12 16:53 UTC, qkrorlqr commented on cloud/blockstore/libs/endpoints/endpoint_manager.cpp
> +        if (!state) {
мне кажется, нужен коммент в коде, почему если state == nullptr, это значит, что endpoint - busy
судя по коду, выглядит так, как будто в этой ветке у нас в ProcessingSockets по ключу socketPath лежит StopEndpointRequest

2024-02-12 16:53 UTC, qkrorlqr commented on cloud/blockstore/libs/endpoints/endpoint_manager.cpp
> +            return TErrorResponse(E_REJECTED, TStringBuilder()
а почему E_REJECTED? ретрай запроса наступит на ту же самую ошибку либо приведет к тому, что мы дадим отлуп про то, что endpoint на этом socketPath уже поднят, так что просто ретрая для успеха запроса недостаточно

2024-02-12 16:53 UTC, qkrorlqr commented on cloud/blockstore/libs/endpoints/service_endpoint.h
> +#include <cloud/storage/core/libs/coroutine/public.h>
инклюды не по порядку идут

2024-02-14 14:52 UTC, sanek325 commented on cloud/blockstore/libs/endpoints/endpoint_manager.cpp
> +        if (!state) {
так и есть, написал в тексте ошибки

2024-02-14 14:52 UTC, sanek325 commented on cloud/blockstore/libs/endpoints/endpoint_manager.cpp
> +                << "endpoint " << socketPath.Quote() << " is occupied now");
поправил

2024-02-14 19:18 UTC, qkrorlqr approved these changes

2024-02-14 19:56 UTC, EvgeniyKozev approved these changes

2024-02-14 21:28 UTC, merged