NBS-4829: [disk-manager]: add log level to dm logs
ydb-platform/nbs pull request #346
Opened 2024-02-06 11:31 UTC by gy2411

2024-02-06 13:35 UTC, BarkovBG commented on cloud/tasks/logging/journald_logger.go
> +		msg = l.name + " " + msg
а это зачем поменялось?

2024-02-06 13:35 UTC, BarkovBG commented on cloud/tasks/logging/journald_logger.go
> +	msg = strings.ToUpper(level.String()) + " => " + msg
а почему тут не сделать пробел а на 95 строчке не оставить =>

2024-02-06 13:39 UTC, gy2411 commented on cloud/tasks/logging/journald_logger.go
> +		msg = l.name + " " + msg
Эта стрелочка теперь всегда ставится после уровня логирования. Подумал, что ещё одна стрелочка будет уже перебором. Хотя не принципиально, можно и вернуть.

2024-02-06 13:42 UTC, gy2411 commented on cloud/tasks/logging/journald_logger.go
> +	msg = strings.ToUpper(level.String()) + " => " + msg
Идея в том, чтобы стрелочка отделяла основное тело сообщения от всего остального. Но думаю, это не принципиально.

2024-02-06 13:46 UTC, gy2411 commented on cloud/tasks/logging/journald_logger.go
> +	msg = strings.ToUpper(level.String()) + " => " + msg
Сделал, как ты предлагаешь

2024-02-06 13:47 UTC, BarkovBG approved these changes

2024-02-06 13:54 UTC, jkuradobery requested changes

2024-02-06 13:54 UTC, jkuradobery commented on cloud/tasks/logging/journald_logger.go
> +	msg = strings.ToUpper(level.String()) + " " + msg
Why not just use a fmt.Sprintf? Is it due to performance concerns?

2024-02-06 14:00 UTC, jkuradobery approved these changes

2024-02-06 14:00 UTC, jkuradobery commented on cloud/tasks/logging/journald_logger.go
> +	msg = strings.ToUpper(level.String()) + " " + msg
Received explanation that it was made for consistency reasons.

2024-02-07 09:35 UTC, merged

2024-02-07 09:36 UTC, gy2411 commented
Tests fail is due to known flap. (Work on this flap is in progress)