NBS-4876 Persistent save shadow disk state
ydb-platform/nbs pull request #366
Opened 2024-02-08 11:09 UTC by drbasic

2024-02-08 16:21 UTC, qkrorlqr requested changes

2024-02-12 09:34 UTC, qkrorlqr approved these changes

2024-02-12 09:35 UTC, qkrorlqr commented on cloud/blockstore/libs/storage/volume/volume_actor_monitoring.cpp
> +            out << " blocks: " << checkpointInfo.ProcessedBlockCount << "/"
Ok, потом

2024-02-12 09:47 UTC, komarevtsev-d approved these changes

2024-02-12 13:00 UTC, merged