NBS-1704: track uds clients in server
ydb-platform/nbs pull request #367
Opened 2024-02-08 11:31 UTC by yegorskii

2024-02-08 15:13 UTC, qkrorlqr commented
Нужно нормально описание PR
Что и зачем делается
А еще лучше нормальное описание + прилинкованная issue (только не в поле issue, а просто issue #xxx в description)

2024-02-09 12:56 UTC, qkrorlqr commented
issue #380

2024-02-09 17:29 UTC, qkrorlqr requested changes

2024-02-09 17:29 UTC, qkrorlqr commented on cloud/filestore/libs/server/server.cpp
> +    Y_ABORT_UNLESS(authContext);
в каком случае auth-контекста может не быть?

2024-02-09 17:29 UTC, qkrorlqr commented on cloud/filestore/libs/server/server.cpp
> +    static const TString PeerFdPrefix = "fd:";
а кто этот fd: в пира записывает?

2024-02-09 17:29 UTC, qkrorlqr commented on cloud/filestore/libs/server/server.cpp
> +    if (source == NProto::SOURCE_SECURE_CONTROL_CHANNEL) {
что-то не понял, в чем суть

в этом месте же у нас unix socket? который нужен, чтоб не гонять по нему токены как раз - авторизация на уровне прав в файловой системе происходит

а откуда тогда токен берется строчкой ниже?

2024-02-09 17:29 UTC, qkrorlqr commented on cloud/filestore/libs/server/server.cpp
> +    using TService = IFileStoreService;
какие-то странные запутывающие typedef-ы, давай их уберем

2024-02-09 17:29 UTC, qkrorlqr commented on cloud/filestore/libs/server/server.cpp
> +    TServicePtr GetSessionService(ui32 fd, NProto::ERequestSource& source)
давай output-параметр (source) передадим raw ptr-ом, чтоб в месте вызова было видно, что это output-параметр

2024-02-09 17:29 UTC, qkrorlqr commented on cloud/filestore/libs/server/server.cpp
> +            dupSocket = SafeCreateDuplicate(socket);
вот эту всю затейливую логику с dup fd надо расписать в комменте (описать, зачем это надо)

2024-02-09 17:29 UTC, qkrorlqr commented on cloud/filestore/libs/server/server.cpp
> +        auto sessionService = SessionStorage->GetSessionService(fd, src);
что-то я не понимаю, а где этот sessionService используется-то? кто запросы в него передает?

2024-02-09 17:31 UTC, qkrorlqr commented
У меня идея. Вот тут добавляется новая фича. А давайте вместе с добавлением новой фичи сразу писать доку про то, что это и как работает, в https://github.com/ydb-platform/nbs/tree/main/doc - это сразу устранит часть вопросов, заданных в комментах в PR

2024-02-21 18:40 UTC, yegorskii commented on cloud/filestore/libs/server/server_ut.cpp
> +        TFsPath unixSocket("./test_socket");
Сделал как в NBS

2024-02-21 19:21 UTC, yegorskii commented on cloud/filestore/libs/server/server.cpp
> +    Y_ABORT_UNLESS(authContext);
Ктобы знал, нам возвращают shared_ptr на некую структуру. Может ли shared_ptr быть пустым - формально да. В документации я ответа не нашел.

2024-02-21 19:23 UTC, yegorskii commented on cloud/filestore/libs/server/server.cpp
> +    static const TString PeerFdPrefix = "fd:";
GRPC. Конкретно функция grpc_server_add_channel_from_fd

2024-02-22 10:57 UTC, yegorskii commented on cloud/filestore/libs/server/server.cpp
> +        auto sessionService = SessionStorage->GetSessionService(fd, src);
TRequestHandler имеет ссылку на на это service. Здесь же мы проверяем что сокет еще не закрыт.

2024-02-22 17:45 UTC, qkrorlqr commented on cloud/filestore/libs/server/server.cpp
> +class TSessionStorage final
ладно, пусть будет тут

2024-02-22 18:01 UTC, qkrorlqr commented on cloud/filestore/libs/server/server.cpp
> +        auto sessionService = SessionStorage->GetSessionService(fd, src);
у тебя sessionService не используется, а GetSessionService зовется только в этом месте
тебе не нужен этот GetSessionService, тебе нужен std::optional<ERequestSource> FindRequestSource(int fd)

2024-02-22 18:46 UTC, yegorskii commented on cloud/filestore/libs/server/server.cpp
> +        auto sessionService = SessionStorage->GetSessionService(fd, src);
Договорились поменять имя функции на более адекватное использованию

2024-02-26 14:06 UTC, yegorskii commented on cloud/filestore/libs/server/server.cpp
> +        auto sessionService = SessionStorage->GetSessionService(fd, src);
Поменял

2024-02-26 14:56 UTC, qkrorlqr commented on cloud/filestore/libs/server/server.cpp
> +    // need for avoid race, see NBS-3325
плохой коммент - давай тут опишем предмет гонки

2024-02-26 15:00 UTC, qkrorlqr commented on cloud/filestore/libs/server/server.cpp
> +        auto src = NProto::SOURCE_FD_DATA_CHANNEL;
это значение использоваться не будет
если CheckClientFd вернул true, то он посетит src сам
если false, то мы просто исключение кидаем и все, не используем src
так что код должен быть примерно таким:
`
auto src = SessionStorage->FindSourceByFd(fd); // returns optional<ERequestSource>
if (!src) {
    ythrow ...;
}
source = *src;
`

2024-02-26 15:01 UTC, qkrorlqr commented on cloud/filestore/libs/server/server.cpp
> +        if constexpr (std::is_same<TAppContext, TEndpointManagerContext>::value)
точно нужна эта проверка? может, просто на уровне конфигов не будем в nfs-server конфигурить uds?

2024-02-26 15:04 UTC, qkrorlqr commented on cloud/filestore/libs/server/server.cpp
> +        IEndpointManagerPtr Service;
не вижу, где это поле используется

2024-02-26 15:39 UTC, yegorskii commented on cloud/filestore/libs/server/server.cpp
> +        if constexpr (std::is_same<TAppContext, TEndpointManagerContext>::value)
Ну идея была в том чтобы не тащить SessionStorage в TFileStoreContext. Ну да ладно.....

2024-02-26 19:18 UTC, yegorskii commented on cloud/filestore/libs/server/server.cpp
> +bool TryParseSourceFd(const TStringBuf& peer, ui32* fd)
унес в storage/core/libs/grpc

2024-02-27 19:02 UTC, qkrorlqr commented on cloud/storage/core/libs/grpc/utils.cpp
> +bool TryParseSourceFd(const TStringBuf& peer, ui32* fd)
и мини-ut на это надо теперь

2024-02-28 10:37 UTC, qkrorlqr commented on cloud/storage/core/libs/grpc/utils_ut.cpp
> +    Y_UNIT_TEST(ShouldFailIfPeerStringIsIncorrent)
Incorrect

2024-02-29 19:05 UTC, qkrorlqr submitted a review, later dismissed

2024-03-04 06:19 UTC, EvgeniyKozev approved these changes

2024-03-04 13:06 UTC, EvgeniyKozev approved these changes

2024-03-04 13:22 UTC, qkrorlqr approved these changes

2024-03-04 13:24 UTC, merged