Introduce PoisonPill helper
ydb-platform/nbs pull request #384
Opened 2024-02-09 08:40 UTC by drbasic

2024-02-09 12:52 UTC, qkrorlqr requested changes

2024-02-09 12:52 UTC, qkrorlqr commented on cloud/storage/core/libs/actors/poison_pill_helper.h
> +
лишняя пустая строка

2024-02-09 12:52 UTC, qkrorlqr commented on cloud/storage/core/libs/actors/poison_pill_helper.cpp
> +
не хватает наших отбивок /////

2024-02-09 12:52 UTC, qkrorlqr commented on cloud/storage/core/libs/actors/poison_pill_helper.cpp
> +
обычно между namespace XXX { и namespace [YYY] { не добавляем пустую строку

2024-02-09 12:52 UTC, qkrorlqr commented on cloud/storage/core/libs/actors/poison_pill_helper.cpp
> +class TIActorHelper: public IActor
IActorHelper

2024-02-09 12:52 UTC, qkrorlqr commented on cloud/storage/core/libs/actors/poison_pill_helper.cpp
> +class TIActorHelper: public IActor
но вообще что-то я не понял, зачем этот хелпер нужен

кажется, намного проще просто в единственном месте использования этой штуки вызывать Owner->Die(ctx)

2024-02-09 12:52 UTC, qkrorlqr commented on cloud/storage/core/libs/actors/poison_pill_helper.h
> +        ui64 Cookie;
давай проинициализируем нулем или сделаем конструктор, который принимает оба параметра (sender, cookie)

2024-02-09 12:52 UTC, qkrorlqr commented on cloud/storage/core/libs/actors/poison_pill_helper.h
> +    virtual void HandlePoisonPill(
а зачем virtual?

2024-02-09 13:32 UTC, drbasic commented on cloud/storage/core/libs/actors/poison_pill_helper.cpp
> +class TIActorHelper: public IActor
Die protected

2024-02-09 14:52 UTC, qkrorlqr commented on cloud/storage/core/libs/actors/poison_pill_helper.cpp
> +class TIActorHelper: public IActor
Что-то выглядит как какой-то адский хак =/ Мне не нравится

2024-02-09 14:52 UTC, qkrorlqr commented on cloud/storage/core/libs/actors/poison_pill_helper.h
> +    virtual void HandlePoisonPill(
Давай сейчас уберем. Понадобится - добавим.

2024-02-10 04:37 UTC, komarevtsev-d approved these changes

2024-02-12 11:45 UTC, qkrorlqr approved these changes

2024-02-12 11:45 UTC, qkrorlqr commented on cloud/storage/core/libs/actors/poison_pill_helper.cpp
> +class TIActorHelper: public IActor
Решили, что сильно лучше не придумать. Заливаем так.

2024-02-12 11:45 UTC, merged