NBSNEBIUS-41: don't release NRD session on retriable errors
ydb-platform/nbs pull request #430
Opened 2024-02-13 19:23 UTC by sharpeye

Issue #170

2024-02-14 17:57 UTC, EvgeniyKozev commented on cloud/blockstore/libs/storage/disk_registry/disk_registry_actor_acquire.cpp
> +    if (HasError(error) && GetErrorKind(error) != EErrorKind::ErrorRetriable) {
Следующий if отличается только ретурном и уровнем логирования?

Вообще тут поменялась логика.
Если ошибка ретраибельная то мы считаем что это нормальный Acquire, но не запоминаем его ID
В этом и суть изменений?

2024-02-14 17:57 UTC, EvgeniyKozev commented on cloud/blockstore/libs/storage/disk_registry/disk_registry_actor_acquire.cpp
>  void TAcquireDiskActor::OnReleaseResponse(
Так, а как тут будет логика очищения списка нод работать?
Они явно будут накапливаться.

2024-02-14 17:57 UTC, EvgeniyKozev commented on cloud/blockstore/libs/storage/disk_registry/disk_registry_actor_acquire.cpp
> +            if (!NodeIdsWithSucceededResponses.contains(device.GetNodeId())) {
Кажется инвертированное будет нагляднее и без continue

2024-02-15 18:46 UTC, sharpeye commented on cloud/blockstore/libs/storage/disk_registry/disk_registry_actor_acquire.cpp
>  void TAcquireDiskActor::OnReleaseResponse(
Ноды не надо очищать, этот актор одноразовый  - запускается на каждый запрос acquire disk.

2024-02-15 18:50 UTC, sharpeye commented on cloud/blockstore/libs/storage/disk_registry/disk_registry_actor_acquire.cpp
> +    if (HasError(error) && GetErrorKind(error) != EErrorKind::ErrorRetriable) {
Смысл в том, что мы теперь не релизим сессии при ретрабильных ошибках. А в NodeIdsWithSucceededResponses кладем только ноды, для которых успешно выполнились запросы (чтобы в ответе оставить только девайсы от таких нод).

2024-02-19 14:48 UTC, tpashkin commented on cloud/blockstore/libs/storage/disk_registry/disk_registry_actor_acquire.cpp
> +        if (GetErrorKind(error) != EErrorKind::ErrorRetriable) {
Я может чего-то не понимаю, но ты выше делаешь move на error, разве он не будет пустой?

2024-02-19 15:00 UTC, qkrorlqr commented on cloud/blockstore/libs/storage/disk_registry/disk_registry_actor_acquire.cpp
> +    OnAcquireResponse(ctx, static_cast<ui32>(ev->Cookie), ev->Get()->GetError());
давай какой-нибудь SafeIntegerCast лучше

2024-02-19 15:01 UTC, qkrorlqr commented on cloud/blockstore/libs/storage/disk_registry/disk_registry_actor_acquire.cpp
> +        static_cast<ui32>(ev->Cookie),
и тут

2024-02-19 16:48 UTC, EvgeniyKozev submitted a review, later dismissed

2024-02-19 16:48 UTC, EvgeniyKozev commented on cloud/blockstore/libs/storage/disk_registry/disk_registry_actor_acquire.cpp
> +        FinishAcquireDisk(ctx, std::move(error));
Это пока смущает. Кажется это приведет к тому, что ошибка пойдет в AddClientResponse, что с провоцирует RequestVolumeStop.
Давайте обсудим.

2024-02-20 10:17 UTC, drbasic requested changes

2024-02-20 10:17 UTC, drbasic commented on cloud/blockstore/libs/storage/disk_registry/disk_registry_actor_acquire.cpp
> +        FinishAcquireDisk(ctx, std::move(error));
при получении ретрабельной ошибки от первого агента мы прекращаем ждать другие ответы. А ведь там кто-то может ответить и не ретрабельной ошибкой.

2024-02-20 11:54 UTC, tpashkin submitted a review, later dismissed

2024-02-20 12:16 UTC, drbasic approved these changes

2024-02-20 12:18 UTC, tpashkin approved these changes

2024-02-20 12:30 UTC, tpashkin approved these changes

2024-02-20 12:32 UTC, sharpeye commented on cloud/blockstore/libs/storage/disk_registry/disk_registry_actor_acquire.cpp
> +        FinishAcquireDisk(ctx, std::move(error));
Обсудили, что не критично

2024-02-20 13:17 UTC, merged