issue #122: GetChangedBlocks should respect 'unconfirmed blobs' feature
ydb-platform/nbs pull request #484
Opened 2024-02-19 15:58 UTC by SvartMetal

2024-02-19 16:04 UTC, qkrorlqr approved these changes

2024-02-20 09:57 UTC, drbasic requested changes

2024-02-20 09:57 UTC, drbasic commented on cloud/blockstore/libs/storage/partition/model/unconfirmed_blob.cpp
>      for (const auto& entry: blobs) {
for (const auto& [commitId, blob]: blobs) {

2024-02-20 09:57 UTC, drbasic commented on cloud/blockstore/libs/storage/partition/part_actor_changedblocks.cpp
> +    if (State->OverlapsUnconfirmedBlobs(
clang-format

2024-02-20 09:57 UTC, drbasic commented on cloud/blockstore/libs/storage/partition/model/unconfirmed_blob.h
>  using TUnconfirmedBlobs = THashMap<ui64, TVector<TUnconfirmedBlob>>;
Заботливао разложенные грабли:
делаем два как бы типа разных типа TUnconfirmedBlobs и TConfirmedBlobs, но они совпадают.
потом пишем функцию 
bool Overlaps(
    const TUnconfirmedBlobs& blobs,
    ui64 commitId,
    const TBlockRange32& blockRange);
в которую кормим первым параметром и то и другое.
давайте не будем так делать, если это разные типы, то они разные. Если одинаковые, то не даем им разные алиасы, а назваем например TCommitIdToBlob

2024-02-20 09:59 UTC, drbasic commented on cloud/blockstore/libs/storage/partition/part_state.h
>      bool OverlapsUnconfirmedBlobs(
точно нужна перегрузка с 3мя параметрами?

2024-02-20 10:23 UTC, SvartMetal commented on cloud/blockstore/libs/storage/partition/model/unconfirmed_blob.h
>  using TUnconfirmedBlobs = THashMap<ui64, TVector<TUnconfirmedBlob>>;
Сделаю в следующем предложение

2024-02-20 10:26 UTC, SvartMetal commented on cloud/blockstore/libs/storage/partition/part_state.h
>      bool OverlapsUnconfirmedBlobs(
Используется в ReadBlocks, DescribeBlocks, чтобы код лучше читался

2024-02-20 10:32 UTC, drbasic approved these changes

2024-02-20 11:52 UTC, BarkovBG approved these changes

2024-02-20 11:52 UTC, merged