track small number of recently completed requests; resolves #481
ydb-platform/nbs pull request #489
Opened 2024-02-19 19:43 UTC by tpashkin

2024-02-20 09:22 UTC, tpashkin commented
Failed tests should not be affected by this changes, likely a false positive

2024-02-20 17:14 UTC, budevg submitted a review, later dismissed

2024-02-21 04:44 UTC, drbasic requested changes

2024-02-21 04:44 UTC, drbasic commented on cloud/blockstore/libs/rdma/impl/client.cpp
> +    bool Completed(ui32 reqId)
const

2024-02-21 04:44 UTC, drbasic commented on cloud/blockstore/libs/rdma/impl/client.cpp
> +    send->context = reinterpret_cast<void*>(req->ReqId);
тут не очень хоршее место, размер ui32 и void* разный.
не понятно чем будут заполнены старшие 32 бита, произойдет ли знаковое расширение или просто забьют все нулями.

2024-02-21 04:44 UTC, drbasic commented on cloud/blockstore/libs/rdma/impl/client.cpp
> +    auto reqId = reinterpret_cast<uintptr_t>(send->context);
а тут получили 64 битный тип и с ним идем туда, куда клали 32 битный.
Когда выключим подавление ворнингов, тут взорвется.

2024-02-21 04:44 UTC, drbasic commented on cloud/blockstore/libs/rdma/impl/client.cpp
1. И снова я прошу, очень прошу. напиши коментарий внутри каждого метода, из какого потока он зовется. Просто одна строчка,
 // called from CQ thread
и это сэкономит кучу времени разбираться, есть конкурируюший доступ к полю.
Вот сейчас я не понимаю, ActiveRequests трогают с разных потоков или нет.
2. Метод `void HandleCompletionEvent(ibv_wc* wc) override;` спрятали в приватную секцию, но пофакту это публичный метод. Его зовут через интерфейс. Перенеси в публичную секцию и напишите явно:
```//Implements NVerbs::ICompletionHandler
// called from X thread```

2024-02-21 07:31 UTC, drbasic commented on cloud/blockstore/libs/rdma/impl/client.cpp
> +    send->context = reinterpret_cast<void*>(req->ReqId);
Тут я не прав, тип же беззнаковый, будт дополнен нулями значит.
Но может правильнее сначала явно расширить его до ui64, а потом сделать bit_cast ?

2024-02-21 11:43 UTC, tpashkin commented on cloud/blockstore/libs/rdma/impl/client.cpp
1. Я не очень понимаю какое это имеет отношение к PR, но у всех методов в заголовках и так отмечено из какого треда они вызываются
2. Перенесу, но не в этом PR

2024-02-21 13:59 UTC, tpashkin commented on cloud/blockstore/libs/rdma/impl/client.cpp
Завёл https://github.com/ydb-platform/nbs/pull/518. Предлагаю дальнейшее обсуждение по этой ветке вести там

2024-02-21 14:02 UTC, drbasic approved these changes

2024-02-22 09:26 UTC, budevg approved these changes

2024-02-22 19:53 UTC, merged