issue #122: get rid of OverlapsUnconfirmedBlobs overloading; get rid of unneeded TConfirmedBlobs type
ydb-platform/nbs pull request #494
Opened 2024-02-20 12:21 UTC by SvartMetal

2024-02-20 12:25 UTC, drbasic commented on cloud/blockstore/libs/storage/partition/part_state.h
> +    // contains entries from UnconfirmedBlobs that have been confirmed but have
`TUnconfirmedBlobs ConfirmedBlobs;`
тут точно нет противоречия?

2024-02-20 12:27 UTC, SvartMetal commented on cloud/blockstore/libs/storage/partition/part_state.h
> +    // contains entries from UnconfirmedBlobs that have been confirmed but have
на первый взгляд выглядит противоречиво, поэтому написал комментарий

2024-02-20 14:35 UTC, drbasic requested changes

2024-02-20 14:35 UTC, drbasic commented on cloud/blockstore/libs/storage/partition/model/unconfirmed_blob.h
> +using TUnconfirmedBlobs = TUniqueIdWithRangeFromCommitId;
 Спорное решение, компилятор не будет споротивляться если ты перепутаешь переменные этих алиасов. Но дает ложное ощущение безопасности.

2024-02-20 14:35 UTC, drbasic commented on cloud/blockstore/libs/storage/partition/model/unconfirmed_blob.h
> +using TUnconfirmedBlobs = TUniqueIdWithRangeFromCommitId;
Лучшее решение - сделать две структуры с идентичным содержанием но разными именами, тогда компилятор будет бить по рукам при попыьке перепутать.

2024-02-21 04:09 UTC, drbasic approved these changes

2024-02-21 14:10 UTC, qkrorlqr approved these changes

2024-02-21 14:52 UTC, BarkovBG approved these changes

2024-02-21 14:53 UTC, merged