issue-506: cancel requests in transactions upon tablet restart
ydb-platform/nbs pull request #507
Opened 2024-02-20 19:51 UTC by yegorskii

2024-02-22 12:17 UTC, NewBediver requested changes

2024-02-22 12:22 UTC, NewBediver submitted a review, later dismissed

2024-02-27 19:24 UTC, debnatkh commented
@yegorskii 
А то, что `AddTransaction` не зовётся в `tablet_actor_addblob.cpp` – это так и задумано?

2024-02-27 19:32 UTC, yegorskii commented
> @yegorskii А то, что `AddTransaction` не зовётся в `tablet_actor_addblob.cpp` – это так и задумано?

да, эта штука зовется только из внутренних акторов, которые если что будут прибиты по poison pill и сами ответят на пользовательский запрос.

2024-02-29 19:06 UTC, qkrorlqr commented on cloud/filestore/libs/storage/tablet/tablet_actor.cpp
> +    Y_ABORT_UNLESS(requestInfo.Empty());
TABLET_VERIFY!

2024-02-29 19:06 UTC, qkrorlqr commented on cloud/filestore/libs/storage/tablet/tablet_actor.cpp
> +    Y_ABORT_UNLESS(!requestInfo.Empty());
TABLET_VERIFY

2024-02-29 19:07 UTC, qkrorlqr commented on cloud/filestore/libs/storage/tablet/tablet_actor.cpp
> +        Y_ABORT_UNLESS(requestInfo->RefCount() >= 1);
TABLET_VERIFY

2024-02-29 19:11 UTC, qkrorlqr commented on cloud/filestore/libs/storage/tablet/tablet_actor_writebatch.cpp
> +    for (const auto& batch: writeBatch) {
странное именование - что за батчи в батчах? почему batch?

2024-02-29 19:11 UTC, qkrorlqr commented on cloud/filestore/libs/storage/tablet/tablet_ut_data.cpp
> +#include <contrib/ydb/core/base/blobstorage.h>
алфавит

2024-02-29 19:13 UTC, qkrorlqr commented on cloud/filestore/libs/storage/core/request_info.h
>          Y_ABORT_UNLESS(CancelRoutine);
кто гарантирует, что CancelRoutine всегда есть?

2024-03-01 13:44 UTC, yegorskii commented on cloud/filestore/libs/storage/core/request_info.h
>          Y_ABORT_UNLESS(CancelRoutine);
Если RequestInfo создается через 
```
template <typename TMethod>
TRequestInfoPtr CreateRequestInfo(....)
```
то CancelRoutine будет инициализирована

2024-03-01 13:56 UTC, qkrorlqr commented on cloud/filestore/libs/storage/tablet/tablet_actor.cpp
> +    Y_ABORT_UNLESS(requestInfo.Empty());
Я не знаю, почему не перевели - видимо, руки не дошли
Это не повод в новом коде не использовать TABLET_VERIFY

2024-03-01 16:58 UTC, qkrorlqr commented on cloud/filestore/libs/storage/core/request_info.h
>          Y_ABORT_UNLESS(CancelRoutine);
мне кажется, нормально и безопасно не полагаться на то, что CancelRoutine ответит правильной ошибкой, а явным образом отдать E_REJECTED, после чего, если CancelRoutine выставлен, позвать его (а если не выставлен, ну и хрен с ним)

2024-03-01 18:11 UTC, yegorskii commented on cloud/filestore/libs/storage/core/request_info.h
> +            MakeError(E_REJECTED, "request cancelled"));
а в акторах на poison pill посылается "request cancelled"......

2024-03-01 18:48 UTC, qkrorlqr approved these changes

2024-03-01 19:50 UTC, debnatkh approved these changes

2024-03-01 19:53 UTC, merged