NBS #179: switch fast path volume to regular path during migrations
ydb-platform/nbs pull request #512
Opened 2024-02-21 10:51 UTC by budevg

When volume starts migration the endpoint will be switched to use regular data
path (NRD volume through actor system).

Additionally when "use-fastpath" added/removed to volume tags the endpoint will
switch to use fast/regular data path

Additionally resolves #312

2024-02-26 10:23 UTC, drbasic requested changes

2024-02-26 10:23 UTC, drbasic commented on cloud/blockstore/libs/storage/partition_nonrepl/part_nonrepl_migration_common_actor_migration.cpp
> +    if (!MigrationStarted
clang-format кажется по-другому форматирует

2024-02-26 10:23 UTC, drbasic commented on cloud/blockstore/libs/storage/partition_nonrepl/part_nonrepl_migration_common_actor_migration.cpp
> +    auto deadline =
зачем убирать const?

2024-02-26 10:23 UTC, drbasic commented on cloud/blockstore/libs/storage/volume/volume_actor_migration.cpp
> +        actorSystem->Send(
NCloud::Reply()

2024-02-26 10:23 UTC, drbasic commented on cloud/blockstore/libs/storage/volume/volume_actor_migration.cpp
> +        .Subscribe([=] (const auto& future) {
лучше явно захватывать все что нужно, а не [=]
Потому что можно захватить случайно this, при этом гарантии что фьюча выполнится до того как сдохнет this ведь нет?

2024-02-26 10:23 UTC, drbasic commented on cloud/blockstore/libs/endpoints/endpoint_events.cpp
> +    TFuture<NProto::TError> SwitchEndpointIfNeeded(
я правильно понимаю что SwitchEndpoint может переключать только в одну сторону, на медленную, акторную реализацию?

2024-02-26 10:23 UTC, drbasic commented on cloud/blockstore/libs/storage/partition_nonrepl/part_nonrepl_migration_ut.cpp
> +            TMigrationStatePtr migrationState = nullptr)
если убрать = nullptr много мест придется поправить? лучше по-меньше использовать дефолты для параметров.

2024-02-26 10:23 UTC, drbasic commented on cloud/blockstore/libs/storage/partition_nonrepl/ut_env.h
> +        NCloud::Reply(ctx, *ev,
clang-format

2024-02-26 10:23 UTC, drbasic commented on cloud/blockstore/libs/storage/volume/volume_actor_migration.cpp
> +        ev->Sender,
clang-format

2024-02-26 10:28 UTC, drbasic requested changes

2024-02-26 10:28 UTC, drbasic commented on cloud/blockstore/libs/storage/volume/volume_state.h
> +    bool UseFastPath = false;
нужно в какую-нибудь метрику отгружать какой путь используется, быстрый или медленный

2024-02-26 13:30 UTC, budevg commented on cloud/blockstore/libs/endpoints/endpoint_events.cpp
> +    TFuture<NProto::TError> SwitchEndpointIfNeeded(
Не он может переключаться в обе стороны. Когда миграция закончится, он опять переключится в быструю реализацию.

2024-02-27 09:56 UTC, drbasic approved these changes

2024-02-27 09:56 UTC, drbasic commented on cloud/blockstore/libs/storage/volume/volume_actor_migration.cpp
> +                    migrationAllowed);
тут NCloud::Reply не сработает?

2024-02-27 14:54 UTC, budevg commented on cloud/blockstore/libs/storage/volume/volume_actor_migration.cpp
> +                    migrationAllowed);
не хотел ctx копировать в ламбду вроде он большой а для NCloud::Reply он используется

2024-02-27 16:16 UTC, budevg commented on cloud/blockstore/libs/endpoints/endpoint_manager.cpp
> +TFuture<NProto::TError> TEndpointManager::SwitchEndpointIfNeeded(
На самом деле endpoint manager имеет одинаковую структуру функций для всех API-вызовов
- FuncName - вызов корутины API-вызова
- DoFuncName - проверка коллизий с другими API-вызовами в соответствующей конечной точке и вызывание фактической реализации
- FuncNameImpl - фактическая реализация
Возможно, можно сделать рефакторинг, чтобы сократить количество методов, но это не входит в этот пр.

Дополнительный `SwitchEndpointIfNeeded` - это API, предназначенный для вызова из системы Actor, а "IfNeeded" призвано подчеркнуть, что endpoint не обязательно переключается. Вызывающая функция не знает, что на самом деле произойдет, и все, что ей нужно, это сделать вызов и дождаться его успешного завершения.

2024-02-27 16:20 UTC, budevg commented on cloud/blockstore/libs/endpoints/endpoint_manager_ut.cpp
> +    Y_UNIT_TEST(ShouldSwitchEndpointWhenNotified)
поменяю на `ShouldSwitchEndpointWhenEndpointStarted`

2024-02-28 13:54 UTC, budevg commented on cloud/blockstore/libs/storage/volume/volume_state.h
> +    bool UseFastPath = false;
на rdma и ic у нас есть отдельные и более детальные метрики ... здесь просто метрика индикатор на data path ... можно попробовать сделать индикатор на  ic, rdma но кажется лучше отдельным пр

2024-02-28 14:08 UTC, tpashkin submitted a review, later dismissed

2024-02-28 14:08 UTC, tpashkin commented on cloud/blockstore/libs/endpoints/session_manager.cpp
> +                                         // validation false posiitives
posiitives -> positives

2024-02-28 14:11 UTC, tpashkin approved these changes

2024-02-28 16:38 UTC, merged