clarify callers and interfaces
ydb-platform/nbs pull request #518
Opened 2024-02-21 13:59 UTC by tpashkin

2024-02-21 14:12 UTC, budevg requested changes

2024-02-21 14:12 UTC, budevg commented on cloud/blockstore/libs/rdma/impl/client.cpp
> +// implements IClientEndpoint
do we really need this `implements` comment ? we already have `override` specifier in the header and rest of the code doesn't mark overridden methods this way

2024-02-21 14:16 UTC, drbasic commented
Объясню почему я очень-очень прошу прописать потоки именно в реализации методов.

Меня заинтересовало, нет ли случайно многопоточного доступа к ActiveRequests.
Для этого я начал смотреть все мотоды, которые обращаются к полю. Нажожу метод - он приватный. Ищу все места где он зовется. Ищу описание этого метода. вижу что он снова приватный, повторяю. нахожу публичый метод. Запоминаю поток. и так по всем методам, натыкаюсь на приватный, который никто не зовет из публичного. Точно, это метод из публичного интерфейса, и поток не прописан. Все. Задолбался и ничего не сделал - я не могу дальше проверить потоки. 
Еще тут я вижу есть друзья, которые тоже дергают приватные поля. А их то как проверять???! 

Я настаиваю, что если мы пишем многопотчный код, то должно быть просто находить из каких потоков что зовется, какие поля трогаются. И чтобы было разложено минимальное количество граблей, типа френдов и методов, реализующих публичный интерфейс в приватной секции. А сам публичный интерфейс был мнималистичный.

Чтобы стало совсем хорошо нужно удалить всех friend  и вынести все что им нужно в публичный интерфейс.

2024-02-21 14:17 UTC, drbasic commented on cloud/blockstore/libs/rdma/impl/client.cpp
> +// implements IClientEndpoint
Желательно, это упрощает чтение кода.

2024-02-22 08:48 UTC, budevg commented
> Объясню почему я очень-очень прошу прописать потоки именно в реализации методов.
> 
I believe a better approach is to use a method name prefix to indicate from which thread the method is being called. For instance, using `CQSomeName` for completion queue methods. While comments provide useful information, they need to be maintained and require you to find the interface where the comment remark is located. With function names, the intent of the method is immediately apparent.

2024-02-22 08:48 UTC, budevg approved these changes

2024-02-22 09:31 UTC, drbasic approved these changes

2024-02-22 12:15 UTC, qkrorlqr commented on cloud/blockstore/libs/rdma/impl/client.cpp
> +// implements IClientEndpoint
Как-то дохрена таких комментов получается
Я тоже не понимаю, зачем - ты же если читаешь или правишь код, явно посмотришь в declaration, а там написано override

2024-02-23 15:24 UTC, tpashkin commented
> Я настаиваю, что если мы пишем многопоточный код, то должно быть просто находить из каких потоков что зовется, какие поля трогаются. И чтобы было разложено минимальное количество граблей, типа френдов и методов, реализующих публичный интерфейс в приватной секции. А сам публичный интерфейс был мнималистичный.
Да я в общем-то согласен, постараюсь заняться в ближайшее время

> Чтобы стало совсем хорошо нужно удалить всех friend  и вынести все что им нужно в публичный интерфейс
Это 100%

> I believe a better approach is to use a method name prefix to indicate from which thread the method is being called. For instance, using `CQSomeName` for completion queue methods. While comments provide useful information, they need to be maintained and require you to find the interface where the comment remark is located. With function names, the intent of the method is immediately apparent.
Можно попробовать, но мне не очень нравится идея добавления имени треда в название метода. Я бы лучше разнёс методы по интерфейсам, которыми пользуется определённый тред, а сам ендпоинт разбил на пачку классов

2024-02-23 15:25 UTC, merged