NBS-4918 : Move features to storage.
ydb-platform/nbs pull request #534
Opened 2024-02-22 10:33 UTC by NewBediver

2024-02-22 10:41 UTC, qkrorlqr commented
что-то большой дифф

там какие-то файлы удалены и созданы заново, а не помуваны?

2024-02-22 10:43 UTC, qkrorlqr commented on cloud/blockstore/config/features.proto
> -syntax = "proto2";
что-то тут написано, что файл удаляется, а не мувается - не понимаю, я смотрю куда-то не туда или github как-то неправильно дифф рисует?

2024-02-22 10:51 UTC, NewBediver commented on cloud/blockstore/config/features.proto
> -syntax = "proto2";
Странно, он действительно просто пропал... Должен был быть в storage/core/config, но его там нет. Есть только правки в ya.make файле

2024-02-22 11:22 UTC, NewBediver commented on cloud/blockstore/config/features.proto
> -syntax = "proto2";
Там еще папка storage/core/libs/features исчезла. Что-то странно как-то все залилось

2024-02-22 18:09 UTC, NewBediver commented on cloud/blockstore/config/features.proto
> -syntax = "proto2";
Вроде все вернул на место, но стоит еще раз внимательно проверить. Очень странные дела произошли и ничего никуда не мувнулось, а просто удалилось

2024-02-26 10:25 UTC, yegorskii requested changes
А почему tabletId, а не Id какой-ниюудь? По крайней мере в NBS у диска tabletId может меняться

2024-02-26 11:21 UTC, NewBediver commented
> А почему tabletId, а не Id какой-ниюудь? По крайней мере в NBS у диска tabletId может меняться

Хорошо, давай тогда заведем поле id, в котором будем писать fsId или diskId. Они же вроде точно остаются уникальными?

2024-02-26 11:31 UTC, NewBediver commented
> > А почему tabletId, а не Id какой-ниюудь? По крайней мере в NBS у диска tabletId может меняться
> 
> Хорошо, давай тогда заведем поле id, в котором будем писать fsId или diskId. Они же вроде точно остаются уникальными?

Вообще в этом ПР убрал новое поле в конфиге. Чтобы его правильно обработать нужно писать дополнительный код. Не хочу это делать в ПРе с переносом

2024-02-26 12:01 UTC, qkrorlqr approved these changes

2024-02-26 12:06 UTC, yegorskii approved these changes

2024-02-26 12:34 UTC, merged