Silent E_NOT_FOUND in GetDependentDisks and UpdateDiskRegistryParams requests
ydb-platform/nbs pull request #572
Opened 2024-02-27 10:31 UTC by dvrazumov

2024-03-01 13:52 UTC, sharpeye submitted a review, later dismissed

2024-03-05 14:51 UTC, qkrorlqr approved these changes

2024-03-07 12:11 UTC, drbasic requested changes

2024-03-07 12:11 UTC, drbasic commented on cloud/storage/core/libs/common/helpers.h
> +#include <cloud/storage/core/protos/error.pb.h>
nit. clang-format сортирует список инклюдов правильно

2024-03-07 12:11 UTC, drbasic commented on cloud/storage/core/libs/common/helpers.h
> +void SetErrorProtoFlag(NProto::TError& error, const T flag)
@qkrorlqr нам бы обсудить, да зафиксировать где-то требования к коду. Так как я покусаный хромиковским кодстайлом, мне кажется мы можем писать более предстказуемый код.

В частности, я бы предпочел такую сигнатуру:
void SetErrorProtoFlag(const T flag, NProto::TError* error)
1. первыми идут входные параметры
2. если объект меняется, он передается по укаателю

2024-03-07 12:11 UTC, drbasic commented on cloud/storage/core/libs/common/helpers.h
> +template <typename T>
почему понадобилось делать функцию шаблонной?

2024-03-07 16:08 UTC, qkrorlqr approved these changes

2024-03-07 16:10 UTC, qkrorlqr commented on cloud/storage/core/libs/common/helpers.h
> +void SetErrorProtoFlag(NProto::TError& error, const T flag)
> В частности, я бы предпочел такую сигнатуру:
> void SetErrorProtoFlag(const T flag, NProto::TError* error)

> первыми идут входные параметры
> если объект меняется, он передается по укаателю

@drbasic да, я согласен и стараюсь делать __почти__ так же - с разницей в том, что по указателю передаю чистые output-параметры (которые ф-ция полностью инициализирует), а если метод просто сетит какое-то одно поле, то не по указателю, а по ссылке

2024-03-07 16:29 UTC, merged