NBSNEBIUS-105: ADD_HOST registers unknown devices
ydb-platform/nbs pull request #597
Opened 2024-02-29 22:05 UTC by sharpeye

2024-03-04 13:48 UTC, qkrorlqr commented on cloud/blockstore/libs/storage/disk_registry/disk_registry_actor.cpp
> +#include <util/string/join.h>
алфавит

2024-03-04 15:06 UTC, qkrorlqr commented on cloud/blockstore/libs/storage/disk_registry/disk_registry_actor.cpp
> +    const TVector<TString>& devicesNeedToBeClean,
devicesThatNeedToBeClean?

2024-03-04 15:12 UTC, komarevtsev-d commented on cloud/blockstore/libs/storage/disk_registry/disk_registry_actor.cpp
> +    const TVector<TString>& devicesNeedToBeClean,
Почему const& devicesNeedToBeClean, а не по значению?

2024-03-04 15:16 UTC, komarevtsev-d commented on cloud/blockstore/libs/storage/disk_registry/disk_registry_actor_update_cms_host_state.cpp
> +            });
А у инфры тулза теперь не начнёт таймаутиться из-за этого? Нужно кого-то предупредить?

2024-03-04 15:42 UTC, qkrorlqr requested changes
Непонятен смысл того, что происходит. Описания нет, куча кода туда-сюда поездила. Пропала большая ф-ция AddNewDevices, появилась новая вместо нее - RegisterUnknownDevices. Postpone был переделан каким-то образом. Не понимаю, как ревьюить такой PR без описания того, что вообще задумано было тут сделать.

2024-03-04 15:42 UTC, qkrorlqr commented on cloud/blockstore/libs/storage/disk_registry/disk_registry_actor.cpp
> +            NCloud::Reply(ctx, *requestInfo, responseFactory(std::move(error)));
а зачем это тут обрабатывать, а не на стороне агента? тут получается, что 1 плохой девайс заблокирует очистку всех остальных

2024-03-04 15:42 UTC, qkrorlqr commented on cloud/blockstore/libs/storage/disk_registry/disk_registry_state.cpp
> +    if (newState != NProto::AGENT_STATE_ONLINE && result.GetCode() == S_OK) {
а почему именно на S_OK проверяем, а не на любой успешный код?

2024-03-04 16:03 UTC, qkrorlqr commented
Надо после того, как доделаем все, что делаем сейчас в районе DR - автообнаружение девайсов, правки в районе acquire/release, довнедрение локальных дисков - перейти к рефакторингу DR. По очереди пройтись по ручкам и вынести сложные сценарии в какие-то внешние контроллеры. Например, все сложные CMS-ные сценарии типа добавленного тут можно вынести в какой-нибудь TCMSController, который будет жить внутри TDiskRegistryActor и дергать ручки State. Потом можно какой-нибудь TMigrationController вынести. И т.д.

2024-03-04 16:06 UTC, sharpeye commented on cloud/blockstore/libs/storage/disk_registry/disk_registry_actor_update_cms_host_state.cpp
> +            });
Да, с Инфрой надо обсудить. Им нужно будет ретраить таймауты и смерть DR, если они еще не умеют.

2024-03-04 16:09 UTC, sharpeye commented on cloud/blockstore/libs/storage/disk_registry/disk_registry_actor.cpp
> +            NCloud::Reply(ctx, *requestInfo, responseFactory(std::move(error)));
DR не отправит на зачистку сломанный девайс. Кажется, тут стоит возвращать сразу error - чтобы Инфра сразу видела проблему.

2024-03-04 16:11 UTC, sharpeye commented on cloud/blockstore/libs/storage/disk_registry/disk_registry_state.cpp
> +    if (newState != NProto::AGENT_STATE_ONLINE && result.GetCode() == S_OK) {
Да, можно на любой.

2024-03-04 17:03 UTC, sharpeye commented on cloud/blockstore/libs/storage/disk_registry/disk_registry_actor.cpp
> +    const TVector<TString>& devicesNeedToBeClean,
Внутри ничего не мувается. Можно, конечно, помувать строки куда-нибудь в ```PendingWaitForDeviceCleanupRequests[std::move(id)] = ...``` например, но, кажется, это не критично.

2024-03-04 17:08 UTC, komarevtsev-d commented on cloud/blockstore/libs/storage/disk_registry/disk_registry_actor.cpp
> +    const TVector<TString>& devicesNeedToBeClean,
Так а в PendingDevices нельзя вмувать?
Ну и в самом месте вызова метода PostponeResponse() ты муваешь вектор. Получатеася там мув можно убрать тогда?

2024-03-05 03:35 UTC, komarevtsev-d commented on cloud/blockstore/libs/storage/disk_registry/disk_registry_actor.cpp
> +    const TVector<TString>& devicesNeedToBeClean,
Да, тут

2024-03-05 12:13 UTC, sharpeye commented on cloud/blockstore/libs/storage/disk_registry/disk_registry_actor.cpp
> +    const TVector<TString>& devicesNeedToBeClean,
PendingDevices - это hash set, т.е. целиком вектор не помувать

2024-03-11 07:17 UTC, komarevtsev-d approved these changes

2024-03-11 10:18 UTC, drbasic commented on cloud/blockstore/libs/storage/disk_registry/disk_registry_actor_update_cms_host_state.cpp
> +            });
А мы можем не отрывать сразу ручку про девайс, чтобы не ломать тулзу инфры?
А когда они передут, уже тогда удалить ручку.

2024-03-11 10:50 UTC, drbasic commented on cloud/blockstore/libs/storage/disk_registry/disk_registry_actor_update_cms_host_state.cpp
> +            });
Обсудили. Нет, инфра сейчас вообще ничего не должна заметить.

2024-03-20 08:41 UTC, komarevtsev-d requested changes
Договорились с инфрой, что они не будут ждать долгий ответ от ADD_HOST. Поэтому тут нужно поставить диски на ансинхронную очистку (если взведён `NonReplicatedDontSuspendDevices`) и сразу ответить.

2024-03-28 13:13 UTC, closed without merging