Update placement groups view in monitoring
ydb-platform/nbs pull request #603
Opened 2024-03-01 12:02 UTC by dvrazumov

2024-03-01 14:16 UTC, qkrorlqr commented on cloud/blockstore/libs/storage/disk_registry/disk_registry_actor_monitoring.cpp
> +                        size_t totalPartitionsCount = isPartitionGroup ?
давай лучше переносить ? и : в начало след строки - мы обычно так пишем

2024-03-01 14:17 UTC, qkrorlqr commented on cloud/blockstore/libs/storage/disk_registry/disk_registry_actor_monitoring.cpp
> +                        if(brokenPartitionsCount > 0) {
пробела после if не хватает

2024-03-01 14:17 UTC, qkrorlqr commented on cloud/blockstore/libs/storage/disk_registry/disk_registry_actor_monitoring.cpp
> +                                TABLED() { out << "Disks count"; }
Disk count

2024-03-01 14:31 UTC, drbasic requested changes

2024-03-01 14:31 UTC, drbasic commented on cloud/blockstore/libs/storage/disk_registry/disk_registry_actor_monitoring.cpp
> +        bool d1Broken = brokenDisks.contains(d1->GetDiskId());
не уверен что ты написал корректный компаратор.
Лучше сделай так:
```
    auto make_val = [](const TDiskIterator& d){
        return std::make_tuple(
            brokenDisks.contains(d->GetDiskId()),
            d->GetPlacementPartitionIndex(),
            d->GetDiskId()
        );
    };
    return make_val(d1) < make_val(d2);
```

2024-03-01 14:31 UTC, drbasic commented on cloud/blockstore/libs/storage/disk_registry/disk_registry_actor_monitoring.cpp
> -            for (const auto& x: State->GetPlacementGroups()) {
тут явно есть строки длиннее 80 символов. Сдаелай clang-format  фрагмента, который редактируешь

2024-03-01 14:31 UTC, drbasic commented on cloud/blockstore/libs/storage/disk_registry/disk_registry_actor_monitoring.cpp
> +                    auto it = brokenGroups.find(groupId);
попробуй использовать brokenGroups.FindIf(groupId) вместо работы с итераторами?

2024-03-01 14:31 UTC, drbasic commented on cloud/blockstore/libs/storage/disk_registry/disk_registry_actor_monitoring.cpp
> +                        size_t totalPartitionsCount = isPartitionGroup ?
clang-format должен делать правильно

2024-03-01 15:41 UTC, dvrazumov commented on cloud/blockstore/libs/storage/disk_registry/disk_registry_actor_monitoring.cpp
> -            for (const auto& x: State->GetPlacementGroups()) {
Пофиксил явные заступы

2024-03-01 19:03 UTC, qkrorlqr approved these changes

2024-03-02 04:50 UTC, drbasic approved these changes

2024-03-02 11:10 UTC, merged