NBSNEBIUS-146: don't generate critical events on health check read during secure erase
ydb-platform/nbs pull request #699
Opened 2024-03-11 14:47 UTC by budevg

Additionally report non health check reads during secure erase and add aditional
info to the critical event report

2024-03-11 15:56 UTC, drbasic requested changes

2024-03-11 15:56 UTC, drbasic commented on cloud/blockstore/libs/storage/disk_agent/disk_agent_actor_io.cpp
> +        if (IsWriteDeviceMethod<TMethod> || clientId != CheckHealthClientId) {
```
const bool allowedReadingDuringErase =
 !IsWriteDeviceMethod<TMethod> && 
 clientId == CheckHealthClientId;
if (!allowedReadingDuringErase){...}
```
кстати может сделать IsReadDeviceMethod() ?

2024-03-11 15:56 UTC, drbasic commented on cloud/blockstore/libs/storage/disk_agent/disk_agent_actor_ut.cpp
> +                ->Record.GetError()
clang-format

2024-03-11 15:56 UTC, drbasic commented on cloud/blockstore/libs/storage/disk_agent/rdma_target.cpp
> +                    << (request.GetStartIndex() + request.GetBlocksCount() - 1)
может удобнее выводить  BlockCount вместо EndIndex?

2024-03-11 17:17 UTC, budevg commented on cloud/blockstore/libs/storage/disk_agent/disk_agent_actor_ut.cpp
> +                ->Record.GetError()
Я исправил это, но clang-format форматирует это как
```c++
        UNIT_ASSERT_VALUES_EQUAL(
            E_REJECTED,
            ReadDeviceBlocks(
                runtime,
                diskAgent,
                "uuid",
                0,
                1,
                TString(CheckHealthClientId))
                ->Record.GetError()
                .GetCode());
```
вместо
```
        UNIT_ASSERT_VALUES_EQUAL(
            E_REJECTED,
            ReadDeviceBlocks(
                runtime,
                diskAgent,
                "uuid",
                0,
                1,
                TString(CheckHealthClientId))->Record.GetError().GetCode());
```

2024-03-11 17:19 UTC, budevg commented on cloud/blockstore/libs/storage/disk_agent/rdma_target.cpp
> +                    << (request.GetStartIndex() + request.GetBlocksCount() - 1)
проще использовать `BlockCount`, но я хотел, чтобы сообщение об ошибке выглядело как сообщение в `disk_agent_actor_io.cpp`

2024-03-12 04:42 UTC, drbasic commented on cloud/blockstore/libs/storage/disk_agent/rdma_target.cpp
> +                    << (request.GetStartIndex() + request.GetBlocksCount() - 1)
Так а что мешает там написать BlockCount? У TBlockRange64 есть для этого метод Size()

2024-03-12 04:43 UTC, drbasic submitted a review, later dismissed

2024-03-12 07:07 UTC, drbasic commented on cloud/blockstore/libs/storage/disk_agent/disk_agent_actor_ut.cpp
> +                ->Record.GetError()
Попробую покрутить clang-format, мне кажется должно вот так отформатироваться:
```
        UNIT_ASSERT_VALUES_EQUAL(
            E_REJECTED,
            ReadDeviceBlocks(
                runtime,
                diskAgent,
                "uuid",
                0,
                1,
                TString(CheckHealthClientId))
                    ->Record.GetError()
                    .GetCode());
```

2024-03-12 09:19 UTC, tpashkin commented on cloud/blockstore/libs/storage/disk_agent/disk_agent_actor_io.cpp
> +        const bool allowedReadingDuringSecureErase =
Немного режет глаз, может "allowedToRead"?

2024-03-12 09:33 UTC, tpashkin commented on cloud/blockstore/libs/storage/disk_agent/disk_agent_actor_io.cpp
> +        range = TBlockRange64::WithLength(
Ничего не сломается от того, что с этой правкой replyError будет возвращать непустой range для read-запросов?

2024-03-12 09:48 UTC, budevg commented on cloud/blockstore/libs/storage/disk_agent/disk_agent_actor_io.cpp
> +        const bool allowedReadingDuringSecureErase =
давай лучше `isHealthCheckRead`

2024-03-12 09:51 UTC, tpashkin approved these changes

2024-03-12 09:53 UTC, drbasic approved these changes

2024-03-12 11:07 UTC, merged