[draft] issue-539: add two-stage writes for scaling throughput
ydb-platform/nbs pull request #707
Opened 2024-03-11 19:04 UTC by debnatkh

#539

2024-03-20 10:44 UTC, qkrorlqr requested changes
Надо вынести подготовительные правки в отдельный PR, иначе будем очень долго это ревьюить. Подготовительные правки - это, например, вынос TWriteDataActor в tablet/actors/, это вынос кода валидации запроса из HandleWriteData в отдельную функцию и другие подобные правки

2024-03-20 10:44 UTC, qkrorlqr commented on cloud/filestore/config/storage.proto
> +    optional bool TwoStageWriteEnabled = 338;
это все-таки ThreeStageWrite

2024-03-20 10:44 UTC, qkrorlqr commented on cloud/filestore/config/storage.proto
> +    // When issuing blobs, the tablet acquires collect barrier. In order to
blob ids
a collect barrier

2024-03-20 10:44 UTC, qkrorlqr commented on cloud/filestore/libs/storage/api/tablet.h
> +    xxx(GenerateBlobs,              __VA_ARGS__)                               \
GenerateBlobIds

2024-03-20 10:44 UTC, qkrorlqr commented on cloud/filestore/libs/storage/core/config.cpp
> +    xxx(GenerateBlobsReleaseCollectBarrierTimeout,                                 \
отступ до \ выглядит неправильно

2024-03-20 10:44 UTC, qkrorlqr commented on cloud/filestore/libs/storage/tablet/model/blob_builder.cpp
> +    bool shouldFillBlobContent)
почему это параметр метода Accept, а не параметр конструктора TMergedBlobBuilder?

2024-03-20 10:44 UTC, qkrorlqr commented on cloud/filestore/libs/storage/tablet/model/blob_builder.cpp
> +        Y_ABORT_UNLESS(buffer.GetBlockSize() == BlockSize);
зачем делать эту проверку столько раз, сколько у нас блоков? зачем она вообще тут нужна в случае, когда мы не наполняем blobContent?

2024-03-20 10:44 UTC, qkrorlqr commented on cloud/filestore/libs/storage/tablet/model/blob_builder.cpp
> +        Y_ABORT_UNLESS(buffer.GetBlockSize() == BlockSize);
и вообще что-то я не понимаю, в чем смысл переиспользовать TMergedBlobBuilder

он не делает практически ничего, кроме наполнения blobContent

ты тут еще и зачем-то оставил аллокацию: blobContent.reserve(blocksCount * BlockSize)

2024-03-20 10:44 UTC, qkrorlqr commented on cloud/filestore/libs/storage/tablet/model/garbage_queue.cpp
> +void TGarbageQueue::ReleaseCollectBarrier(ui64 commitId, bool allowMissing)
этот параметр выглядит коряво

обычно делают TryDoSomething, который возвращает bool в зависимости от того, получилось сделать Something или не получилось, и враппер для него вида DoSomething, который ничего не возвращает, зовет TryDoSomething и валидирует возвращаемое значение от TryDoSomething

2024-03-20 10:44 UTC, qkrorlqr commented on cloud/filestore/libs/storage/tablet/model/garbage_queue.cpp
> +    return it != Impl->Barriers.end() && it->RefCount > 0;
а почему у нас может быть барьер с RefCount == 0?

2024-03-20 10:44 UTC, qkrorlqr commented on cloud/filestore/libs/storage/tablet/tablet_actor_adddata.cpp
> +    TABLET_VERIFY(args.Node);
это очень плохой verify, т.к. NodeId приходит со стороны клиента, т.о. мы крешимся, если клиент прислал что-то не то - так ни в коем случае делать нельзя и WriteData тоже надо поправить

здесь это вдвойне плохо, т.к. между инициированием записи со стороны клиента и этим местом проходит больше времени (т.к. клиент сначала генерит blobId, потом пишет, потом шлет запрос, приводящий к AddData)

надо репортить CritEvent в release и крешиться в debug - например, вот так: https://github.com/ydb-platform/nbs/blob/dbc5a798b2d083ad506c9ac7a9513a2a6e3ea09d/cloud/storage/core/libs/diagnostics/critical_events.h#L41

2024-03-20 10:44 UTC, qkrorlqr commented on cloud/filestore/libs/storage/tablet/tablet_actor_adddata.cpp
> +    FILESTORE_VALIDATE_TX_ERROR(WriteData, args);
а зачем? этот макрос не делает ничего, кроме return: https://github.com/ydb-platform/nbs/blob/dbc5a798b2d083ad506c9ac7a9513a2a6e3ea09d/cloud/filestore/libs/storage/tablet/tablet_tx.h#L55

2024-03-20 10:44 UTC, qkrorlqr commented on cloud/filestore/libs/storage/tablet/tablet_actor_adddata.cpp
> +        ReleaseCollectBarrier(args.CommitId, true);
зачем 2 раза?

2024-03-20 10:44 UTC, qkrorlqr commented on cloud/filestore/libs/storage/tablet/tablet_actor_adddata.cpp
> +    if (FAILED(args.Error.GetCode())) {
а почему не HasError(args.Error)?

2024-03-20 10:44 UTC, qkrorlqr commented on cloud/filestore/libs/storage/tablet/tablet_actor_adddata.cpp
> +    IBlockBufferPtr buffer = CreateLazyBlockBuffer(args.ByteRange);
и builder не нужен, и этот buffer не нужен

2024-03-20 10:44 UTC, qkrorlqr commented on cloud/filestore/libs/storage/tablet/tablet_actor_adddata.cpp
> +////////////////////////////////////////////////////////////////////////////////
отбивка идет после namespace {

2024-03-20 10:44 UTC, qkrorlqr commented on cloud/filestore/libs/storage/tablet/tablet_actor_adddata.cpp
> +    IBlockBufferPtr buffer = CreateLazyBlockBuffer(range);
тут не нужны ни buffer, ни builder

2024-03-20 10:44 UTC, qkrorlqr commented on cloud/filestore/libs/storage/tablet/tablet_actor_adddata.cpp
> +        args.Error = ErrorInvalidHandle(args.Handle);
а если файл просто удалили уже, мы не удалим барьер?

2024-03-20 10:44 UTC, qkrorlqr commented on cloud/filestore/libs/storage/tablet/tablet_actor_adddata.cpp
> +    // We schedule this event for the case if the client will not call
if the client does not call

2024-03-20 10:44 UTC, qkrorlqr commented on cloud/filestore/libs/storage/tablet/tablet_actor_adddata.cpp
> +    if (!CompactionStateLoadStatus.Finished) {
я там в другом PR закоммитил IsDataOperationAllowed и использовал его в разных хендлерах - сделай, пожалуйста, аналогично

2024-03-20 10:44 UTC, qkrorlqr commented on cloud/filestore/libs/storage/tablet/tablet_actor_adddata.cpp
> +    // We acquire the collect barrier for the second time in order to prolong an
an already acquired lease -> the already acquired lease

2024-03-20 10:44 UTC, qkrorlqr commented on cloud/filestore/libs/storage/tablet/tablet_actor_adddata.cpp
> +    auto validator = [&](const NProtoPrivate::TAddDataRequest& request)
этот валидатор вроде такой же как в HandleWriteData - надо его код вынести в общее место

2024-03-20 10:44 UTC, qkrorlqr commented on cloud/filestore/libs/storage/tablet/tablet_actor_adddata.cpp
> +    TABLET_VERIFY(!blobIds.empty());
а если клиент прислал пустой список BlobId-ов? нельзя крешиться на валидации запроса клиента

сделай хотя бы через STORAGE_PRECONDITION_FAILED

2024-03-20 10:44 UTC, qkrorlqr commented on cloud/filestore/libs/storage/tablet/tablet_actor_writedata.cpp
> +#include "tablet_actor_writedata_actor.h"
лучше переместить в cloud/filestore/libs/storage/tablet/actors/ - так сделано в других местах в нашем коде

2024-03-20 10:44 UTC, qkrorlqr commented on cloud/filestore/libs/storage/tablet/tablet_actor_writedata_actor.cpp
> +#include "tablet_actor_writedata_actor.h"
код этого актора не поменялся?

2024-03-20 10:44 UTC, qkrorlqr commented on cloud/filestore/libs/storage/tablet/tablet_private.h
> +        ui64 CommitId;
надо либо дефолтный конструктор удалить, либо явным образом нулями инициализировать

явный конструктор, который обязывает передать оба параметра, - лучше

2024-03-20 10:44 UTC, qkrorlqr commented on cloud/filestore/libs/storage/tablet/tablet_ut_data.cpp
> +                UNIT_ASSERT_VALUES_EQUAL(blob.BlobSize(), expectedSizes[i]);
если эти ассерты выстрелят, непонятно будет, какой из вызовов checkGeneratedBlob их вызвал
так что лучше checkGeneratedBlob оформить в виде макроса, а не функции

2024-03-20 10:44 UTC, qkrorlqr commented on cloud/filestore/private/api/protos/tablet.proto
> +    // Length of data to write.
длина тоже aligned должна быть

2024-03-20 14:42 UTC, debnatkh commented on cloud/filestore/libs/storage/tablet/model/garbage_queue.cpp
> +    return it != Impl->Barriers.end() && it->RefCount > 0;
Это сделано чтобы в `GarbageBlobs` шли блобы в порядке возрастания коммитов:

2024-03-20 14:45 UTC, debnatkh commented on cloud/filestore/libs/storage/tablet/tablet_actor_adddata.cpp
> +    TABLET_VERIFY(args.Node);
Там выше есть проверка, что это валидная NodeId же. 

https://github.com/ydb-platform/nbs/blob/a1f43fc07999c116f873ed21412b52666fd85e5d/cloud/filestore/libs/storage/tablet/tablet_actor_writedata.cpp#L436-L442

2024-03-20 14:54 UTC, debnatkh commented on cloud/filestore/libs/storage/tablet/tablet_actor_adddata.cpp
> +        args.Error = ErrorInvalidHandle(args.Handle);
Удалим в `CompleteTx_AddData`. Про это добавил тест. Только в нём реджектится запрос не из-за того, что файл удалили, а из-за RDONLY

https://github.com/ydb-platform/nbs/blob/7a980f3c4426da259599f99cc17e81a061e702c1/cloud/filestore/libs/storage/tablet/tablet_ut_data.cpp#L4040-L4065

2024-03-21 21:35 UTC, qkrorlqr commented on cloud/filestore/libs/storage/tablet/tablet_actor_adddata.cpp
> +    TABLET_VERIFY(args.Node);
Не понял, какая проверка? if (!ReadNode)? Это не проверка, это if на случай, если в памяти нет нужных данных - чтоб их зачитать и перезапустить Prepare-стадию транзакции

2024-03-22 10:20 UTC, debnatkh commented on cloud/filestore/libs/storage/tablet/tablet_actor_adddata.cpp
> +    TABLET_VERIFY(args.Node);
Да, сори
Это не та проверка

Но я всё равно не очень понимаю, как NodeId может быть невалидна, если handle валиден, а NodeId берётся из handle?

Такая же логика происходит в writedata:
https://github.com/ydb-platform/nbs/blob/a1f43fc07999c116f873ed21412b52666fd85e5d/cloud/filestore/libs/storage/tablet/tablet_actor_writedata.cpp#L425
https://github.com/ydb-platform/nbs/blob/a1f43fc07999c116f873ed21412b52666fd85e5d/cloud/filestore/libs/storage/tablet/tablet_actor_writedata.cpp#L442

2024-03-25 18:35 UTC, qkrorlqr commented on cloud/filestore/libs/storage/tablet/tablet_actor_adddata.cpp
> +    TABLET_VERIFY(args.Node);
ok

2024-03-27 16:40 UTC, qkrorlqr commented on cloud/filestore/config/storage.proto
> +
лишняя пустая строка

2024-03-27 16:40 UTC, qkrorlqr commented on cloud/filestore/libs/storage/tablet/actors/tablet_writedata.cpp
> +    , SkipBlobStorage(skipBlobStorage)
давай лучше прямо напишем SkipWriteBlob

2024-03-27 16:40 UTC, qkrorlqr commented on cloud/filestore/libs/storage/tablet/actors/tablet_writedata.cpp
> +            // acquired at the GenerateBlob request and once for the lock
at the -> by the

2024-03-27 16:40 UTC, qkrorlqr commented on cloud/filestore/libs/storage/tablet/actors/tablet_writedata.cpp
> +    if (SkipBlobStorage) {
не вижу смысла в том, чтобы держать одного актора и делать в нем if-ы
осмысленная логика находится как раз в этих if-ах
давай лучше сделаем отдельного TAddDataActor - код будет аккуратнее (хоть и будет чуть больше строк)

2024-03-27 16:40 UTC, qkrorlqr commented on cloud/filestore/libs/storage/tablet/actors/tablet_writedata.cpp
> +            NCloud::Reply(ctx, *RequestInfo, std::move(response));
а почему в этой ветке не нужны ни ThrottlerInfo, ни TraceInfo?

2024-03-27 16:40 UTC, qkrorlqr commented on cloud/filestore/libs/storage/tablet/actors/tablet_writedata.cpp
>          "WriteData");
и вот тут на самом деле хочется видеть AddData для нового data path

2024-03-27 16:40 UTC, qkrorlqr commented on cloud/filestore/libs/storage/tablet/actors/tablet_writedata.h
> +    // This parameter is used for a scenario, when there is already a blobId
for the scenario

2024-03-27 16:40 UTC, qkrorlqr commented on cloud/filestore/libs/storage/tablet/actors/tablet_writedata.h
> +    // with data written to. In this case, we don't need to send requests to
written to it

2024-03-27 16:40 UTC, qkrorlqr commented on cloud/filestore/libs/storage/tablet/actors/tablet_writedata.h
> +    // blobstorage. This field is used only for two-stage writes. For more info
three-stage

2024-03-27 16:40 UTC, qkrorlqr commented on cloud/filestore/libs/storage/tablet/actors/tablet_writedata.h
> +    // see See #539
see 1 раз

2024-03-27 16:40 UTC, qkrorlqr commented on cloud/filestore/libs/storage/tablet/tablet_actor_adddata.cpp
> +
лишняя пустая строка

2024-03-27 16:40 UTC, qkrorlqr commented on cloud/filestore/libs/storage/tablet/tablet_actor_adddata.cpp
> +            MAKE_FILESTORE_ERROR(NProto::E_FS_INVAL),
просто E_ARGUMENT, без E_FS_* и без MAKE_FILESTORE_ERROR

2024-03-27 16:40 UTC, qkrorlqr commented on cloud/filestore/libs/storage/tablet/tablet_actor_adddata.cpp
> +                "");
надо написать /* data buffer */

2024-03-27 16:40 UTC, qkrorlqr commented on cloud/filestore/libs/storage/tablet/tablet_actor_adddata.cpp
> +    for (auto [targetBlob, srcBlob]: Zip(blobs, args.BlobIds)) {
auto&

2024-03-27 16:40 UTC, qkrorlqr commented on cloud/filestore/libs/storage/tablet/tablet_actor_adddata.cpp
> +namespace {
давай это вынесем в начало файла

2024-03-27 16:40 UTC, qkrorlqr commented on cloud/filestore/libs/storage/tablet/tablet_actor_adddata.cpp
> + * @returns A vector of sizes of the blobs that the data should be split into.
The vector

2024-03-27 16:40 UTC, qkrorlqr commented on cloud/filestore/libs/storage/tablet/tablet_actor_adddata.cpp
> +    TVector<ui64> blobs;
blobSizes

2024-03-27 16:40 UTC, qkrorlqr commented on cloud/filestore/libs/storage/tablet/tablet_actor_adddata.cpp
> +    // It is up to the client to provide the aligned range, but we still verify
an aligned range

2024-03-27 16:40 UTC, qkrorlqr commented on cloud/filestore/libs/storage/tablet/tablet_actor_collectgarbage.cpp
> +        // already have been released by a completed two-stage write operation
may have already been released

2024-03-27 16:40 UTC, qkrorlqr commented on cloud/filestore/libs/storage/tablet/tablet_actor_collectgarbage.cpp
> +        // already have been released by a completed two-stage write operation
three-stage

2024-03-27 16:40 UTC, qkrorlqr commented on cloud/filestore/libs/storage/tablet/tablet_tx.h
> +    struct TAddData : TSessionAware
перед : пробел не ставим

2024-03-27 16:40 UTC, qkrorlqr commented on cloud/filestore/libs/storage/tablet/tablet_tx.h
> +        ui64 CommitId = InvalidCommitId;
инициализация не нужна, т.к. у тебя единственный конструктор сам инициализирует CommitId

2024-03-27 16:40 UTC, qkrorlqr commented on cloud/filestore/libs/storage/tablet/tablet_tx.h
> +                ui64 commitId,
странно выглядит, что порядок аргументов не такой, как порядок полей в структуре

2024-03-27 16:40 UTC, qkrorlqr commented on cloud/filestore/libs/storage/tablet/tablet_tx.h
> +            CommitId = InvalidCommitId;
а зачем? это же входной параметр, то есть он не меняется по ходу Prepare-стадии

2024-03-27 16:40 UTC, qkrorlqr commented on cloud/filestore/private/api/protos/tablet.proto
> +
лишняя строка

2024-03-27 16:40 UTC, qkrorlqr commented on cloud/filestore/private/api/protos/tablet.proto
> +    // Blob ids in the same order as in the request.
коммент, кажется, неправильный

2024-03-28 12:56 UTC, debnatkh commented on cloud/filestore/libs/storage/tablet/tablet_tx.h
> +    struct TAddData : TSessionAware
Во всём файле так

2024-03-28 14:17 UTC, merged