733: render suspended and dirty states in DR monpage
ydb-platform/nbs pull request #735
Opened 2024-03-13 19:38 UTC by komarevtsev-d

2024-03-14 05:24 UTC, drbasic requested changes

2024-03-14 05:24 UTC, drbasic commented on cloud/blockstore/libs/storage/disk_common/monitoring_utils.h
> +    uint16_t flags = EDeviceStateFlags::NONE,
EDeviceStateFlags

2024-03-14 05:24 UTC, drbasic commented on cloud/blockstore/libs/storage/disk_registry/disk_registry_actor_monitoring.cpp
> +                uint16_t flags =
EDeviceStateFlags

2024-03-14 06:38 UTC, drbasic submitted a review, later dismissed

2024-03-14 16:55 UTC, sharpeye approved these changes

2024-03-14 16:55 UTC, sharpeye commented on cloud/blockstore/libs/storage/disk_common/monitoring_utils.h
> +    SUSPENDED = 1 << 3,
М.б. выровнять?
```
    NONE      = 0,
    FRESH     = 1 << 0,
    DISABLED  = 1 << 1,
    DIRTY     = 1 << 2,
    SUSPENDED = 1 << 3,
```

2024-03-15 04:32 UTC, drbasic approved these changes

2024-03-15 09:32 UTC, merged