issue-733: Add a link in volume monpage to DR
ydb-platform/nbs pull request #761
Opened 2024-03-16 19:10 UTC by komarevtsev-d

2024-03-17 05:16 UTC, drbasic commented on cloud/blockstore/libs/storage/volume/volume_actor.cpp
> +            new TEvDiskRegistryProxy::TEvGetDrTabletInfoRequest());
ты планируешь отправку сообщения самому себе, а надо в  MakeDiskRegistryProxyServiceId()

2024-03-17 06:42 UTC, drbasic approved these changes

2024-03-17 09:13 UTC, budevg requested changes

2024-03-17 09:13 UTC, budevg commented on cloud/blockstore/libs/storage/volume/volume_actor.cpp
> +            TInstant::Seconds(3),
let's define some const to name the magic `3 seconds` number
something like 
```c++
constexpr TDuration TabletInfoRequestRetryInterval = TInstant::Seconds(3);
```

2024-03-17 14:39 UTC, budevg requested changes

2024-03-17 14:39 UTC, budevg commented on cloud/blockstore/libs/storage/volume/volume_actor.cpp
> +        constexpr TInstant DRTabletIdRequestRetryInterval =
please move it outside of the function and class
similar to how it's done here https://github.com/ydb-platform/nbs/blob/8d8cdc34ca22b227aef86313f87dbb075723bfb4/cloud/blockstore/libs/storage/ss_proxy/path_description_backup.cpp#L23

2024-03-17 17:10 UTC, budevg approved these changes

2024-03-18 06:30 UTC, drbasic approved these changes

2024-03-18 06:54 UTC, merged