limit the number of connect attemptr for cached tablet in volume proxy
ydb-platform/nbs pull request #799
Opened 2024-03-22 12:26 UTC by yegorskii

2024-03-26 19:02 UTC, qkrorlqr requested changes

2024-03-26 19:02 UTC, qkrorlqr commented on cloud/blockstore/config/storage.proto
> +    optional uint32 VolumeProxyCacheRetryLimit = 359;
а как посчитать, сколько времени мы будем ретраить в зависимости от кол-ва попыток? нам же на самом деле интересно конфигурировать через задание времени - типа "ретрай 5 минут, если за 5 минут не приконнектился к таблетке - тогда подескрайби"

2024-03-26 20:03 UTC, yegorskii commented on cloud/blockstore/config/storage.proto
> +    optional uint32 VolumeProxyCacheRetryLimit = 359;
Так мы сами-то в volume proxy не ретраим, а делаем это когда приходят запросы. Поэтому и указание времени вместо количества попыток не удобно потому что между двумя последовательными запросами может проходить произвольное время.

2024-03-26 20:05 UTC, yegorskii commented on cloud/blockstore/config/storage.proto
> +    optional uint32 VolumeProxyCacheRetryLimit = 359;
Дефолтные настройки клиента - это увеличивающийся таймаут с шагом 500мс. Т.е здесь 14 секунд

2024-03-26 20:14 UTC, qkrorlqr commented on cloud/blockstore/config/storage.proto
> +    optional uint32 VolumeProxyCacheRetryLimit = 359;
> Так мы сами-то в volume proxy не ретраим, а делаем это когда приходят запросы. Поэтому и указание времени вместо количества попыток не удобно потому что между двумя последовательными запросами может проходить произвольное время.

ну тогда получается странная логика - таблетка нагруженного диска полежит секунду и все - мы из кеша вымоем запись

а для ненагруженного удаленного диска можем держать таблетку в кэше долго 

> Дефолтные настройки клиента - это увеличивающийся таймаут с шагом 500мс. Т.е здесь 14 секунд

ты про durable-клиента? это же от параллельности зависит
задаст тебе юзер 8 запросов параллельно в момент, когда таблетка недоступна, и все, выкинешь из кеша запись

2024-04-02 15:14 UTC, qkrorlqr commented on cloud/blockstore/config/storage.proto
> +    // switching to describe volume.
в миллисекундах или в чем измеряется?

2024-04-02 15:14 UTC, qkrorlqr commented on cloud/blockstore/libs/storage/volume_proxy/volume_proxy_ut.cpp
> +    Y_UNIT_TEST(ShouldRunDescribeForCachedTabletsIfNumberOfConnFailExceedsThreshold)
название теста теперь неправильное

2024-04-02 15:17 UTC, yegorskii commented on cloud/blockstore/config/storage.proto
> +    // switching to describe volume.
У нас же время в конфигах всегда в миллисекундах

2024-04-02 17:06 UTC, qkrorlqr approved these changes

2024-04-03 08:51 UTC, BarkovBG approved these changes

2024-04-03 08:53 UTC, merged