NBSNEBIUS-31: add degradation test to ci/runner
ydb-platform/nbs pull request #81
Opened 2024-01-09 17:22 UTC by debnatkh

2024-01-10 20:41 UTC, qkrorlqr commented on cloud/storage/core/tools/ci/runner/run_degradation_test.sh
> +monitoring_url="https://monitoring.nebius.ai/projects/yc.nbs.cloud/dashboards"
давай это не будем заливать в гит, а вынесем в переменные окружения на ci vm или в файл там же

2024-01-15 11:42 UTC, qkrorlqr submitted a review, later dismissed

2024-01-17 11:16 UTC, budevg requested changes

2024-01-17 11:16 UTC, budevg commented on cloud/storage/core/tools/ci/runner/degradation_test.py
> +        for result in results:
There is no way to differentiate between the results in the generated report. Better add something to `description` field which makes it clear.

2024-02-15 17:09 UTC, budevg approved these changes

2024-02-28 18:39 UTC, jkuradobery approved these changes

2024-02-28 19:03 UTC, merged