issue-196: a testing tool which issues write requests and then starts to modify the data buffer
ydb-platform/nbs pull request #821
Opened 2024-03-25 19:36 UTC by qkrorlqr

This tool is needed to check whether our checksum logic may be affected by a "misbehaving" guest (which changes the data buffer after sending a write request)

#196

2024-03-25 19:41 UTC, debnatkh submitted a review, later dismissed

2024-03-25 20:33 UTC, SvartMetal submitted a review, later dismissed

2024-03-26 10:08 UTC, drbasic requested changes

2024-03-26 10:08 UTC, drbasic commented on cloud/blockstore/tools/testing/bad-guest/lib/io.cpp
> +        memset(alignedPtr, 0, sz);
Создание строки 
  TString buffer(sz + BlockSize, 0);
не гарантирует что внутри буфера будут одни нули?

2024-03-26 10:08 UTC, drbasic commented on cloud/blockstore/tools/testing/bad-guest/lib/io.cpp
> +        auto f = AsyncIO.Write(File, alignedPtr, sz, offset);
тут нужен комментарий, что все затевалось ради этих строк, запустили запись и пишем в буфер, который отправили на запись.

2024-03-26 11:50 UTC, qkrorlqr commented on cloud/blockstore/tools/testing/bad-guest/lib/io.cpp
> +        memset(alignedPtr, 0, sz);
Да, гарантирует, я туда-сюда код двигал и memset забыл стереть

2024-03-26 11:58 UTC, qkrorlqr commented on cloud/blockstore/tools/testing/bad-guest/lib/io.cpp
> +        for (ui64 i = 0; i < sz; ++i) {
да, я еще подумал - наверное, смысла мало
если даже между этим кодом и nbs делается memcpy, то все равно мы напоремся на simd и у нас не будет красивых aaaa...AAAA или AAAA...aaaa, а будут aaAAaaAaaAa..AAaaA

2024-03-26 12:16 UTC, drbasic approved these changes

2024-03-26 12:38 UTC, merged