[CI]: Add teamcity tests badge for nb-nbs-stable-lab
ydb-platform/nbs pull request #841
Opened 2024-03-27 18:54 UTC by jkuradobery

2024-03-27 19:03 UTC, qkrorlqr requested changes

2024-03-27 19:03 UTC, qkrorlqr commented on cloud/storage/core/tools/ci/runner/index.xsl
> +    <xsl:variable name="badge-url" select="concat('https://', $teamcity-domain, '/guestAuth/app/rest/builds/buildType:(id:', $teamcity-build-configuration-name, ')/statusIcon')"/>
длинная строка

2024-03-27 19:03 UTC, qkrorlqr commented on cloud/storage/core/tools/ci/runner/index.xsl
> +<xsl:template name="teamcity-badge">
сделай лучше без имени - через match

2024-03-27 19:03 UTC, qkrorlqr commented on cloud/storage/core/tools/ci/runner/index.xsl
> +                    <xsl:for-each select="nb-nbs-stable-lab-teamcity-tests/child::*">
тут можно заменить for-each на apply-templates match="nb-nbs-stable-lab-teamcity-tests/child::*"

2024-03-28 15:20 UTC, qkrorlqr approved these changes

2024-03-28 15:46 UTC, SvartMetal approved these changes

2024-03-28 17:02 UTC, merged