NBS-4358: added test_override_storage_discovery_config
ydb-platform/nbs pull request #85
Opened 2024-01-09 19:02 UTC by sharpeye

2024-01-10 11:22 UTC, budevg requested changes

2024-01-10 11:22 UTC, budevg commented on cloud/blockstore/tests/storage_discovery/test.py
> +    disk_agent_configurator.files["disk-agent"] = disk_agent_dynamic_config
it's not so clear that the config from disk_agent_dynamic_config is different then the config you override in cms ... maybe better generate the config explicitly in the test and then modify it and configure the cms with the changed version, this way whoever reads the test can notify the intention to override the dynamic config with the config in cms

2024-01-11 12:13 UTC, budevg approved these changes

2024-01-16 13:32 UTC, umed approved these changes

2024-01-16 13:48 UTC, budevg approved these changes

2024-01-16 13:48 UTC, merged