NBSNEBIUS-85: add manifests for nbs; support volume attach via nbd
ydb-platform/nbs pull request #875
Opened 2024-04-02 14:53 UTC by sanek325

2024-04-02 14:59 UTC, dvrazumov requested changes

2024-04-02 14:59 UTC, dvrazumov commented on cloud/blockstore/tools/csi_driver/README.md
> +kubectl apply -f ./deploy/manifests/5-nbs-deployment.yaml
опечатка

2024-04-02 14:59 UTC, dvrazumov commented on cloud/blockstore/tools/csi_driver/deploy/manifests/6-nbs-daemonset.yaml
> +            - "--verbose"
Добавь, пожалуйста, 
`            - "--mon-port=8766"
`

2024-04-02 15:39 UTC, sanek325 commented on cloud/blockstore/tools/csi_driver/README.md
> +kubectl apply -f ./deploy/manifests/5-nbs-deployment.yaml
глаз алмаз, спасибо, поправил

2024-04-02 15:40 UTC, sanek325 commented on cloud/blockstore/tools/csi_driver/deploy/manifests/6-nbs-daemonset.yaml
> +            - "--verbose"
Добавил, но в конфиг файл.
Тут эти арги вообще не нужны, выпилил.

2024-04-02 15:57 UTC, dvrazumov submitted a review, later dismissed

2024-04-02 16:16 UTC, dvrazumov submitted a review, later dismissed

2024-04-04 08:51 UTC, yegorskii approved these changes

2024-04-04 08:54 UTC, dvrazumov approved these changes

2024-04-04 10:54 UTC, merged