NBSNEBIUS-127: add data scrubbing for mirrored disks
ydb-platform/nbs pull request #954
Opened 2024-04-11 17:21 UTC by WilyTiger

#502

2024-04-16 11:01 UTC, qkrorlqr requested changes

2024-04-16 11:01 UTC, qkrorlqr commented on cloud/blockstore/libs/storage/partition_nonrepl/part_mirror_ut.cpp
> +    Y_UNIT_TEST(ShouldFindChecksumMismatchInFirstRange)
FirstRange - это не какой-то особый случай, тест не должен подчеркивать, что он именно первый range проверяет 

И вообще ему бы лучше не только первый проверять, а как-то более общо - первый и последний, например. Потому что легко представить себе баг, который проявится в том, что скраббинг будет проверять только первый рейнж (например, забыть в коде ++ScrubbingRangeId или ScheduleScrubbingNextRange)

2024-04-16 11:01 UTC, qkrorlqr commented on cloud/blockstore/libs/storage/partition_nonrepl/part_mirror.cpp
> +    bool dataScrubbingNeeded)
собственно, включать скраббинг мы будем наверняка просто через TStorageConfig

2024-04-19 18:39 UTC, qkrorlqr commented on cloud/blockstore/config/storage.proto
> +    // Enable data scrubbing for mirrores disks.
mirrores -> mirrored

2024-04-19 18:46 UTC, qkrorlqr commented on cloud/blockstore/libs/storage/partition_nonrepl/part_mirror_actor.cpp
> +    for (size_t i = 0; i < checksums.size(); i++) {
i = 1

2024-04-19 18:46 UTC, qkrorlqr commented on cloud/blockstore/libs/storage/partition_nonrepl/part_mirror_actor.cpp
> +        }
break

2024-04-19 18:51 UTC, qkrorlqr commented on cloud/blockstore/libs/storage/partition_nonrepl/part_mirror_actor.cpp
> +    ScheduleScrubbingNextRange(ctx);
а если у нас будет undelivery для нескольких запросов на вычисление чексумм, мы несколько раз Scrubbing запустим параллельно?

2024-04-19 18:58 UTC, qkrorlqr commented on cloud/blockstore/libs/storage/partition_nonrepl/part_mirror_ut.cpp
> +        runtime.SetObserverFunc([&] (auto& event) {
EventFilter

2024-04-19 18:59 UTC, qkrorlqr commented on cloud/blockstore/libs/storage/partition_nonrepl/part_mirror_ut.cpp
> +                rangeCount++;
++rangeCount

2024-04-19 19:00 UTC, qkrorlqr commented on cloud/blockstore/libs/storage/partition_nonrepl/part_mirror_ut.cpp
> +                rangeCount++;
++rangeCount

2024-04-19 19:01 UTC, qkrorlqr commented on cloud/blockstore/libs/storage/partition_nonrepl/part_mirror_ut.cpp
> +
лишняя пустая строка

2024-04-19 19:01 UTC, qkrorlqr commented on cloud/blockstore/libs/storage/partition_nonrepl/part_mirror_ut.cpp
> +        runtime.SetObserverFunc([&] (auto& event) {
EventFilter

2024-04-19 19:01 UTC, qkrorlqr commented on cloud/blockstore/libs/storage/partition_nonrepl/part_mirror_ut.cpp
> +                        state = REQUESTS_RECIEVED;
REQUESTS_RECEIVED

2024-04-19 19:03 UTC, qkrorlqr commented on cloud/blockstore/libs/storage/partition_nonrepl/part_mirror_ut.cpp
>  }
нужен тест, проверяющий, что scrubbing не завершается после одного прохода по диску, а продолжает работать дальше

2024-04-19 19:06 UTC, qkrorlqr requested changes
Нужен счетчик throughput или rps scrubbing-а 
Чтоб видеть, что scrubbing работает с ожидаемой скоростью (по дефолту 4MiB в 50ms, то есть 80MiB/s)

2024-04-30 15:36 UTC, WilyTiger commented on cloud/blockstore/libs/storage/partition_nonrepl/part_mirror_ut.cpp
>  }
Добавила в ShouldFindChecksumMismatch

2024-05-03 11:19 UTC, drbasic requested changes

2024-05-03 11:19 UTC, drbasic commented on cloud/blockstore/libs/storage/partition_nonrepl/part_mirror_state.h
> +    TNonreplicatedPartitionConfigPtr PartConfig;
const и сразу после  const TStorageConfigPtr Config;

2024-05-03 11:19 UTC, drbasic commented on cloud/blockstore/libs/storage/partition_nonrepl/part_mirror_actor.h
> +    ui64 ScrubbingRangeId = 0;
можно ли легко получить ScrubbingRange из ScrubbingRangeId  ? если да, то зачем хранить ?

2024-05-03 15:08 UTC, qkrorlqr commented on cloud/blockstore/libs/storage/partition_nonrepl/part_mirror_actor.cpp
> +    if (WriteIntersectsWithScrubbing) {
Если код не усложнится - ок

2024-05-07 11:07 UTC, drbasic submitted a review, later dismissed

2024-05-07 12:11 UTC, qkrorlqr commented on cloud/blockstore/libs/storage/partition_nonrepl/part_mirror_actor.cpp
> +    ScrubbingThroughput += ResyncRangeSize;
лучше не завязываться лишний раз на некую константу вне этого модуля, а сделать ScrubbingThroughput += scrubbingRange.Size()
и, кстати, еще надо на BlockSize умножить

2024-05-07 12:11 UTC, qkrorlqr commented on cloud/blockstore/libs/storage/partition_nonrepl/part_mirror_actor.cpp
> +    ScrubbingRangeId++;
++ScrubbingRangeId;

2024-05-07 13:06 UTC, WilyTiger commented on cloud/blockstore/libs/storage/partition_nonrepl/resync_range.cpp
> -    if (!ChecksumRangeActorCompanion.IsFinished()) {
Бага не было. Поменялась логика этого Finished. Раньше он считался Finished, когда ошибка случалась и не дожидался остальных чексумм. В случае ресинка можно не ждать оставшиеся чексуммы и завершить работу актора. А в случае скраббинга нужно дождаться все чексуммы, чтобы на следующей итерации скраббинга не словить левые чексуммы

2024-05-07 16:48 UTC, qkrorlqr approved these changes

2024-05-07 17:29 UTC, merged