topic api: use a single write session
ydb-platform/nbs pull request #956
Opened 2024-04-11 21:18 UTC by sharpeye

2024-04-25 11:47 UTC, sanek325 approved these changes

2024-04-25 14:34 UTC, EvgeniyKozev commented on cloud/blockstore/libs/logbroker/topic_api_impl/topic_api.cpp
> +    TFuture<NProto::TError>
Мы так раньше не писали возвращаемое значение на новой строке

2024-04-25 14:34 UTC, EvgeniyKozev commented on cloud/blockstore/libs/logbroker/topic_api_impl/topic_api.cpp
> +            return MakeFuture(MakeError(E_REJECTED, "Write in progress"));
E_TRY_AGAIN?

2024-04-25 14:34 UTC, EvgeniyKozev commented on cloud/blockstore/libs/logbroker/topic_api_impl/topic_api.cpp
> +        if (WriteInProgress.test_and_set()) {
А почему они не накапливаются?
Формируй новый батч, зачем тут реджектить то?

2024-04-25 14:34 UTC, EvgeniyKozev commented on cloud/blockstore/libs/logbroker/topic_api_impl/topic_api.cpp
>          auto self = shared_from_this();
А почему тут делаешь shared_ptr, а не weak_ptr?
Пока идет обработка батча, я ни как объект не разрушу?

2024-04-25 14:34 UTC, EvgeniyKozev commented on cloud/blockstore/libs/logbroker/topic_api_impl/topic_api.cpp
> +        Session->Write(
А записать сразу весь батч нельзя? Циклом?

2024-04-25 20:21 UTC, sharpeye commented on cloud/blockstore/libs/logbroker/topic_api_impl/topic_api.cpp
> +    TFuture<NProto::TError>
Это clang-format

2024-04-26 08:25 UTC, sharpeye commented on cloud/blockstore/libs/logbroker/topic_api_impl/topic_api.cpp
> +        if (WriteInProgress.test_and_set()) {
Чтобы не усложнять. В реальной жизни этот сервис используется в DR, а DR ждёт завершения пред. записи.

2024-04-26 08:51 UTC, sharpeye commented on cloud/blockstore/libs/logbroker/topic_api_impl/topic_api.cpp
> +        Session->Write(
Неа, только по-одному сообщению. https://github.com/ydb-platform/nbs/blob/main/contrib/ydb/public/sdk/cpp/client/ydb_topic/topic.h#L1657

2024-04-26 09:11 UTC, sharpeye commented on cloud/blockstore/libs/logbroker/topic_api_impl/topic_api.cpp
>          auto self = shared_from_this();
Надо дёрнуть Stop - сессия закроется, обработка завершится. Если передать weak, то batch может быть разрушен раньше времени, пока он используется сессией.

2024-04-30 11:04 UTC, sanek325 approved these changes

2024-05-06 10:31 UTC, sdimanx91 requested changes

2024-05-06 10:31 UTC, sdimanx91 commented on cloud/blockstore/libs/logbroker/topic_api_impl/topic_api.cpp
> +        std::unique_lock lock{DriverMutex};
std::scoped_lock

2024-05-06 10:31 UTC, sdimanx91 commented on cloud/blockstore/libs/logbroker/topic_api_impl/topic_api.cpp
> +    NYdb::TDriver& GetDriver()
Я бы сделал так:
```
const NYdb::TDriver& GetDriver()
```

Насколько я понял, единственное, что произойдет копирование указателя Pimpl `TImpl` из `TDriver`, Сам Driver не будет изменен. Кажется)

2024-05-06 10:50 UTC, sharpeye commented on cloud/blockstore/libs/logbroker/topic_api_impl/topic_api.cpp
> +        , Timestamp(timestamp)
TInstant не умеет муваться, оно как ui64. Что скажет coverity, кстати, если мувать то, что не имеет конструктора от && ?

2024-05-06 11:18 UTC, sdimanx91 commented on cloud/blockstore/libs/logbroker/topic_api_impl/topic_api.cpp
> +        , Timestamp(timestamp)
Ничего не скажет, по идее. Я таких сообщений не видел,

2024-05-06 11:19 UTC, sdimanx91 approved these changes

2024-05-08 10:47 UTC, sdimanx91 approved these changes

2024-05-13 09:33 UTC, sanek325 approved these changes

2024-05-13 15:38 UTC, merged